### ISSUE TITLE
Arrays 6.1.3

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/RunestoneComponents#1000]
Error reported in course AAHuronCovidJava on page topic-6-1-array-basics by user HuronDemo huron_demo@aaps.k12.mi.us
The original problem is: to enter an answer to load an element from the cars array, "Volvo", into a String variable, s. Volvo is the 2nd element so the answer should be:
String s = cars[1];
but it is not being accepted

**Comment by citelms** [comment]
This does work, but maybe you're typing in the semicolon. Do not type in the semicolon since it's already there at the end.
![image](https://user-images.githubusercontent.com/37457040/79762481-d6756080-82f0-11ea-84fb-8af8428288f8.png)
