### ISSUE TITLE
module 'runestone' has no attribute 'codelens'

### ISSUE THREAD

**Issue by Kikolo3000** [RunestoneInteractive/RunestoneComponents#1001]
I am trying to install the RunestoneComponents package, following the README.rst documentation. I am getting the following error at the moment of running the comand `runestone init`:
![image](https://user-images.githubusercontent.com/44951468/79969165-65b97a00-8491-11ea-9bdf-537106c33df9.png)

**Comment by bnmnetp** [comment]
This is a problem because you are using Python 3.6.

**Comment by Kikolo3000** [comment]
Very true, thanks!
