### ISSUE TITLE
For a custom created course, students cannot mark 'Exercises' as 'completed'

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/RunestoneComponents#1013]
Error reported in course Minerva_Python_Summer_Prep on page Any Exercises chapter by user Svitlana.mm svitlana@minerva.kgi.edu
I am an instructor. My course is based on thicspy book, but so,e exercises were custom created. My students reported that they cannot mark those exercises as 'completed'.

**Comment by bnmnetp** [comment]
That is by design. With many Exercises pages having hundreds of exercises on them we do not show the mark as completed button.
