### ISSUE TITLE
Practice

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/RunestoneComponents#1014]
Error reported in course fopp on page https://runestone.academy/runestone/assignments/practiceNotStartedYet?message1=Practice+tool+is+not+set+up+for+this+course+yet.&message2=Please+ask+your+instructor+to+set+it+up. by user AlejandroRD alejandro.rivera@udem.edu
On the course of Basics Python (Coursera) the outer source of evaluation, do not have the "Practice Section" available

**Comment by bnmnetp** [comment]
We don't have any control over how coursera configures the server for their courses.
