### ISSUE TITLE
Add a brief description of the questions to the question picker that appears on hover

### ISSUE THREAD

**Issue by bnmnetp** [RunestoneInteractive/RunestoneComponents#1016]
Most questions have a discernable question part that is easy to pick out of the source for the question.  It would be nice if this part of the question was quickly and easily available to the instructor when they are building an assignment.

I propose we add a column to the question table to hold this bit of text and that this bit of text is either

* appended to the question information (type autogradable etc) OR
* made into something that appears as a tooltip when then instructor hovers over the question.

I don't think most instructors need to see the fully rendered component, they just need a quick look at the question to know if it is the one they want to add.

**Comment by bjones1** [comment]
I fully agree -- I've wanted this for a while. I'd suggest using the first sentence/80 characters of a question for the text.

**Comment by bnmnetp** [comment]
Here is a quick prototype of what it could look like:

<img width="1182" alt="Screen Shot 2020-07-06 at 9 57 10 AM" src="https://user-images.githubusercontent.com/51115/86607889-74331000-bf6f-11ea-84ca-c916e831e163.png">

Of course clicking on it still brings up the full preview.

**Comment by bjones1** [comment]
Fantastic! I love it!

**Comment by bnmnetp** [comment]
@bhoffman0 @pearcej @barbarer -- Any thoughts?  I'm going to keep heading down this track by updating other components to store their explanatory text in a database field called description.  Everything gets a default of empty string so it doesn't break any of the components that are not updated.

**Comment by bhoffman0** [comment]
I like it! Is the default to use the first x characters of a question or do we need to add a new description field in each question? I'm hoping it's the first option!

**Comment by bnmnetp** [comment]
It is the first 80 characters from the question text.  So no modification is needed for any existing directive.  Yay!!

**Comment by bhoffman0** [comment]
I really love it then!

**Comment by bnmnetp** [comment]
The only thing that would be easier is if we standardized all of the directives to put their question before the `~~~~` like we do with activecode.  Then we could grab it from a parent class and do it all in one place.  But that is probably best left for a separate PR.

**Comment by barbarer** [comment]
Sounds good to me.

Dr. Barbara Ericson
Assistant Professor, School of Information
University of Michigan

**Comment by bjones1** [comment]
Can't you just pull from the `htmlsrc` field of the `questions` table for this? Why add another field?

**Comment by bnmnetp** [comment]
Because it would be a parsing nightmare.

It is much clearer in the source what the question is than it is in the htmlsrc.

**Comment by bjones1** [comment]
That makes sense.
