### ISSUE TITLE
Adding image datafiles to database

### ISSUE THREAD

**Issue by bhoffman0** [RunestoneInteractive/RunestoneComponents#1020]
Please add image data files like :datafile: arch.jpg to the database so that we can run the picture lab in the grader and assignment pages.  Thank you!
-Beryl

**Comment by bnmnetp** [comment]
I like this idea, although I need to think about it a bit in terms of how to implement it.  datafiles are currently assumed to be text files.  

But this would really be a good solution to the image problem.

**Comment by bnmnetp** [comment]
done!
