### ISSUE TITLE
Possible XSS

### ISSUE THREAD

**Issue by bjones1** [RunestoneInteractive/RunestoneComponents#1021]
Looking through the code used to generate HTML, it seems like there's a *TON* of unescaped, unchecked HTML we add blindly to our components. Anything put into HTML, from div_ids to strings, should be run through `bleach`.

**Comment by bnmnetp** [comment]
Can you point to a couple of examples?  I don't consider HTML that we generate from rst source ourselves as being risky.

**Comment by bjones1** [comment]
I emailed these to you. I'm not sure if this can be entered via the instructor interface, which would be more serious.

**Comment by bjones1** [comment]
I'll close this, since we can discuss via e-mail.
