### ISSUE TITLE
6-2-5:

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/RunestoneComponents#1033]
Error reported in course pathfinders-pd-2020 on page topic-6-2-traversing-arrays by user brandybarlow brandy.barlow@coffee.k12.ga.us
Could you double check the answer to this question please? I understand the indexing of it...but would have thought that it would have doubled each one. I may be wrong however. I'm quite new at this. Thanks for your awesome materials and hard work!

**Comment by bhoffman0** [comment]
Hi Brandy,
I wasn't sure which exercise you meant. Was it Activity 3 ActiveCode (lcal1)? That one does double the array elements. The original array is {2, 6, 7, 12, 5} and the resulting output is 4 12 14 24 10. Similarly Activity 5 ActiveCode (lclp1) doubles the first 5 elements.
-Beryl
