### ISSUE TITLE
Cannot access through Coursera

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/RunestoneComponents#1039]
Error reported in course fopp on page https://fopp.umsi.education/books/published/fopp/PythonModules/intro-ModulesandGettingHelp.html by user mnkamion mnkamion@yahoo.com
Cannot access Runestone links from Coursera "Python Basics" course - requests that I login through Coursera to access; however, I am logged in - also tried logging out and logging back in and I get the same message.

**Comment by bnmnetp** [comment]
We have no control over the servers that Coursera uses with Runestone.
