### ISSUE TITLE
installation failure - errors

### ISSUE THREAD

**Issue by elmtang** [RunestoneInteractive/RunestoneComponents#1041]
Try to follow the youtube tutorial to install Runestone and get the following errors 
OS: Ubuntu 18.4 on AWS 

ubuntu@ip-172-26-8-249:~/Runestone/RunestoneComponents$ npm install
npm ERR! addLocal Could not install /home/ubuntu/Runestone/RunestoneComponents/-@0.0.1
npm ERR! Linux 4.15.0-1021-aws
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! path /home/ubuntu/Runestone/RunestoneComponents/-@0.0.1
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/home/ubuntu/Runestone/RunestoneC
omponents/-@0.0.1'
npm ERR! enoent ENOENT: no such file or directory, open '/home/ubuntu/Runestone/RunestoneC
omponents/-@0.0.1'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/Runestone/RunestoneComponents/npm-debug.log

Thanks

**Comment by bnmnetp** [comment]
You need at least version 5 of npm, I'm using 6.14.4 for my development.  Its a webpack requirement.  I thought 18.04 was beyond version 3.

**Comment by elmtang** [comment]
Got it, thanks!
