### ISSUE TITLE
audio tour button does nothing on local server

### ISSUE THREAD

**Issue by cchaz003** [RunestoneInteractive/RunestoneComponents#1044]
**What Course are you in**
thinkcspy - locally hosted server

**What Page were you on**
4.3 Instances - A Herd Of Turtles (or other audio tour pages)

**Describe the bug**
I'm not entirely sure where to ask this question so if this is the wrong place, please let me know. I've been working on getting a runestone server setup for this fall and I've gotten pretty far but I'm currently stuck on how to get audio tours to work properly. The button shows up but when pressed it does nothing (no error in the browser nor in the server console). At first I assumed this was a problem with the book we're putting together but I just built a fresh copy of thinkcspy on our server and that's not working either so it would seem to me that this is related to the server install. 

I tried following the server install guide as best as I could and built a script that takes care of the installation. The script can be found here: [https://github.com/cromerMHC/RunestoneInstaller/blob/master/RunestoneInstaller.sh](https://github.com/cromerMHC/RunestoneInstaller/blob/master/RunestoneInstaller.sh) and is intended to do a full installation only asking the user to create a database user (it's not the best installation solution but I needed something that could be tested over and over while I sort out any issues like this one). I assume I'm just missing something...

Hopefully someone can take a look and let me know if something looks fishy. 

**Additional context**
I've been doing my testing on an ubuntu server 20.04 VM.

**Comment by bnmnetp** [comment]
Fixed in 5.0.13
