### ISSUE TITLE
uploading bulk students

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/RunestoneComponents#1045]
Error reported in course RIT_principles_of_computing on page https://runestone.academy/runestone/admin/admin by user cxbppr cxbppr@rit.edu
System errors out each time i load a csv file on the first record - complains "name already exists" if i remove the name it does the same for the next name on the list -- i was able to add 47 students one-time but there was a student missing so i deleted all the students and and now trying to upload the new csv file and will not work -- very critical that i can do this ASAP - students are waiting for access

**Comment by bnmnetp** [comment]
Why did you delete the students?  Why didn't you just add the one additional student in a new csv file?

You cannot actually delete students.  Removing them from your course does not delete the student.  A student may delete their account but they are the only one's that have the permission to completely delete an account once it is created.
