### ISSUE TITLE
Parson's not working with touch events

### ISSUE THREAD

**Issue by abkfenris** [RunestoneInteractive/RunestoneComponents#105]
Currently Parson's problems does not work with touch events. Currently they appear to be only looking for click or drag events, which iOS and other mobile devices don't use.

![withouttouchpunch](https://cloud.githubusercontent.com/assets/1296209/11215297/7bb0cef0-8d13-11e5-8b8e-21cb33f8bfcd.gif)

The js-parsons library works with iOS currently.

![js-parsons](https://cloud.githubusercontent.com/assets/1296209/11215941/a61bb83c-8d16-11e5-820f-a38687e2883f.gif)

**Comment by bnmnetp** [comment]
fixed #110
