### ISSUE TITLE
Unable to log students in

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/RunestoneComponents#1052]
Error reported in course CHS20-APCSA on page Nonhttps://runestone.academy/runestone/books/published/csawesome/index.htmle by user beauchampc beauchampc@chsvb.org
Requesting: remove all student accounts with the @chsvb.org email addresses from your database so that they can set up their accounts themselves. 
Attempted to access students' account unsuccessfully. Theseaccounts were set up with a csv. and all of these accounts are stating that the email addresses are in the database, but their usernames are invalid. Attempted to remove a student from the course and enable them to create their own account - this was also unsuccessful as the student's email address was still in the system. Had their username sent to their email address successfully but when attempting to reset their password - it wasn't recognizing the username - We used the username and not the email address as you shared is commonly the problem

**Comment by cherbeauch** [comment]
This has been resolved - the username cell had a space added at the end of username which is why it wasn't working.
