### ISSUE TITLE
Can't add student to my account

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/RunestoneComponents#1058]
Error reported in course Period_2_APCS_A on page index by user mrhollaway dph5259@lausd.net
Hello,

I am trying to add a student but I get a message saying the student is already in the classroom (alara0116). However, when I look on my classroom roster they are not on the roster. How can I fix this?

**Comment by bhoffman0** [comment]
It sounds like the student already has a Runestone account and is probably enrolled in the wrong course. Ask the student to login   at runestone.academy and click on Sign Up and type in your course name Period_2_APCS_A and click on Apply Changes.
