### ISSUE TITLE
Exam does not allow box clicking. 

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/RunestoneComponents#1061]
Error reported in course APCSP-TBrown on page Exercises by user WHudson william.hudson@student.nhcs.net
When I try to take the exam, it shows a red circle with a line through it  and does not allow me to click start, pause, finish or any of the question answers.  I have not clicked "finish exam" yet.  I am working in Chrome on a personal laptop.  I have tried on my Moms laptop too.  Same issue.

**Comment by bnmnetp** [comment]
You already attempted that exam. Your teacher will need to reset it.
