### ISSUE TITLE
A question has the wrong answer on the marking scheme

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/RunestoneComponents#1080]
Error reported in course COSC1306-17524 on page index by user aamille4 aamille4@cougarnet.uh.edu
In the "MIDTERM TEST 1" assignment question I selected the right answer, but was marked as wrong. The question was selecting the correct output for a for loop printing its range, in range(0,10,2). The answer included 10.  I double checked on the runestone IDE and found that the output in the IDE went to 8 and not to 10 like like the the webpage said.

**Comment by bnmnetp** [comment]
Please take this up with your instructor.
