### ISSUE TITLE
Vulnerability in timed exams that webpage can be inspected and <div id="timed_Test" style="display:none"> edited to "display:initial" to reveal exam questions without starting exam

### ISSUE THREAD

**Issue by vqum** [RunestoneInteractive/RunestoneComponents#1083]
Inspecting webpage:
![2020 10 09  timed exam display initial issue1](https://user-images.githubusercontent.com/40499850/95618011-57a8e700-0a3a-11eb-86f1-5eb737c41ea8.png)

Editting `<div id="timed_Test" style="display:none">` to `"display:initial"` reveals the question navigation numbers:
![2020 10 09  timed exam display initial issue2](https://user-images.githubusercontent.com/40499850/95618012-58417d80-0a3a-11eb-8e2b-c726bbcc1a61.png)

Clicking question navigation numbers reveals exam questions, all while exam time has not been started:
![2020 10 09  timed exam display initial issue3](https://user-images.githubusercontent.com/40499850/95618013-58417d80-0a3a-11eb-80ba-308b2c381db9.png)

It seems like this originates in `RunestoneComponents > runestone > timed > js > timed.js` on line 175 `style: "display:none",`:
![2020 10 09  timed exam display initial issue4](https://user-images.githubusercontent.com/40499850/95618386-f5041b00-0a3a-11eb-8217-7271991df5ba.png)

**Comment by bjones1** [comment]
This is a fundamental limit of the Runestone design. If you enable server-side grading, then the answers won't be visible for fill-in-the-blank questions only. (We haven't implemented server-side grading for other question types yet.)

So, this isn't a viable approach for high-stakes assessment -- it's better for low-stakes environments.
