### ISSUE TITLE
pip install fails on Python 3.9.x on Windows 10

### ISSUE THREAD

**Issue by schellenberg** [RunestoneInteractive/RunestoneComponents#1113]
Currently, you cannot install runestone on Windows 10 with Python 3.9. This is due to the version of lxml being used (4.5.1). However, the current version of lxml (4.6.2) can be installed via pip just fine. 

Can you update the requirements.txt file to either:
- lxml==4.6.2               # assuming this version doesn't have any backwards-incompatibilities

OR  

- lxml>=4.5.1

Thanks!

**Comment by bnmnetp** [comment]
Or you could make a PR? 😄 Its hard for one person to keep up.
