### ISSUE TITLE
Resizing active code window seems to be capped at a maximum height

### ISSUE THREAD

**Issue by vqum** [RunestoneInteractive/RunestoneComponents#1118]
Example from [Overview book 1.1. ActiveCode Examples in Python](https://runestone.academy/runestone/books/published/overview/ActiveCode/python.html) the 2nd active code window with code that produces the Sierpinski Triangle
![image](https://user-images.githubusercontent.com/40499850/104063603-70a46e00-51ca-11eb-87dc-c62ea63d493a.png)

When dragging the bottom right corner to increase the height, upon reaching some height threshold it appears to not display any additional vertical
![image](https://user-images.githubusercontent.com/40499850/104063635-7ac66c80-51ca-11eb-8849-701863606bc2.png)

**Comment by bnmnetp** [comment]
Yes, it is capped at a maximum height.  What purpose does it server to make it even bigger?

**Comment by bjones1** [comment]
I've written programs in an active code problem that are more than 22 lines long, and find that size can be limiting. Is this some setting that's easy to remove?

If not (meaning we want to restrict the max size to 22 lines), there should be something to prevent users from exceeding the max size. Currently, you can resize the window larger than 22 lines but the extra space is just empty / odd looking.

**Comment by bnmnetp** [comment]
fixed
