### ISSUE TITLE
Missing line numbers on active code in a timed exam

### ISSUE THREAD

**Issue by barbarer** [RunestoneInteractive/RunestoneComponents#1124]
The active code in a timed exam do not show line numbers on the code.

**Comment by bnmnetp** [comment]
They are not missing they were purposely removed.

**Comment by barbarer** [comment]
Why?  Can we have the option to turn them back on? When students get compiler errors I want them to know which line it is on.

**Comment by bnmnetp** [comment]
I do not remember why.  but the code checks to see if it is in a timed exam and disables line numbers.

So, someone at some point wanted it that way.

Making everything an option is not an option in my opinion. It just makes everything more complicated to maintain and test.

I can turn the line numbers back on as I really don't think it hurts to have them there.

**Comment by barbarer** [comment]
I agree, that I don't see why it would hurt and it certainly hurts to not have them.
