### ISSUE TITLE
Unit tests in fopp involving search in getEditorText() are failing

### ISSUE THREAD

**Issue by jonnycomes** [RunestoneInteractive/RunestoneComponents#1126]
Exercises in fopp such as TL_365_ex_2_11 and ex_2_6_jcomes include unit tests for checking that the input function is used in the code. The unit test only checks that the string 'input' is somewhere in the code using the following assertion:

self.assertTrue(re.search('input', self.getEditorText()), 'Checking that input is used.')

These unit tests were working fine in the Fall, but are now failing. More precisely, these unit tests are failing when code is run in the book (first image below), but passing when identical code is run in an Instructor's Page (second image below). 

![image](https://user-images.githubusercontent.com/43709428/105041696-8adb1900-5a20-11eb-91fb-e51b5d39e826.png)
![image](https://user-images.githubusercontent.com/43709428/105041727-9595ae00-5a20-11eb-8e45-483a10fd1952.png)

**Comment by bnmnetp** [comment]
I've been fixing a lot of bugs internal to active codes the last couple weeks.   I can reproduce this problem on runestone.academy, but I cannot reproduce the problem on my dev machine.  🎉. I'll be doing a release on Saturday so this should not be an issue next week.
