### ISSUE TITLE
Problems with scoring for timed exam

### ISSUE THREAD

**Issue by barbarer** [RunestoneInteractive/RunestoneComponents#1129]
I just tried a timed midterm in my course Win21-SI206 and my score was 0 even though I had most questions correct.  The timed exam was Midterm-1-Fall20-v2.

It also said I skipped all the question in the summary when I went back to the page.

![Screen Shot 2021-01-28 at 3 10 29 PM](https://user-images.githubusercontent.com/43884467/106195213-d8245c80-617d-11eb-8873-e91f2d343bee.png)

**Comment by bnmnetp** [comment]
I have a bunch more fixes ready to go on Saturday.  Scores are showing up correctly on my dev server.

If you are preparing to give an exam I would like to know when so we can be ready rather than reacting.

**Comment by barbarer** [comment]
No, we are not giving a midterm yet.  I just wanted to start testing it to
make sure it would be ready.

Dr. Barbara Ericson
Assistant Professor, School of Information
University of Michigan

**Comment by bnmnetp** [comment]
Great, I've been working with Mark Newman and I feel like we are really close to getting all the bugs squashed. But everyone uses different questions and different elements of selectquestion.  So there are SOOOOOO many different combinations to test.

We will get there!

**Comment by barbarer** [comment]
This seems to be fixed though the grading isn't working yet.

**Comment by bnmnetp** [comment]
Please clarify/open a new Issue about grading not working yet.  I don't understand what about the grading is not working.

**Comment by bnmnetp** [comment]
I have continued to try and test this but as far as I can determine the autograder is behaving and scoring all questions correctly.  So I'm going to need more specifics on what you think is not working.

**Comment by barbarer** [comment]
When I grade the midterm I get 0 for all of my answers even though they are
correct.

Dr. Barbara Ericson
Assistant Professor, School of Information
University of Michigan

**Comment by bnmnetp** [comment]
That doesn't help me.

How do you know you get 0's?  Is it in the grade book?  Is it in the grading interface looking at individual problems?  The summary on the exam itself?  Are you looking at the assignment with the select questions or the actual questions?

In my testing yesterday the grade book accurately reflected the scores.  AND when I looked at the assignment (with the select questions) I saw the correct score for each question.  I am using the two different timed exams in the overview book.

**Comment by barbarer** [comment]
Yes, it was in the gradebook.  I graded the midterm using the grading
interface and then looked at my answers which were correct but had a score
of 0 with autograded.

I am in Win21-SI206 doing Midterm1-Practice-Win21-Timed.

Dr. Barbara Ericson
Assistant Professor, School of Information
University of Michigan
