### ISSUE TITLE
Parsons problems with more than one statement in a block are indented wrong

### ISSUE THREAD

**Issue by ericsonga** [RunestoneInteractive/RunestoneComponents#113]
Since incorporating the latest Parsons stuff we have a problem with the indention on Parsons problems when the block of code contains multiple statements and should be indented.  Only the first line is correct (indention removed) and the rest of the code statements in the block are indented.

**Comment by bnmnetp** [comment]
Barb,

Can you point me at an example?  Or copy paste the parsons example source here?  The test that I have that has code blocks seems to work fine.

Brad

**Comment by ericsonga** [comment]
Here is one of the examples.  Note that the leading white space should be removed on g = p.getGreen() and on b = p.getBlue() but it is only removed on the first line.

Barb

.. parsonsprob:: Image_Decrease_GB

   Another way to get a similar effect to increasing the red, is to decrease the green and blue.  Figure out how to do that in the program above and then use that information to drag the code blocks below from the left to the right in the correct order with the correct indention. 
   -----
   from image import *
   =====
   img = Image("beach.jpg")
   =====
   pixels = img.getPixels()
   for p in pixels:
   =====
       g = p.getGreen()
       b = p.getBlue()
   =====       
       p.setGreen(g * 0.75)
       p.setBlue(b * 0.75)
   =====
       img.updatePixel(p)
   =====
   win = ImageWin(img.getWidth(),img.getHeight())
   img.draw(win)

**Comment by ericsonga** [comment]
When I pasted the code it didn't keep the indention.  Here is a picture.
![screen shot 2016-01-27 at 2 06 06 pm](https://cloud.githubusercontent.com/assets/1844609/12624873/3ba17e30-c4ff-11e5-85ac-4fec06dffab2.png)

**Comment by ericsonga** [comment]
I found the solution for this and it was added to my open pull request.
