### ISSUE TITLE
Move up buttons on timed exams to above the question

### ISSUE THREAD

**Issue by barbarer** [RunestoneInteractive/RunestoneComponents#1130]
The next and prev buttons and question number buttons are showing up below the area I can see.  Can we move them to above the question?  I had to scroll down just to see the next button.

![Screen Shot 2021-01-28 at 2 52 07 PM](https://user-images.githubusercontent.com/43884467/106194952-7f54c400-617d-11eb-8a18-1cf96fb0d6a9.png)

**Comment by bnmnetp** [comment]
How is this?

<img width="925" alt="Screen Shot 2021-02-12 at 4 24 46 PM" src="https://user-images.githubusercontent.com/51115/107835599-f332c700-6d4e-11eb-83c8-6a0a3250ca51.png">

**Comment by barbarer** [comment]
Much better!

Dr. Barbara Ericson
Assistant Professor, School of Information
University of Michigan
