### ISSUE TITLE
Can't see images in fopp Parson's problems pp3_7_1 and pp3_7_2

### ISSUE THREAD

**Issue by jonnycomes** [RunestoneInteractive/RunestoneComponents#1131]
The instructions for problems pp3_7_1 and pp3_7_2 are currently not rendering. In particular, the images are not showing up for those problems.

Edit: The same issue is also happening for pp3_3_1 and pp3_3_2.

![image](https://user-images.githubusercontent.com/43709428/106489785-5d578c00-6472-11eb-9e91-2c754890a222.png)
![image](https://user-images.githubusercontent.com/43709428/106489822-69434e00-6472-11eb-9ef7-244186609f5d.png)

**Comment by bnmnetp** [comment]
Shoot, I updated parsons so that the instructions would be treated as restructured text and fully parsed.  This just means that the raw html tags need to be changed to .. image:: instead.

**Comment by bnmnetp** [comment]
fixed.

**Comment by jonnycomes** [comment]
Thanks Brad!
