### ISSUE TITLE
Parsons problems in timed exams not showing the instructions

### ISSUE THREAD

**Issue by barbarer** [RunestoneInteractive/RunestoneComponents#1139]
In a timed exam the instructions for the Parsons problems are not being displayed.

**Comment by bnmnetp** [comment]
I just committed a fix for this.

**Comment by bnmnetp** [comment]
OK, I'm convinced this is fixed and it will be live tomorrow morning.

**Comment by barbarer** [comment]
Great!

Dr. Barbara Ericson
Assistant Professor, School of Information
University of Michigan

**Comment by barbarer** [comment]
It isn't showing the Parsons problems at all now. When I click next it
stays on the previous question and changes the question number button to
red.

[image: image.png]
Dr. Barbara Ericson
Assistant Professor, School of Information
University of Michigan
