### ISSUE TITLE
Parsons Problems Bug (always says correct when trying after solving)

### ISSUE THREAD

**Issue by bhoffman0** [RunestoneInteractive/RunestoneComponents#1145]
I think there's a new Parsons Problem bug. After you solve it once, students are trying different options without hitting reset and it always says correct no matter what you do after solving it once. I've been telling them to hit reset first, but I've gotten a couple emails about it, so it would be good to fix it so it checks it and removes the "you got it right message" if you try new things after solving.
![image](https://user-images.githubusercontent.com/4571962/110210703-e8a4b280-7e60-11eb-89af-0b66853f805f.png)

**Comment by bnmnetp** [comment]
Thanks Beryl, I haven't made any changes to parsons for weeks, and this looks like something that has been lurking for a long time.

There is a `hasSolved` flag that gets set to true as soon as the student gets the correct answer.  If that flag is true no further grading is done.

@barbarer Do you think this is how it has always been?  What should the correct behavior be?  If a student moves a block once they have the correct answer should we reset the hasSolved flag?  Should we freeze the code once they have the correct answer to force them to reset?

**Comment by barbarer** [comment]
I agree with Beryl that we should grade whatever the solution is.

**Comment by bnmnetp** [comment]
OK, I can make that change.  The grader has logic that checks to see if this.hasSolved is true and if it is the grader just returns without grading again.  Not sure why it was written that way but wanted to check.

**Comment by bnmnetp** [comment]
@barbarer There is a lot of logic built around the hasSolved flag.  I'm not sure we want to just regrade.

What if we forced the student to use a reset if they wanted to try something else?  Its seems to me that once the parsons problem is solved we can disable the ability to move the blocks or simply disable the Check Me button once solved correctly.  

Given that there is only one correct answer I'm not sure what value there is in encouraging students to move the blocks around on a solved problem. ??

**Comment by barbarer** [comment]
I am also fine with forcing them to click the reset button if they want to
solve it again.

Dr. Barbara Ericson
Assistant Professor, School of Information
University of Michigan

**Comment by bnmnetp** [comment]
This is fixed.  The check Me button is disabled after the student gets the correct answer.  They can try other answers by using Reset.
