### ISSUE TITLE
Add question numbers to the assignments.  

### ISSUE THREAD

**Issue by barbarer** [RunestoneInteractive/RunestoneComponents#1187]
The assignments that you reach from the assignments page do not have problem numbers.  This makes it hard for students to communicate about them.

Add a question number on the page like we have on the end of chapter exercises.

**Comment by bnmnetp** [comment]
It looks kind of inconsistent to me. Many problems do have their number from the chapter.section.problem in the textbook.  All of them have the unique id, and I'm not sure what we should do to handle problems added through the web interface.

Nothing is less ambiguous than using the identifier which is there for all the problems.

**Comment by barbarer** [comment]
Right now all problems added through the web interface say assignment 1.
See
https://runestone.academy/runestone/assignments/doAssignment?assignment_id=56887

The divid can be quite long.

Dr. Barbara Ericson
Assistant Professor, School of Information
University of Michigan

**Comment by bnmnetp** [comment]
Fixed so that the assignment page numbers the activities 1-N but also keeps their other labels.
