### ISSUE TITLE
Parsons problems List<String> being interpreted as html

### ISSUE THREAD

**Issue by bhoffman0** [RunestoneInteractive/RunestoneComponents#1191]
In https://csawesome.runestone.academy/runestone/books/published/csawesome/MixedFreeResponse/RandomStringChooserParsonsA.html and probably elsewhere, List<String> words in the parsons problems are being rendered as List words. I guess <String> is being interpreted as html and not being printed. 

Should I change these to &lt;String&gt; ? I will try that. Not sure if this was always a problem, or a new thing.
-Beryl

**Comment by bnmnetp** [comment]
Hi Beryl,

We haven't changed anything about how we parse the blocks. 

I looked at the source for that one and I notice that it does not have a `:language:` option given to the parsons problem which means that it defaults to trying to parse it as a Python language.  I would try addling the language flag with the value of java to see if that fixes it.  Parsons problems internally use a language aware parser for the blocks so my guess.

**Comment by bnmnetp** [comment]
The other thing you may have to resort to for this is to use the &lt; and &gt; in the parsons problems.  

The library they used for parsons is called prettify.js but it has no information in it about where it came from and whether it is still maintained.  I think it is a bug in that library which we have used forever....

**Comment by bhoffman0** [comment]
Locally, :language: java didn't work but &lt; worked. Thanks!
