### ISSUE TITLE
Previous/next buttons render incorrectly if built for offline

### ISSUE THREAD

**Issue by bjones1** [RunestoneInteractive/RunestoneComponents#1238]
Since the recent layout fixes, it looks like books built for offline use (`"dynamic_pages": False, "use_services": "false"` in `pavement.py` don't render the previous/next buttons correctly. @ascholerChemeketa, are you available to look at this?

The previous and next buttons are on top of one another with confused hover text:
![image](https://user-images.githubusercontent.com/2125584/127842367-d1650aa6-4488-46b7-b2a8-116f35acb4b7.png)

The next button appears on the left and the hover text appears offscreen:
![image](https://user-images.githubusercontent.com/2125584/127842178-2ca217b8-7e0a-4ec5-acf4-717dbad6e557.png)

**Comment by ascholerChemeketa** [comment]
I believe there were some merge based regressions with recent PRs. Submitting a fix today.

**Comment by bnmnetp** [comment]
Oddly, I am not seeing that problem on a couple of the test books I tried.  But thanks for fixing up the regressions.

**Comment by bjones1** [comment]
@ascholerChemeketa, thanks!

@bnmnetp, here's my `pavement.py` for the Overview book, which is otherwise unmodified; I'm using the Runestone Components v5.9.0.

``` Python
import paver
from paver.easy import *
import paver.setuputils

paver.setuputils.install_distutils_tasks()
import os, sys
from socket import gethostname
import pkg_resources
from sphinxcontrib import paverutils


######## CHANGE THIS ##########
project_name = "overview"
###############################

master_url = "https://runestone.academy"
if master_url is None:
    if gethostname() in ["runestone.academy", "runestone-deploy", "rsbuilder"]:
        master_url = "https://runestone.academy"
    elif "RUNESTONE_HOST" in os.environ:
        master_url = "http://{}".format(os.environ["RUNESTONE_HOST"])
    else:
        master_url = "http://127.0.0.1:8000"

master_app = "runestone"
serving_dir = "./build/" + project_name
dest = "./published"

options(
    sphinx=Bunch(docroot=".",),
    build=Bunch(
        builddir="./build/" + project_name,
        sourcedir="_sources",
        outdir="./build/" + project_name,
        confdir=".",
        project_name=project_name,
        template_args={
            "course_id": project_name,
            "login_required": "false",
            "appname": master_app,
            "loglevel": 10,
            "course_url": master_url,
            "dynamic_pages": False,
            "use_services": "false",
            "basecourse": "overview",
            "python3": "true",
            "downloads_enabled": "true",
            "allow_pairs": "false",
            "enable_chatcodes": "false",
        },
    ),
)

version = pkg_resources.require("runestone")[0].version
options.build.template_args["runestone_version"] = version

from runestone import build  # build is called implicitly by the paver driver.
```

**Comment by ascholerChemeketa** [comment]
Actually, I am not seeing this either after pulling 5.9.0 and doing a rebuild.
Used that exact `pavement.py`

Can you show me what you are seeing as styles applied to the .relations-next li?
![2021-08-02 10_44_04-DevTools - file____F__Programming_RunestoneOverview_build_overview_index html](https://user-images.githubusercontent.com/7787413/127902818-289ab217-be44-419c-ad61-7168a7ac25a1.png)

**Comment by bjones1** [comment]
Oops, this was my mistake -- I forgot to `npm run build`.
