### ISSUE TITLE
Group Submit

### ISSUE THREAD

**Issue by bnmnetp** [RunestoneInteractive/RunestoneComponents#1245]
Feature requested by @barbarer 

* Create a component that can be added at the bottom of a page
* Allow the selection of usernames from the course
	* Use the select2 widget
	* Should there be a limit on group size to prevent someone submitting for the whole class??
* Submit Group button
	* Scan the page for components
	* Log a group submit start event where act contains group members divid is the page - sid will be the team submitter
	* Log the answer for each group member (circumvent normal check of sid in hsblog) We could include a group attribute on the hsblog request.  It is probably easier to iterate over the group members in javascript given the complexity of `hsblog` on the web2py server.  Should there be any other indication on the individual submissions that this is part of a group?
	* Log a group submit end

**Comment by barbarer** [comment]
Sounds good.
Yes, I think we could limit the number of people in the group to 4.
