### ISSUE TITLE
Quizlys show N/A instead of Correct on Chapter Activity subchapdetail

### ISSUE THREAD

**Issue by bhoffman0** [RunestoneInteractive/RunestoneComponents#1254]
In Mobile CSP in the Instructor's Page, Chapter Activity, when you drill down to a student and lesson like https://runestone.academy/runestone/dashboard/subchapdetail?chap=Unit2-Intro-to-Mobile-Apps&sub=I-Have-a-Dream-Tutorial&sid=BerylStudent, the quizlys show N/A under the Correct column instead of Yes or No. @bnmnetp I think this should be fixable since when you grade it in an assignment, it gives the correct points for quizlys. A lot of teachers are using this easier view instead of figuring out how to make assignments and grading them, so it would be great to fix this if it's an easy fix.
![image](https://user-images.githubusercontent.com/4571962/133938444-fcba6724-fb9b-4a11-9930-928082a687e1.png)
thanks,
Beryl

**Comment by bnmnetp** [comment]
@bhoffman0 -- Check and see.  Should be fixed.

**Comment by bhoffman0** [comment]
Wow thanks for working on it. I got Report a Bug and this error though:
    ---------------- Traceback --------------
    Traceback (most recent call last):
  File "/home/bmiller/Runestone/web2py/gluon/restricted.py", line 219, in restricted
    exec(ccode, environment)
  File "/home/bmiller/Runestone/web2py/applications/runestone/controllers/dashboard.py", line 1074, in <module>
  File "/home/bmiller/Runestone/web2py/gluon/globals.py", line 421, in <lambda>
    self._caller = lambda f: f()
  File "/home/bmiller/Runestone/web2py/gluon/tools.py", line 3869, in f
    return action(*a, **b)
  File "/home/bmiller/Runestone/web2py/applications/runestone/controllers/dashboard.py", line 1048, in subchapdetail
    active = set([r["name"] for r in res])
  File "/home/bmiller/Runestone/web2py/applications/runestone/controllers/dashboard.py", line 1048, in <listcomp>
    active = set([r["name"] for r in res])
TypeError: string indices must be integers

**Comment by bnmnetp** [comment]
Were you on csawesome or plain runestone.academy?

**Comment by bhoffman0** [comment]
https://runestone.academy/runestone/dashboard/subchapdetail?chap=Unit2-Intro-to-Mobile-Apps&sub=I-Have-a-Dream-Tutorial&sid=hoffmanb

**Comment by bnmnetp** [comment]
What class??  I will make myself instructor as it seemed to be working for me.

**Comment by bhoffman0** [comment]
mcsp-test

**Comment by bnmnetp** [comment]
oops - silly me...  Should not have reused that variable.

Works for me now on mcsp-test

**Comment by bhoffman0** [comment]
Yes works for me too!! Thank you so much! I'll let the teachers know. :-)

**Comment by bnmnetp** [comment]
Great, there is still a bit more that we should do for quizly and khanex at some point to make them fully compatible with the other question types.

For example I don't think we can grade quizly's as % correct they are all or nothing right now.  But that can be a project for another day.
