### ISSUE TITLE
Error rendering dynamic questions in assignment - fl-py4e

### ISSUE THREAD

**Issue by rafael-atias** [RunestoneInteractive/RunestoneComponents#1285]
**Please check the current issues** 
I haven't found a related issue

**What Course are you in**
fl-py4e

**What Page were you on**
https://runestone.academy/runestone/assignments/doAssignment?assignment_id=70847

**What is your username**
ratias

**Describe the bug**
I have experienced an error when I tried to do an [assignment](https://runestone.academy/runestone/assignments/doAssignment?assignment_id=70847)

The assignment has 3 dynamic questions. When the page is rendered, it shows

>Loading a dynamic question ...
>Selecting from: Function_String_MixedUpCode_2_v2, Function_String_MixedUpCode_2_v2_ac

> Loading a dynamic question ...
> Selecting from: Function_String_MixedUpCode_3, Function_String_MixedUpCode_3_ac

> Loading a dynamic question ...
> Selecting from: Function_String_MixedUpCode_4, Function_String_MixedUpCode_4_ac

**The problem is that those questions are never rendered**.

The **expected behavior**, I think, would be to show the `Loading a dynamic question...` messages and then render the dynamic questions

**Traceback**
No Traceback

**Javascript Errors**
My browser is Google Chrome 96.0.4664.110, 64 bits

```
selectone.js:103 POST https://runestone.academy/ns/assessment/get_question_source 422 (Unprocessable Entity)
selectone.js:453 Error rendering New Exercise Function_String_MixedUpCode_2_v2_sq
                         Details: TypeError: l.split is not a function
selectone.js:455 TypeError: l.split is not a function
    at a.initialize (selectone.js:227)
    at async HTMLDocument.<anonymous> (selectone.js:449)

selectone.js:97 getting question source
selectone.js:103 POST https://runestone.academy/ns/assessment/get_question_source 422 (Unprocessable Entity)
selectone.js:453 Error rendering New Exercise Function_String_MixedUpCode_3_sq
                         Details: TypeError: l.split is not a function
selectone.js:455 TypeError: l.split is not a function
    at a.initialize (selectone.js:227)
    at async HTMLDocument.<anonymous> (selectone.js:449)

selectone.js:97 getting question source
selectone.js:103 POST https://runestone.academy/ns/assessment/get_question_source 422 (Unprocessable Entity)
selectone.js:453 Error rendering New Exercise Function_String_MixedUpCode_4_sq
                         Details: TypeError: l.split is not a function
selectone.js:455 TypeError: l.split is not a function
    at a.initialize (selectone.js:227)
    at async HTMLDocument.<anonymous> (selectone.js:449)
```

**Comment by bnmnetp** [comment]
fixed
