### ISSUE TITLE
Two different versions of overview.rst

### ISSUE THREAD

**Issue by ericsonga** [RunestoneInteractive/RunestoneComponents#13]
There is an overview.rst in RunestoneComponets but it doesn't always match the one in RunestoneInteractive/overview  They should be the same.

**Comment by bnmnetp** [comment]
I agree, and I think it makes sense to make the master version the one in the project_template.  We can then deploy the online overview from one simple project.

**Comment by bnmnetp** [comment]
This is nearly resolved with the work @aerenchyma did last week.

1. The template project will be short with a couple of examples, and a link to the full developer documentation on runestoneinteractive.org

2.  The overview will be in the overview repository -- auto built on push -- and will be for introducing newcomers to the capabilities of Runestone.  Not for documentation.

3.  The detailed documentation for each directive which also contains the source code will be on the runestoneinteractive site.
