### ISSUE TITLE
Toggle code pulls up problems with the same id from the wrong book

### ISSUE THREAD

**Issue by bhoffman0** [RunestoneInteractive/RunestoneComponents#1337]
We need to have the toggle problems to look for the div id of the problem in the **same** book first. The toggle problems in CSAwesome are pulling up the wrong problems for example ch5ex2muc in Barb's Python book instead of the same name ch5ex2muc in the CSAwesome book.  For example, see the second question here https://runestone.academy/ns/books/published/csawesome/Unit3-If-Statements/topic-3-9-practice-mixed-code-toggle.html which shows a  Python Turtle parsons problem when you toggle and labels it ch5ex2muc, instead of the Java one with the same name in the CSAwesome book.

**Comment by bnmnetp** [comment]
fixed
