### ISSUE TITLE
Khanex Component does not save result in Runestone db

### ISSUE THREAD

**Issue by bhoffman0** [RunestoneInteractive/RunestoneComponents#1352]
The Khanex component (@ram8647, @bnmnetp ) does not seem to save its result into Runestone. It does show as correct and increases the activity count while on the page, but when you come back to the page or try to grade it, it has not saved the result.  Here's the error message when it is run on https://runestone.academy/ns/books/published/mobilecsp/Unit2-Intro-to-Mobile-Apps/Binary-Numbers.html. 
<img width="925" alt="error1" src="https://user-images.githubusercontent.com/4571962/180469800-4a028032-1716-4904-96c1-92bba1df6002.png">
When trying to grade it, I get the following error (even after a hard refresh): 
<img width="668" alt="error2" src="https://user-images.githubusercontent.com/4571962/180469910-22f79836-e69d-49bd-9eb4-e5c1ce3b8416.png">
We only use the Khanex component 4 times in Mobile CSP, so it's not a big priority, but it would be nice to fix.

**Comment by bnmnetp** [comment]
@bhoffman0 

This is fixed and will be deployed in the next update to runestone components. 

The new server is a lot more picky about making sure that what is passed to us is the appropriate type and length etc.  That is a good thing for security and correctness. And the exact problem was identified just a couple of lines below where you cut off the javascript console.
