### ISSUE TITLE
Quizly questions in MobileCSP loading random ones in Assignments page (but ok in context)

### ISSUE THREAD

**Issue by bhoffman0** [RunestoneInteractive/RunestoneComponents#1360]
@bnmnetp @ram8647 , the quizly component is doing weird things on the Assignment page of MobileCSP. It's loading random ones in instead of the one with the correct quizname. But it works fine on the e-book pages and when you click on context. It's also giving a "Error:  Missing the component factory!  Clear you browser cache." when you click to view Quizly problems in the Instructor's page/Assignments tab, but clearing the cache doesn't seem to help.  Here's what happens when I click on the quiz_pause_the_player. It shows a random one instead and gives the console error "blockly.html:1 Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause()." It loads and works fine in the ebook page though.
<img width="890" alt="image" src="https://user-images.githubusercontent.com/4571962/187804910-36c8b9ad-f08b-42fd-8474-4e174df51dac.png">

**Comment by bnmnetp** [comment]
I fixed this yesterday.

**Comment by bhoffman0** [comment]
Thanks!
