### ISSUE TITLE
What to log for timed assessments?

### ISSUE THREAD

**Issue by riknos314** [RunestoneInteractive/RunestoneComponents#14]
In the RSE 0001 version of assessments, the answers to questions are logged to the server/localstorage on a per-question basis.  What should be logged for the timed assessment as a whole?  Just things like the number correct, number incorrect, and number skipped, as well as the time taken?

**Comment by ericsonga** [comment]
I also logged the time taken, the number correct, the number incorrect, and the number skipped.

**Comment by riknos314** [comment]
Logging of the time taken, number correct, number incorrect, and number skipped has been implemented.
