### ISSUE TITLE
showEval would make a pretty cool directive

### ISSUE THREAD

**Issue by bnmnetp** [RunestoneInteractive/RunestoneComponents#147]
http://inventwithpython.com/showeval/

See also:  https://github.com/asweigart/showeval

**Comment by bnmnetp** [comment]
Step one will be to design an easy to write syntax for authors.  You should look at the example on github linked above to first understand how the javascript version of this works.  It may be that something  very close to his syntax will work best.

I think we should call the directive `showeval` and it should allow the author to choose between replace mode and trace mode.  Initially we could have just a next step and reset button similar to what he has in the example, but I think for consistency with CodeLens it would be nice to have a slider as well.

**Comment by conzty01** [comment]
Are the instructors supposed to fill in the steps themselves or is the showeval directive supposed to be similar to CodeLens in that it will take any code and show the evaluation? 

The former option would be more tedious for an instructor particularly if they wanted many of the examples to be showevals. The later might be harder to implement but would make it easier for instructors to use.

**Comment by bnmnetp** [comment]
I think, at least in version 1, we can expect the instructors to fill in the steps themselves.  I'm not aware of any python tool that would break down a statement or expression into the sequence of steps required for evaluation.   

Leaving it in the instructors hands also allows for this directive to be used for any programming language.

**Comment by gardhi01** [comment]
Is this going to be its own directive, or is this something that you'd want to be tacked onto the codelens directive?

**Comment by bnmnetp** [comment]
No, this would be a new standalone directive!
