### ISSUE TITLE
load order of assess.js and tabbedstuff.js causes click events to be lost

### ISSUE THREAD

**Issue by bnmnetp** [RunestoneInteractive/RunestoneComponents#15]
If tabbedStuff is loaded after assess.js then the checkMe buttons on the assessments do not work.  This is also true of reveal.js

**Comment by riknos314** [comment]
We have tracked this down to tabbedstuff copying the innerHTML and not the nodes, which we think may had interfered with the capturing/bubbling process on the button.  We have a solution for this in the javascript implementation of tabbedstuff that makes this work correctly.
