### ISSUE TITLE
Need to be consistent when saving data on local storage

### ISSUE THREAD

**Issue by ericsonga** [RunestoneInteractive/RunestoneComponents#151]
Some of the directives save by user + divid as the key to local storage and some only use divid as the key.  Since it is quite possible in schools for more than one student to use the same computer we should use user + divid as the key always.

**Comment by bnmnetp** [comment]
@flysaiah I think a lot of the work that you have done for each directive (checkLocalStorage, repopulateFromStorage, shouldUseServer) could be refactored, and much of it could be pushed into RunestoneBase to keep from duplicating code, and to make sure we are being very consistent.  It will also make it easier for new directive authors to add a new directive and do the right thing.

Lets add this to your todo list

**Comment by flysaiah** [comment]
I agree completely; this was my original goal when writing these functions, I just never got to it before. I'll get it done.

**Comment by ericsonga** [comment]
I agree that this would be great to have as a centralized function.
