### ISSUE TITLE
we need to add an optional instructions field on activecode (this is needed for timed exams)

### ISSUE THREAD

**Issue by ericsonga** [RunestoneInteractive/RunestoneComponents#154]
There should be an optional instructions field added to the active code directive that then gets displayed above the activecode as text (html?).  This is really needed when you use an activecode inside a timed exam, because otherwise you may have a blank activecode with no instructions as to what you are supposed to do.

**Comment by bnmnetp** [comment]
Should be able to use the Question directive to solve this now.
