### ISSUE TITLE
Can we reduce thenumber of js files needed by Parsons?

### ISSUE THREAD

**Issue by bnmnetp** [RunestoneInteractive/RunestoneComponents#157]
@jochenrick 

Now that you have finished the parsons rewrite I wonder if we can eliminate any of the following javascript files?  It would be mind-blowingly awesome if we didn't need a special version of jquery just for parsons anymore.  It might be the last impediment to us making one master combined js file for all of runestone which would make our load times oh-so-much better.

```
 app.add_stylesheet('parsons.css')
    app.add_stylesheet('lib/prettify.css')

    app.add_javascript('lib/jquery.min.js')
    app.add_javascript('lib/jquery-ui.min.js')
    app.add_javascript('lib/jquery.ui.touch-punch.min.js')
    app.add_javascript('lib/prettify.js')
    app.add_javascript('lib/underscore-min.js')
    app.add_javascript('lib/lis.js')
    app.add_javascript('parsons_setup.js')
    app.add_javascript('parsons.js')
    app.add_javascript('parsons-noconflict.js')
    app.add_javascript('timedparsons.js')
```

**Comment by jochenrick** [comment]
We can definitely do some cleanup there. My guess is the jquery stuff can go as I'm using pretty standard jquery stuff. I just need the draggable package. I'll look into it. We definitely need prettify. I might just integrate lis.js into parsons.js. Getting rid of parsons_setup.js is on my list and will be done soon. I'm not sure what parsons-noconflict.js is and why we need it. I'm not sure why timedparsons.js has to be a separate file. If it doesn't have to be one, then we can integrate it into parsons.js. So, I hear you and agree.

**Comment by jochenrick** [comment]
Let's leave timedparsons as a separate file to stay with the convention. I've looked into it a bit and I do need jquery and jquery-ui but no special versions of those, so I can probably remove those from the parsons directive, assuming that normal jquery and jquery-ui are included.

**Comment by jochenrick** [comment]
OK. I've looked into it and I can remove jquery.min, jquery-u.min, jquery.ui.touch-punch.min, underscore-min, and parsons-noconflict.js. That said, I find it strange that we are using jquery-ui-1.10.3.custom.min instead of the latest version.

**Comment by jochenrick** [comment]
So, actually, I'll take that back. It turns out that normal jquery-ui does not support touch events, so jquery.ui.touch-punch.min is necessary. It is amazing that jQuery does not properly support touch, so you need a hack like touch-punch to fix it.

**Comment by jochenrick** [comment]
HA! I was able to use Hammer.js instead of jquery-ui. That framework is pretty awesome: lightweight, support both touch and mouse. So, I am able to get rid of things.

**Comment by jochenrick** [comment]
We might want to include [Hammer.js](http://hammerjs.github.io/) as a Runestone general include. It is compact, self contained, and does a nice job of supporting touch. I could see it being useful for other directives.
