### ISSUE TITLE
classes for all top level component containers

### ISSUE THREAD

**Issue by bnmnetp** [RunestoneInteractive/RunestoneComponents#161]
@jochenrick mentioned this last week, and I think its a great idea and should be implemented across all of the components.  That is that each top level container should have a descriptive class name on the top level component so that we can write CSS rules for each component and have something to match against.  In addition I wonder if all of the top level containers should also belong to the class rscomponent so that we could write some rules that match against all of the components.  I think that this is the first step toward giving better control over the width of various containers too which is an ugly problem that has been hanging around for a couple of years.

For example the top level div for an activecode would look like `<div class="rscomponent activecode">`

Comments?

**Comment by jochenrick** [comment]
I don't see any disadvantages.

**Comment by bnmnetp** [comment]
I did this.  All components have a class of "runestone"
