### ISSUE TITLE
Add a new clickable area directive that would allow students to click on a region of an image

### ISSUE THREAD

**Issue by bnmnetp** [RunestoneInteractive/RunestoneComponents#163]
this is similar to the current clickable area directive but would work on an image instead of elements.

**Comment by flysaiah** [comment]
I think I may have stumbled upon a good way to do this, but it depends on the use cases for this, and how we expect people to define "regions" of an image. Will people upload an image and specify that they want it cut into thirds/fourths/etc? Or will they specify the coordinates in pixels for the various rectangles inside the image that should be clickable?

**Comment by flysaiah** [comment]
An example that would work if we want people to just provide image maps for the sections of their image would be:
```html
<div data-component="clickableimage">
    <span data-question>Click on the correct sections of this image</span>
    <span data-feedback>Sorry, you are incorrect.</span>
    <img data-source src="image.jpg"/>
    <map data-map>
        <area data-correct shape="rect" coords="0,0,82,126">
        <area data-incorrect shape="circle" coords="90,58,3">
        <area data-incorrect shape="circle" coords="124,58,8">
    </map>
</div>
```

The restructuredText version would look something like:

```
.. clickableimage:: clickimage1
    :feedback: Sorry, you are incorrect.
    :image: image.jpg
    :correct: ("rect", "0,0,82,126")
    :incorrect: ("circle", "90,58,3")
    :incorrect: ("circle", "124,58,8")

    Click on the correct sections of this image.

```

This would function exactly like the current clickablearea, and I feel that this would be pretty straightforward to implement, but I'm not sure if this is the vision for how authors should specify the regions.

**Comment by bnmnetp** [comment]
I'm pretty sure this is exactly what @ericsonga wants.

**Comment by ericsonga** [comment]
It would be nice to have more than one question possible with each question having a list of correct and incorrect clickable areas.  I like the idea of any sided polygon to define the clickable area.

**Comment by bnmnetp** [comment]
@ericsonga can you give an example of what you mean by more than one question?  I get that there could be several correct areas to click on, and that the student would need to click on all of them to get full credit.  But I'm not sure I get what you mean by "more than one question"

**Comment by flysaiah** [comment]
After some research, I have found that this will be much easier to implement if we use SVGs instead of image maps. An updated template using SVGs looks like this:

```html
<div data-component="clickableimage">
    <span data-question>Click on the correct sections of this image</span>
    <span data-feedback>Sorry, you are incorrect.</span>
    <img data-source src="image.jpg"/>
    <svg data-clickareas>
        <rect data-correct x="50" y="20" width="150" height="200">
        <circle data-incorrect cx="10" cy="200" r="50">
        <polygon data-incorrect points="200,10 250,190 160,210">
    </svg>
</div>
```

reStructuredText:

```
.. clickableimage:: clickimage1
    :feedback: Sorry, you are incorrect.
    :image: image.jpg
    :correct: ("rect", "50,20,150,200")
    :incorrect: ("circle", "10,200,50")
    :incorrect: ("polygon", "200,10|250,190|160,210")

    Click on the correct sections of this image.
```

I will probably have to find a cleaner way of specifying the polygon coordinates, but I haven't even started Sphinx stuff yet, so that can wait for now. @ericsonga please let me know if you have any concerns with this--using image maps is still possible; SVGs just make some of the CSS styling much easier.

**Comment by bnmnetp** [comment]
@flysaiah are you embedding a standard image in an SVG object?  We wouldn't want to force people to only use SVG drawings.

**Comment by flysaiah** [comment]
@bnmnetp I'm using the image as a background, then they would specify whatever regions they want to be clickable as SVG drawings; the SVG is an overlay on the image. The actual image would not have to be a SVG drawing.

**Comment by bnmnetp** [comment]
The flexibility of SVGs are nice, well supported, and I doubt anyone will even know that is going on behind the scenes.

**Comment by ericsonga** [comment]
Say you have an image of several parts of a computer and you have several questions asking them to click on different parts - 1) click on the CPU 2) Click on the hard drive 3) click on the fan 
You would want a different correct area for each question, but all the questions are about the same image.

**Comment by flysaiah** [comment]
@bnmnetp Okay, so I will continue using SVGs like I have suggested, but I will also provide support for simple imagemaps, like in the original template--that way no one is forced to use only SVGs.

@ericsonga I have constructed a new template that will work for multiple questions per image.

```html
<div data-component="clickableimage">
    <img data-source src="image.jpg"/>
    <svg data-clickareas>
        <rect id="1" x="50" y="20" width="150" height="200">
        <circle id="2" cx="10" cy="200" r="50">
        <polygon id="3" points="200,10 250,190 160,210">
    </svg>
    <ul data-questions>
        <li data-correct="1,3" data-incorrect="2">
            <span data-question>Click on the rectangular and polygon sections</span>
            <span data-feedback>Sorry, you are incorrect.</span>
        </li>
        <li data-correct="2" data-incorrect="1,3">
            <span data-question>Click on the circular sections</span>
            <span data-feedback>Sorry, you are incorrect.</span>
        </li>
    </ul>
</div>
```

Because the SVG (or imagemap) is only defined in one place, the clickable areas can be reused. It can also easily be used with one question (just have only one list element). Please let me know if this is what you're looking for.
