### ISSUE TITLE
The timed Parsons and active code are not working

### ISSUE THREAD

**Issue by ericsonga** [RunestoneInteractive/RunestoneComponents#168]
I had updated to the most recent version of Runestone Components and now the timed parsons problems and timed active code are not working.

**Comment by bnmnetp** [comment]
Barb, the only thing new in the last two weeks is that I accepted some bug fixes from @flysaiah.  I can't see that there were any changes to Parsons Problems in that PR.  Could you be more specific about what isn't working?

We have no control over figures.

**Comment by flysaiah** [comment]
Barb mentioned to me that the timed activecode questions aren't rendering at all and that the parsons problems are rendering incorrectly. I'm looking into it, but it would be nice to have some screenshots because I'm currently unable to reproduce the issue.

**Comment by ericsonga** [comment]
It turned out to be some bad indention, but I am still having problems with the timed Parson and timed active code.  They are rendering okay, but the active code run isn't working correctly and the when I finish a timed Parsons it isn't hiding the Parsons like it should.
