### ISSUE TITLE
We Must Revive the Selenium testing framework

### ISSUE THREAD

**Issue by bnmnetp** [RunestoneInteractive/RunestoneComponents#170]
With the number of developers growing, and the increasing variety of components we really need some form of testing in place.  It's frustrating to see one thing improve while unintentionally breaking something else.  A comprehensive set of tests that at least minimally tests each Runestone Component would allow everyone to run tests before making a PR and would allow our Jenkins server to automatically run the same tests when a PR is made.

A couple years ago Isaac wrote some simple tests using Selenium.  This works well for our situation as it allows us to simulate pushing buttons and grab results from HTML components.  The tests currently live in the test folder of RunestoneServer.  These tests became largely useless in the great rewrite last summer, but they should be moved over and revived. 

I propose that each component has a test rst file that creates each component with a variety of options.  Each component should also then maintain its own test script that exercises each of the various buttons and widgets associated with the component.  

When new features are added new tests must be added in order for the PR to be accepted.

**Comment by bnmnetp** [comment]
@RunestoneInteractive/contributors ^^

**Comment by ericsonga** [comment]
Sounds like a great idea!
