### ISSUE TITLE
Backward compatibility 

### ISSUE THREAD

**Issue by bnmnetp** [RunestoneInteractive/RunestoneComponents#172]
@jochenrick,

I had the following problem that I encountered after accepting both PR's today.

I went back to a parsons problem that I had solved previously with a prior version of the parson's code.  Using the new version, that parson's problem appeared as a tiny empty gray rectangle.

When I cleared localStorage and reloaded the page all was well.

This won't hurt Barb's tests, but it will annoy thousands of current users who will not see past parson's problems.

**Comment by jochenrick** [comment]
Hi Brad,

I'll investigate putting something in for backwards compatibility.
Shouldn't be too hard.

Jeff

**Comment by bnmnetp** [comment]
Also, do all blocks have to be explicitly delimited with ==== now?

There is an example in the default project that looks like this

```
.. parsonsprob:: question1_100_4

   Construct a block of code that correctly implements the accumulator pattern.
   -----
   x = 0
   for i in range(10)
      x = x + 1
```

But when I build I get no blocks to drag...

**Comment by bnmnetp** [comment]
@jochenrick 
The problem is on line 756 of parsons.js
The value in localStorage is "1_0-0_0-2_1"  which is not valid JSON.

This turns out to be really bad as it stops all kinds of downstream things from happening.  Activecodes don't get rendered and other components end up blank.

**Comment by jochenrick** [comment]
Right. I've fixed that but I never checked it in as other things took
priority. Will do soon.
