### ISSUE TITLE
Make Sure components work when useRunestoneServices is false

### ISSUE THREAD

**Issue by bnmnetp** [RunestoneInteractive/RunestoneComponents#181]
@flysaiah, @jochenrick, @ericsonga 

I'm seeing a few problems with parsons, and fitb where building with useRunestoneServices off causes things to fail.

You can reproduce the problem by making a new folder and doing runestone init in that folder.  When it asks about using runestone services make sure that is false, and then build the default project.  type runestone serve and then access the built site.  You will see failures.

**Comment by jochenrick** [comment]
I've put it on my ToDo list. Should be simple.

**Comment by bnmnetp** [comment]
I've experienced a number of fail situations today, all of which can be traced back to parsing errors in data coming out of localStorage.

I think we need to surround the calls to JSON.parse with try catch and deal with it.

If we don't, the page looks broken.

**Comment by flysaiah** [comment]
I have this done for all components except for parsons in PR #196. @jochenrick I didn't do parsons just in case you're already working on it, but let me know if you'd like me to put a fix for parsons in this PR too.

**Comment by jochenrick** [comment]
I'll merge it in on Monday.

Cheers,

Jeff

**Comment by jochenrick** [comment]
I'm not sure what is going on but I've tried to do "runestone serve" in the
newly created directory and I get an error:

Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/runestone",
line 9, in <module>

    load_entry_point('runestone==2.4.0', 'console_scripts', 'runestone')()

  File
"/Users/jrick/Desktop/bd/barb/RunestoneComponents/runestone/__main__.py",
line 175, in main

    cli()

  File
"/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/click/core.py",
line 716, in __call__

    return self.main(*args, **kwargs)

  File
"/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/click/core.py",
line 696, in main

    rv = self.invoke(ctx)

  File
"/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/click/core.py",
line 1086, in invoke

    rv.append(sub_ctx.command.invoke(sub_ctx))

  File
"/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/click/core.py",
line 889, in invoke

    return ctx.invoke(self.callback, **ctx.params)

  File
"/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/click/core.py",
line 534, in invoke

    return callback(*args, **kwargs)

  File
"/Users/jrick/Desktop/bd/barb/RunestoneComponents/runestone/__main__.py",
line 93, in serve

    httpd = SocketServer.TCPServer((listen, port), Handler)

  File
"/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py",
line 420, in __init__

    self.server_bind()

  File
"/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py",
line 434, in server_bind

    self.socket.bind(self.server_address)

  File
"/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py",
line 228, in meth

    return getattr(self._sock,name)(*args)

socket.error: [Errno 48] Address already in use

When I manually move the directory over to the static directory and look at
it, I don't get any errors. What are these "useRunestoneServices is false"
errors that you are expecting to see. I did fix the small bug on the
backwards compatibility and localStorage. Is that perhaps what you are
reporting and it has nothing to do with useRunestoneServices?

Cheers,

Jeff

**Comment by bnmnetp** [comment]
The address already in use means:

1.  You are already running the server in another window
2.  You killed your server at an unlucky time and now you have to wait (about a minute) for the operating system to clean up that port.

**Comment by bnmnetp** [comment]
I suspect the problems I reported with the useRunestoneServices are the same or related to the backward compatibility bug.  However, you should try to respect the eBookConfig.useRunestoneServices flag and NOT try to make ajax calls when that is false.
