### ISSUE TITLE
Need to create an exercise directive or allow for question text to be added to an activecode

### ISSUE THREAD

**Issue by bnmnetp** [RunestoneInteractive/RunestoneComponents#206]
This problem revealed itself in testing the new assignment builder.  The problem is that you can search for ex_2_5 and you will get the `.. actex` directive.  But when when we go to build a file of questions for this assignment, we have no way to know what the actual question is, because the question has always been outside of the directive itself.

**Comment by bnmnetp** [comment]
@RunestoneInteractive/contributors I would like to solicit some opinions / ideas / dialog on how we should solve this one.

We cannot make it mandatory to include some question text as part of the directive as active codes are used for exercises and examples alike.

We could modify the `..actex` directive to include some description. as this is already used for the exercises and is implemented as a subclass of the ActiveCode class.

I think doing it as an option is quite problematic as many programming exercise descriptions are fairly long, and may contain images or multi-line code snippets.

A `.. exercise::` directive would give us a lot of control over the formatting of the exercise.

**Comment by bnmnetp** [comment]
I am leaning strongly to the following:

```
.. question:: draw_turtle_flower

   Using turtle graphics, draw an image the looks like the following:
   
   .. image:: path/to/flower.png

   .. actex:: ex_5_4
      :language: python

```

This will preserve the activecode id for all existing questions.

But when the page containing the assignment is generated we'll have both the question text and the activecode component we need together.

**Comment by presnick** [comment]
This looks but three additional things will have to be done:

1. When processing the .. question directive, may need to store stuff in the database about subcomponents, like the actex ex_5_4.
2. When responding to assignments/problem ajax call, will need to provide that info from the database, like we currently do for activecodes (included files, prefix code, etc.)
3. The javascript that handles the response to assignments/problem will have to handle the additional information, and not just assume that it's getting just an activecode back.

**Comment by presnick** [comment]
Maybe if we could intercept the HTML that sphinx produces for the question directive, it would be great to capture it and store it in the DB.

**Comment by aerenchyma** [comment]
I also like that idea with preservation of the activecode id ^, and I agree that it would be good to associate all of the subcomponent ids (during build, presumably?). It seems like there might be a way of doing that during the build that doesn't require intercepting the sphinx-produced HTML, but perhaps that's best.

**Comment by bnmnetp** [comment]
I think this question directive is problematic for grading in a few ways.

It seems that intercepting the html for a node and all of its children is definitely not obvious.  Because the visit_xxx_node and depart_xxx_node functions all append their templated html to the body.    I guess I could do a hack where I append "start_divid" when I visit, and then on departure I could grab everything from start to the end. and then remove the "start_divid" piece from self.body.  Feels like a nasty hack, but I think it would work.  I also posted a question to the sphinx developers list, but I don't expect I'll hear anything back.

The other problem is that for many of the exercises they include the tabbed environment above the actex directive so when grading you would have to wade through all of the tabs etc. just to get to the code.

Which brings me back to including the question along with the code in the body of the activecode/actex directive.

```
.. activecode:: example1
   :language: python

   Write a program to reproduce this cool picture

   .. image:: turtlefun.jpg
   ++++
   def myfunc():
       # your code here

   ====
   import unittest blah blah

```

This would leave us with three potential sections of the content.  with different delimiters.  I haven't even tried this yet, but I think it would work.  

Thoughts??

**Comment by bnmnetp** [comment]
Well, my hack does work.  I can extract the html for an entire `.. question::`

As I think about a needed mechanism to be able to view / grade any type of question this does seem like the easiest approach.  Even though storing html in the database makes me queasy.

I am confident that the second approach would work as well, but this does not really solve the real problem.  Which is: for other question types we have never had the need to dynamically build generate them.  Sphinx is not designed for the purpose of **Give me a string of rst and I will generate the html for that**  It is designed around the idea that you have a set of files in a particular directory structure.  So recreating a multiple choice question dynamically is actually an ugly problem.  One would have to have some temporary directory where you could write a small file and run a runestone build then display the page generated. 

So, using the question directive to save the html to the database might be the best option. But would we want to do this for all directives?  Would we want to change our source for the books so that only components surrounded by question directives are candidates for inclusion in an assignment? (as a summative activity)  I actually like that proposal.  Right now, we get all kinds of activecodes that you would never grade.

OK, I'm going to work on another project for the rest of the day and let this soak, but I would really appreciate feedback from @RunestoneInteractive/contributors before I finalize this.

**Comment by presnick** [comment]
I'm glad that saving HTML to the DB turns out to be an option. I do think that it is, in some ways, natural, given that we've now said in principle that the HTML output after processing a directive really *is* the specification of an interactive runestone element, and the .rst is just one possible way to generate such HTML.

As to whether only question directives can be included in an assignment, I guess I'm OK with only questions being manually *gradable*. But I certainly want to be able to have an assignment page that tells students what they have to read and what outside links they should follow. Maybe it's OK to require that everything be wrapped in a question directive, since we can embed arbitrary .rst, including other directives, inside .. question.

I know we have said that each question directive should only contain one activecode in it. Could we generalize that to say that each .question directive should only contain one gradable directive inside it. That could be a multiple choice, an active code, or a usage assignment.

**Comment by bnmnetp** [comment]
I think that a usageAssignment is at the same level as a question.  But serves an important function for formative parts of the assignment. There will be work for you to do on the implementation of the usageAssignment so that it fits into the new assignment creation schema.

I would be happy to have the restriction that each question directive should only contain one 'gradable' directive inside it.

**Comment by bnmnetp** [comment]
This is all done now in the latest release of the components (2.6.4), and in the dashboard branch on the server.
