### ISSUE TITLE
Issues viewing Actual and Expected Values for testing

### ISSUE THREAD

**Issue by laumurph** [RunestoneInteractive/RunestoneComponents#218]
In some cases when writing tests, the actual and expected values are longer than the space allotted, and the condensed versions shown do not provide enough information for students about what they are being tested on. Would it be possible to add either the option to click on the actual/expected value or to hover over it so that the full value is revealed?

**Comment by bnmnetp** [comment]
How long are these actual and expected values?  
Could you provide an example?

Should we make the cells of the table a fixed width and have them wrap to multiple lines when needed?

@hangde01 @millro04 Any thoughts?  When we decided to just use the elipses to keep the actual and expected values to a reasonable length I thought that would give students enough to go on.

**Comment by laumurph** [comment]
The actual and expected values are longer than 15 characters, in two of the exercises that we're doing, the expected values are lists, one has 47 characters split up into 6 elements, and another has 2 elements, but one of the elements is another list.

![screen shot 2016-08-09 at 5 19 12 pm](https://cloud.githubusercontent.com/assets/16598894/17534171/e499ad92-5e55-11e6-9a69-c521e9967c41.png)
![screen shot 2016-08-09 at 5 20 22 pm](https://cloud.githubusercontent.com/assets/16598894/17534172/e49c21ee-5e55-11e6-9080-e4a3c26512e2.png)

Having a fixed width and wrapping the lines would work well I think. My guess is that this is not going to be an issue too often.

**Comment by aerenchyma** [comment]
Talked with @laumurph et al about this today. I agree that this is an issue and we think it will actually come up fairly often. Do you think a hover for the full value is too much? I would to be able to see the entire actual and expected values if desired, especially in cases where the goal is to create e.g. a semi-substantial (say, >100 chars) dictionary or list.

**Comment by bnmnetp** [comment]
I hear that, but I'm not convinced that a hover is going to solve the problem.  First, you will only be able to hover one thing or the other.  You can't see them both at the same time.  Which I think will make it really hard. 

Second, hovers are meant for small short messages.  A big long hover 100+ character hover is going to be hard.

What about a simple alert dialog?  I could fully display both things one on top of the other?
If the length is > our threshold then we show the truncated messages like now, but make them clickable so that the alert will show both of them.

**Comment by aerenchyma** [comment]
@bnmnetp Yeah, that does make sense, definitely. I hadn't considered that properly.

An alert dialog I like a lot: Maybe you don't need a whole thing, if it was easy and it passes, but if it's wrong and complicated, you should see both of them in the alert.

**Comment by bnmnetp** [comment]
@millro04 I think I like the alert idea better than wrapping the columns.  With the columns as narrow as they are 100+ characters would take 10 lines or more.

**Comment by hangde01** [comment]
I wrote a quick solution for this using alerts, but due to spotty internet won't be able to upload until Saturday afternoon/evening.

**Comment by bnmnetp** [comment]
Fixed in 2.6.8
