### ISSUE TITLE
Problem with username

### ISSUE THREAD

**Issue by bnmnetp** [RunestoneInteractive/RunestoneComponents#220]
Error reported in course None on page None
My Username: g.molnes
My Email: g.molnes@gmail.com

Hello. I tried to start an account with my gmail account. But I'm not allowed to have the dot in my g.molnes as a username. Also I'm not able to change the username either. I guess I could start the course with a different email, but since there are many people with a dot in their account I thought it relevant to report anyways.

**Comment by bnmnetp** [comment]
@presnick We disabled the . because it was causing problems with the grading interface.  The jQuery selector was interpreting a dot in the username to be a css class.  I also have some memory that this was fixed in the grading interface as well.  Do you recall?

**Comment by presnick** [comment]
Sorry, I don't recall.
