### ISSUE TITLE
Please put Error window above TestGui output, or remove TestGui output if there's an error

### ISSUE THREAD

**Issue by presnick** [RunestoneInteractive/RunestoneComponents#223]
I just went through a very confusign debugging session. It turns out I had a typo in my code that was generating an error. However, the error window was below my screen and I didn't scroll down to see it. The test case output did not update, because the code didn't complete running, so I was getting incorrect feedback from the test cases.

I think the best thing would be to hide the test cases output if the program doesn't complete running. The old test case output may not match the code that is currently being run.

Second best would be to just put the error window above the test case output.

**Comment by bnmnetp** [comment]
The usual behavior is to remove/erase old output before starting a new run.  Unit testing should be consistent with that behavior.

**Comment by presnick** [comment]
Agree. It looks like console window is getting cleared at the start of each
run. So, clearning and hiding the unit testing div at the start of each run
would be a good idea, too.

**Comment by bnmnetp** [comment]
Fixed in 2.6.8
