### ISSUE TITLE
Problem running activecode in timed exams

### ISSUE THREAD

**Issue by flysaiah** [RunestoneInteractive/RunestoneComponents#228]
When an activecode directive is on screen when the user clicks "Finish Exam" it runs fine. However, if one or more is off screen when the user finishes the exam, it does not run correctly because no output is shown. I've been looking into this for about a week now and I think I've traced it to something not happening right in the configuration of Skulpt (assuming that's what "Sk" is), but I haven't found any solution yet. I'm just writing this issue in case someone who is a little more familiar with activecode might have any insight.

**Comment by bnmnetp** [comment]
That is certainly an edge case I never thought of.  Running an active code when it was hidden or not visible.  

Can you be more specific about what the error is?

How output is handled by skulpt is configurable, usually we have a function that updates some element like a ``pre`` tag.  But you could configure the output to go to console.log or an alert, or even just store it in a variable and do nothing.

**Comment by flysaiah** [comment]
There is no error in the console; the `pre` element that is supposed to contain the output is invisible and does not contain any output. It appears that there is a function called `outputfun(text)` which is supposed to make the output visible (as well as other things) that should normally be called when the activecode is run, but it is not doing that when activecode is off the screen. I'm pretty sure this function **should** be getting called as a result of this config step:
`
        Sk.configure({output : this.outputfun.bind(this),
              read   : this.builtinRead,
              python3: this.python3,
              imageProxy : 'http://image.runestone.academy:8080/320x'
        });
`
but unfortunately this is as far as I've gotten with debugging so far, as I'm not really sure how this configuration works.

**Comment by bnmnetp** [comment]
@flysaiah If the entire activecode component is offscreen, then I'm not sure where/how this one little pre tag should appear.   Do you have a reference to the ActiveCode object?  If so then you should be able to at least get the $(myactivecode.output).text()  to get its text.  Otherwise we could save the text in a different non-html element inside the ActiveCode object.

**Comment by flysaiah** [comment]
I do have a reference to the activecode object. I will look into this.

**Comment by bnmnetp** [comment]
@flysaiah I also discovered today that the print function is asynchronous.  As I was working on a function for the unittest module I was having weird results returned.  I ended up putting in a little delay before I accessed the pre tag to get its contents and that solved the problem.
