### ISSUE TITLE
prompt string not displaying in the modal window for input or raw_input

### ISSUE THREAD

**Issue by presnick** [RunestoneInteractive/RunestoneComponents#241]
See screenshot. "hello" should show up in the modal window (used to before latest changes, I think).

Thanks to Everlast Chigoba for reporting this on Runestone_instructors email list.

![image](https://cloud.githubusercontent.com/assets/1077198/17854222/17a85b96-683f-11e6-99a4-d9a03691fbff.png)

**Comment by bnmnetp** [comment]
Yep, this is actually a bug in Skulpt.  the prompt is printed to stdout, which is hidden in your example.  But we'll get the old functionality restored as soon as we can.

**Comment by bnmnetp** [comment]
Fixed in 2.6.8
