### ISSUE TITLE
Documentation / clarity for new ..question directive

### ISSUE THREAD

**Issue by aerenchyma** [RunestoneInteractive/RunestoneComponents#242]
Should add this when we can. 

I have some questions about this that I can abstract into comments or elsewhere as desired, mainly collected in: 
Am I correct that extant directives of whatever type (actex, mult-choice, etc) will not be counted among the questions search in the questionBank, and cannot be added to assignments via the new interface, until they have the correct syntax from https://github.com/RunestoneInteractive/RunestoneComponents/issues/206 ? Or is the goal that the templates provided in the current directives should now account for this?

**Comment by bnmnetp** [comment]
It depends:

Summative questions must be wrapped inside a question directive.  Any directive can be encapsulated into a question.  The search interface for summative questions should only show these.  

Formative: Anything goes for a question that is meant as a formative exercise.  All current directives will show up and they are graded on your doing them rather than correctness.

Is that what you are asking?

**Comment by aerenchyma** [comment]
Yes, thanks!

**Comment by aerenchyma** [comment]
This structure intends for formative questions not to be included in Runestone Assignments, then, correct?

**Comment by bnmnetp** [comment]
Yes, although its not clear to me how they should be communicated.  For summative questions it makes sense to create a worksheet that contains all of those exercises.  For formative things it seems that a link to the section would make more sense, but I haven't thought about it as I don't use that homework strategy.  How do they show up in the pip2 book today?

**Comment by aerenchyma** [comment]
Yes -- I think we've sort of done that in the pip2 book with the Problem Set pages, for the summative questions, so we can convert those to ```..question``s. 

In pip2, for formative questions, they've been primarily assigned via the usageDirective OR included in the problem set pages although they were not graded via our grading interface, because we weren't using the log data.

I think it might be useful for a system like ours to be able to make assignments that are collections of formative questions -- did you do <some threshold> of this, and that's what the usageDirective becomes? @presnick may have other thoughts. I'm curious what seems most generalizably useful as well.

**Comment by aerenchyma** [comment]
To summarize recent discussion in real-time:
I see the ability to write a formative assignment -- this is from activecodes, not questions:
<img width="651" alt="screen shot 2016-08-24 at 11 24 26 am" src="https://cloud.githubusercontent.com/assets/1413839/17936609/5b81584a-69ed-11e6-8f18-13a282b0d61b.png"> This is OK and intended, but formative assignments' grading/autograding does not work yet. We can probably use most of what @presnick has already written to enable threshold grading or something like that for formative assignments (though currently in the new assignments interface, that does not include what you have to read/time you spend, I think?).

However, for summative assignments, you can create those with any ids that are Questions (use the question directive). Grading for those is in progress, parallel to the old grading interface.

Other issues that may come up: improved search for div_ids, and I'm going to test out the assignment creation appearance on rebuild myself, which should go in different threads.

Of course correct me if anything is wrong here!

**Comment by bnmnetp** [comment]
we don't have a question directive anymore.
