### ISSUE TITLE
Change from student to instructor?

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/RunestoneComponents#243]
Error reported in course thinkcspy on page index by user pweiner pweiner@smumn.edu
I have used this book as a student (sitting in on my colleague's class), but now I am going to be teaching a course using these materials, and so would like to become an instructor.  I can't figure out how to do that.

**Comment by bnmnetp** [comment]
This is a first.  There is no button to become an instructor, you just have to create your own course.  This will make you the instructor of the course you build.  However, the site won’t let you go to the instructors interface as a student unless you are enrolled in one of the open textbooks.  So, change your profile to enroll in thinkcspy and then go to the instructors interface and create your own course.

If you are going to be co-teaching a course and the book already exists then the registered instructor for that course can use the Beta instructors interface to add you as an instructor to that course.
