### ISSUE TITLE
EX 7.10 Q3 - error msg

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/RunestoneComponents#245]
Error reported in course thinkcspy on page http://interactivepython.org/courselib/static/thinkcspy/Selection/Exercises.html by user willwatts4519 willwatts4519@gmail.com
Get error message: SyntaxError: bad input on line 22 - problem is that there is not a line 22. I get the error when I copy the answer in too.

**Comment by bnmnetp** [comment]
There was an indentation problem with the unit tests.  I've fixed and pushed a new build of thinkcspy.
