### ISSUE TITLE
log the results of unit tests

### ISSUE THREAD

**Issue by bnmnetp** [RunestoneInteractive/RunestoneComponents#246]
@RunestoneInteractive/contributors 

I am about to commit a change that allows the unittest module to log the results of the run to the useinfo table.  The entry in the table looks like this at the moment.  Is the percentage good for everyone?  Would you rather see number of tests that passed and the number that did not.

```
| 12179733 | 2016-08-24 15:38:08 | bmiller | unittest   | percent:50.0  | ex_6_7|   mycourse |  
```

The next step would be to incorporate this into an auto grade controller for questions that have unit tests.

I think I can also make some progress on adding some functionality to unittest.gui that would allow us to get the output  (as requested in #225 ) as well as the raw code of the user.  In case we might want to add unit tests that match for some particular word or whatever in the code.

**Comment by bnmnetp** [comment]
I decided to just log everything - percent, the number passed and the number failed.

Also added two methods to TestCaseGui: getOutput()  - returns the text from the output widget, and getEditorText() which gets the contents of the editor

<img width="991" alt="screenshot 2016-08-24 17 40 37" src="https://cloud.githubusercontent.com/assets/51115/17951016/94e8884c-6a24-11e6-958c-c105cfbfb3c3.png">

These  changes are on github, but I have not yet made another release of runestone.

**Comment by presnick** [comment]
That's totally awesome! Now we can have unit tests for printed output,  and
also to check for things like hard coding.

sent from mobile-- strange words are probably auto-correct gone awry.

**Comment by aerenchyma** [comment]
Yes, this is fantastic! I'm so excited.

**Comment by presnick** [comment]
Hey, Brad, where do I get these updates? The latest version of
RunestoneServer doesn't have any extra fields in the useinfo table.
