### ISSUE TITLE
"^": XOR or Exponent Operator?

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/RunestoneComponents#252]
Error reported in course pythonds on page InfixPrefixandPostfixExpressions by user leros zhleiyu@gmail.com
The meaning of ^ is not clear in expression 5 * 3 ^ (4 - 2). It could be XOR or an exponent operator. The  precedence of those two are different. To get a pass on "Check me", I have to assume it is an exponent operator.

**Comment by bnmnetp** [comment]
Fixed to use the correct notation for exponentiation.
