### ISSUE TITLE
Need to make the new explainer div prefix to activecodes play nice with timed exams

### ISSUE THREAD

**Issue by bnmnetp** [RunestoneInteractive/RunestoneComponents#254]
With runestone 2.7.0 the activecodes go missing from the timed exams.  I suspect this is because the textarea tag with the data-component attribute of activecode is wrapped inside a new div.

@flysaiah lets brainstorm about how we can make these work together.  I think this solves a very important problem for timed exams.  (that is that you could not really have explanatory text for your activecode.

Do you have any time today to talk?

**Comment by flysaiah** [comment]
@bnmnetp Yes, I am free pretty much all day today except for 6-7:30.

**Comment by bnmnetp** [comment]
OK, I have updated activecode.py to include the data-childcomponent attribute on the outer div for an activecode.  The data-childcomponent is automatically populated by the directive so it will always match the divid of the inner activecode.

```
<div data-childcomponent="timedactive" class="explainer ac_section alert alert-warning">

<textarea data-component="activecode" id=timedactive data-lang="python"    data-timelimit=25000  data-codelens="true" data-audio=''     >
print("hello world")
</textarea>
</div>
```

**Comment by bnmnetp** [comment]
fixed
