### ISSUE TITLE
Exercises not visible in the (old) grading interface

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/RunestoneComponents#258]
Error reported in course smhs_code_16 on page http://interactivepython.org/runestone/assignments/detail?id=976&sid=60064 by user dleesmusd dlee@smusd.us
My Username: dleesmusd
My email: dlee@smusd.us
Browser: Chrome and Safari

Students are having their work erase after being run. An empty file is saved on the teacher's account. 

Specific example: Ethan Wang on problem ex_3_13.

**Comment by bnmnetp** [comment]
The exercises are all safely stored in the database, however they do not appear to be visible to the grader.
