### ISSUE TITLE
Assignment directive should both add and remove questions

### ISSUE THREAD

**Issue by aerenchyma** [RunestoneInteractive/RunestoneComponents#262]
This will work because all student information (work, grades) are tied to their user id and the question id. Relationship between questions and assignments is a separate relationship.

**Comment by aerenchyma** [comment]
This is for @presnick.

**Comment by bnmnetp** [comment]
I don't understand how (or why) a directive would remove a question?

**Comment by aerenchyma** [comment]
Oh, removal was meant only from the assignment collection. The intention of this was such that if you put the directive like:

```.. assignment::
     :name: A1
     :questions: q1 2, q2 3, q3 2
etc```

and then realized you didn't want q3 to be part of assignment a1, you could edit the assignment directive and the build would update the database associations appropriately.

**Comment by bnmnetp** [comment]
obsolete
