### ISSUE TITLE
finish new drag and drop matching directive

### ISSUE THREAD

**Issue by bnmnetp** [RunestoneInteractive/RunestoneComponents#28]

**Comment by bnmnetp** [comment]
@flysaiah drag and drop looks nice.   One thing I would like to see added would be some feedback on the drop side.  A change in the background color of the drop zone when you are dragging over it would be a really good thing.

**Comment by flysaiah** [comment]
I added feedback at the bottom (similar to MC, FITB and Clickable Area) and some CSS rules that highlight the dropzone when you are dragging over it as well as highlighting incorrect answers (similar to parsons).
