### ISSUE TITLE
email registration is broken

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/RunestoneComponents#289]
Error reported in course thinkcspy on page https://interactivepython.org/runestone/default/user/register by user portnoy portnoy@gmail.com
https:// is strongly preferable, we are sending passwords here, but the REcaptcha is not shown and can not be used.

I'm using Chrome Version 49.0.2623.112 (64-bit) on OS X 10.8.5

I ended up registering using google.

thanks,
Eugene

**Comment by bnmnetp** [comment]
Disabled captcha -- probably needs a web2py upgrade to work again.
