### ISSUE TITLE
Errors in user highlight data interrupts page setup causing most components to fail.

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/RunestoneComponents#299]
Error reported in course HTTLACS on page 2DimensionalIterationImageProcessing by user anthony.maranca anthony.maranca@gmail.com
rangy-core.js:10 Discontiguous selection is not supported.

Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.

rangy-core.js:10 Uncaught TypeError: Failed to execute 'selectNodeContents' on 'Range': parameter 1 is not of type 'Node'.

**Comment by bnmnetp** [comment]
I'm not sure on this but it appears that when the parent_class is null then we the range-core error.

When this error happens it causes any further processing of runestone directives to be ignored.  So the page looks like crap, and none of the components work.

I've wrapped this in a try/catch and logged the error for now, as it seems  a lot more user friendly for this to fail gracefully.  Users can live without highlights but a highlight error should not trash the page.
