### ISSUE TITLE
"Supposed" Recursive function is not recursive

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/RunestoneComponents#305]
Error reported in course pythonds on page http://interactivepython.org/runestone/static/pythonds/Recursion/StackFramesImplementingRecursion.html by user anonymous sarpotd@yahoo.com
Hi!

You are using a while loop here (and not a recursive call)

Looks like an oversight. The wrong code was inserted here.

Thanks

**Comment by bnmnetp** [comment]
I should have said "instead of" rather than prior to.  The example is to illustrate the implicit use of the stack in recursion.   I've updated the wording and will publish soon.
