### ISSUE TITLE
same book, different exercises

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/RunestoneComponents#317]
Error reported in course Programming_1 on page thinkcspyExercises by user tmeyer t.meyer@kaneland.org
Some of my students see one page of exercises at the end of chapter 6 and some see another. The two URLs are:
http://interactivepython.org/runestone/static/thinkcspy/Functions/thinkcspyExercises.html
http://interactivepython.org/runestone/static/Programming_1/Functions/thinkcspyExercises.html

**Comment by bnmnetp** [comment]
You should rebuild your Programming_1 book to get the latest changes in thinkcspy.
