### ISSUE TITLE
Incorrect Answer

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/RunestoneComponents#321]
Error reported in course How to Think Like a Computer Scientist: Interactive Edition on page http://interactivepython.org/runestone/static/thinkcspy/PythonTurtle/IterationSimplifiesourTurtleProgram.html by user anonymous mohamedatef6@gmail.com
Hello Sir,

I believe the answer of exercise "turtle-6-6" is incorrect, the answer should "A" while the current accepted answer is "C", the code is the same as the one used in the second example on the same page "ActiveCode:2 (ch03_forcolor) ".
Browser used: Chrome version 55.0.2883.87 m

Best regards.

**Comment by bnmnetp** [comment]
This question is very frequently reported as a bug, but it is not.  The feedback could be made more clear.  The feedback for answer A currently reads:

```
Incorrect. The items in the list are not actually used to control the color of the turtle because aColor is never used inside the loop. But, the loop will execute once for each color in the list.
```
But something along the lines of
```
Incorrect.  The question is not asking you to describe the outcome of the entire loop, the question is asking you about the outcome of a **single iteration** of the loop.
```
