### ISSUE TITLE
"Edit Profile"

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/RunestoneComponents#328]
Error reported in course thinkcspy on page http://interactivepython.org/runestone/default/user/profile by user L1L1L3 logen9706@gmail.com
My email changed, so I went to the page titled, "Edit Profile" in order to change my email. However, none of the pieces of information could be altered (I was not able to type in my new email). Just as a test, I also tried clicking on my name to see if I could change anything else on the page, and nothing could be changed. Basically the text box, that contains all the pieces of information that compose my account, was not interactive (could not type into it). I hope I was descriptive enough to be understood.

**Comment by bnmnetp** [comment]
I have not been able to reproduce this problem.   Is this still happening for you?
