### ISSUE TITLE
Incorrect student names appearing in beta instructor view

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/RunestoneComponents#341]
Error reported in course Colgate-S17-COSC-101 on page http://interactivepython.org/runestone/admin/admin by user vramachandran vramachandran@colgate.edu
In the Admin tab of the beta instructor view, I am seeing student names who are not actually attached to my course.

**Comment by bnmnetp** [comment]
Can you give me a couple of username so that I can do some database investigation and see what is happening?
