### ISSUE TITLE
SpliceOut -- handling both children

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/RunestoneComponents#357]
Error reported in course pythonds on page SearchTreeImplementation by user anonymous j.a.zastrow.jr@gmail.com
Hi, this is just a question on the logic of the spliceOut function.

What happens when the successor node to be spliced has both a left and right child? It doesn't look like the code provided would handle the right child -- it would process the if self.hasLeftChild then skip the else.

Should the 'else' be an 'elif'?

def spliceOut(self):
    if self.isLeaf():
        if self.isLeftChild():
               self.parent.leftChild = None
        else:
               self.parent.rightChild = None
    elif self.hasAnyChildren():
        if self.hasLeftChild():
               if self.isLeftChild():
                  self.parent.leftChild = self.leftChild
               else:
                  self.parent.rightChild = self.leftChild
               self.leftChild.parent = self.parent
        else:
               if self.isLeftChild():
                  self.parent.leftChild = self.rightChild
               else:
                  self.parent.rightChild = self.rightChild
               self.rightChild.parent = self.parent

**Comment by bnmnetp** [comment]
By definition, the successor node will not have two children.  You can convince yourself of this if you think through the logic for finding the successor.
