### ISSUE TITLE
Site (and More Importantly Login Page) not Encrypted - Use TLS/HTTPS Everywhere

### ISSUE THREAD

**Issue by nicorellius** [RunestoneInteractive/RunestoneComponents#369]
I heard your show on Talk Python to Me, and I went to `interactivepython.org` -- cool episode and great site, by the way... can't wait to use it... but I noticed it wasn't using HTTPS everywhere. This would be a great project for one of your students -- setup HTTPS everywhere with Lets Encrypt. Super easy to do. Setting it up with Nginx or Apache is about the same difficulty level (a few hours to a day for a complete newbie, and an hour or less for someone who knows how to do it).

Anyway, I know you don't need to log in to use the site, but you should probably be, at the very least, encrypting your login page. All your students and users have been sending their user names and passwords in plain text through through browser...

**Comment by bnmnetp** [comment]
I totally agree.  This will be a priority this summer when I get some time to do some real coding work on the project.

**Comment by bnmnetp** [comment]
See the new site at https://runestone.academy

**Comment by nicorellius** [comment]
Awesome! I'm glad you got this taken care of. Cheers
