### ISSUE TITLE
At Least One Student Not Appearing in Course

### ISSUE THREAD

**Issue by e3-cerruti** [RunestoneInteractive/RunestoneComponents#374]
I have about 25 students in a course, I am only seeing progress for around 18. A student, edwin.machado, showed me his progress while apparently logged into the course.

http://interactivepython.org/runestone/static/e3Python/index.html

**Comment by bnmnetp** [comment]
Thanks, I'll take a look at the user in question and at other data for your course and see if I can figure out what is happening.

**Comment by e3-cerruti** [comment]
Also: jacqkeni03

**Comment by bnmnetp** [comment]
Same problem with jacqkeni03  -- they are not enrolled in a valid course and need to update their profile.

**Comment by e3-cerruti** [comment]
Thanks, I will check in with the students during tomorrow's class and close the issue.
