### ISSUE TITLE
Unreachable code in example

### ISSUE THREAD

**Issue by cryptogun** [RunestoneInteractive/RunestoneComponents#385]
The else clause will never be reached:
http://interactivepython.org/runestone/static/pythonds/Trees/ParseTree.html#lst-buildparse
```
        if i == '(':
        elif i not in ['+', '-', '*', '/', ')']:
        elif i in ['+', '-', '*', '/']:
        elif i == ')':
        else:
            raise ValueError
```
Because of the second line: `elif i not in`.
And the text after the code may also be amended:
`The only error checking we do in this function is in the else clause where we raise a ValueError exception if we get a token from the list that we do not recognize.`

**Comment by bnmnetp** [comment]
linking this to #386

**Comment by conzty01** [comment]
Would you rather omit the error checking altogether or force the error checking to happen in the first elif statement?

**Comment by bnmnetp** [comment]
I think I would reorder the elifs so that the `not in` check is at the end, and then the assumption is that the token should be an int, so either surround that with a try/except or explicitly check that the token is an int.
