### ISSUE TITLE
Formula typo for analysis worst case AVL Tree

### ISSUE THREAD

**Issue by cryptogun** [RunestoneInteractive/RunestoneComponents#387]
Bottom of http://interactivepython.org/runestone/static/pythonds/Trees/AVLTreePerformance.html
1. `Nh=Fh+2 − 1,h≥1` (4th formula from the bottom)
I think it should be `Nh=Fh + 1,h≥1`
2. `logNh+1=(H+2)logΦ−12log5` (3nd formular from the bottom)
`H` >> `h`

**Comment by bnmnetp** [comment]
fixed in dev version
