### ISSUE TITLE
Wrong big O notation in summary

### ISSUE THREAD

**Issue by cryptogun** [RunestoneInteractive/RunestoneComponents#388]
http://interactivepython.org/runestone/static/pythonds/Trees/SummaryofMapADTImplementations.html

Performances of Column `Binary Search Tree` are all `O(n)`
According to http://bigocheatsheet.com/ they are all O(log(n)).

**Comment by bnmnetp** [comment]
You need to look at the bigocheatsheet table a bit more closely.  They are making the distinction between *average* time Θ(log(n)) notice the Θ and *worst* case O(n).  Our table is only showing the worst case numbers and is correct as it is.

**Comment by cryptogun** [comment]
Ok, thanks. I didn't notice it is `O` not `Θ` in your page. I thought it is average case.
Well then `Hash Table` column is incorrect. Both bigocheatsheet and [Wikipedia](https://en.wikipedia.org/wiki/Hash_table) say they are big `O(n)`. Due to probing or chaining.
