### ISSUE TITLE
Parsons problems are limited in width again 

### ISSUE THREAD

**Issue by ericsonga** [RunestoneInteractive/RunestoneComponents#410]
With some of the new changes the Parsons problems are limited to 500 px wide, and they should be allowed to be as large as the activecode.  The problem seems to be that they are now in a runestone container which has a limit of 500px wide.  In the past they were not in this container.  Can we remove it again from this container?  Everything else is the same.

**Comment by bnmnetp** [comment]
We should leave the container as it has many benefits.  We can adjust the CSS to allow for wider parsons problems.

**Comment by bnmnetp** [comment]
I fixed this by changing the container div for parsons problems to look like this:
```
<div class="runestone" style="max-width: none;"> 
```
