### ISSUE TITLE
Can't remove a question from an assignment without refreshing page

### ISSUE THREAD

**Issue by bnmnetp** [RunestoneInteractive/RunestoneComponents#415]
If I add a question and then change my mind, clicking the x to remove the question from the assignment table has no effect until I refresh the page.

**Comment by bjones1** [comment]
Fixed in https://github.com/RunestoneInteractive/RunestoneServer/tree/assignment_interface.

**Comment by bjones1** [comment]
@bnmnetp, please close -- I don't have the ability to.
