### ISSUE TITLE
The unCamel function in chapternames.py doesn't seem to produce good subchapter names

### ISSUE THREAD

**Issue by presnick** [RunestoneInteractive/RunestoneComponents#419]
unCamel, on line 20 in server/chapternames.py, is supposed to give us human readable subchapter names. It seems to add spaces before camel cased capitals. I guess the solution is that we should rename files with better camel casing? Or is there some way we could get the chapter and subchapter names from directives in the .rst files, and have them be available in chapternames.py/findChaptersSubChapters ?

![image](https://user-images.githubusercontent.com/1077198/28233940-a77ad76e-68c8-11e7-97b7-7658d5c37139.png)

**Comment by bnmnetp** [comment]
I was doing a bit more investigation, and I think there is a better solution.

We can add a function as an event handler to the sphinx event 'build-finished'

The following code prints out the file name and the title for that file.

We could adapt the current code that reads the toctree and use this dictionary instead of trying to reconstruct the human readable title from the camelcase.

```
def process_activcode_nodes(app, ex):    
    for k in app.env.titles:
        print(k, app.env.titles[k].children[0].astext())
```

Connecting this to a sphinx event anyway seems like a much cleaner solution for adding this processing anyway.

**Comment by presnick** [comment]
Sounds very promising!

sent from mobile-- strange words are probably auto-correct gone awry.

**Comment by bnmnetp** [comment]
OK, I think this will do what we want.

```
import docutils

chapId = ''
chapsubs = {}
chaptitles = {}
subtitles = {}

def doctree_resolved(app, doctree, docname):
    global chapId
    for section in doctree.traverse(docutils.nodes.section):
        #print(section.source,dir(section.document))
        title = section.next_node(docutils.nodes.Titular)
        pl = section.source.split('/')
        chapId = pl[-2]
        subchapId = pl[-1]
        if chapId not in chapsubs:
            chapsubs[chapId] = []
        if chapId not in subtitles:
            subtitles[chapId] = []
        if title:
            if subchapId == 'toctree.rst':
                chaptitles[chapId] = title.astext()
            if subchapId not in chapsubs[chapId]:
                chapsubs[chapId].append(subchapId)
            if subchapId not in subtitles:
                subtitles[subchapId] = title.astext()


def build_finished(app, ex):
    for k in chapsubs:
        for sub in chapsubs[k]:
            print(k, chaptitles[k], sub, subtitles[sub])
```

The only thing I don't recall was whether or not the order of the chapters/subchapters was important.  Right now we insert them in the proper order.  The way sphinx works we are handed the subchapters in whatever order sphinx processes them.

**Comment by presnick** [comment]
Yes,  it's good that you are inserting in toctree order. It would be good
to add a sortby id in the query that retrieves them for inclusion in
assignment.html.

sent from mobile-- strange words are probably auto-correct gone awry.

**Comment by bnmnetp** [comment]
OK, we are not quite there then. I'll have to find a way to get back to the toctree.rst file to get the proper order.

**Comment by presnick** [comment]
The function findChaptersSubChapters in server/chapternames.py (in
RunestoneComponents) may have useful code for you for getting the toc
order.

Perhaps you could add a tocorder field to the chapters and subchapters db,
and use the code that's there to computer the desired ordering.

The place where we should be querying for the toc ordering is in runsetone
server admin/_get_toc_and_questions. There are two queries, chapters_query
and subchapters_query that should have an ordering inside their select
clauses.

**Comment by bnmnetp** [comment]
gone!!
