### ISSUE TITLE
Sentence incomplete

### ISSUE THREAD

**Issue by shrivatsahosabettu** [RunestoneInteractive/RunestoneComponents#423]
Hi,

   In chapter _"2.7. Operators and Operands"_ the statement _"In the above example, 7 divided by 3 is 2 when we use integer division and there is a remainder of 1."_ is incomplete.

I think it should have been "In the above example, 7 divided by 3 is 2 when we use integer division and there is a remainder of 1 _when we use modulus operator._

**Comment by bnmnetp** [comment]
fixed.
