### ISSUE TITLE
Wrong link shown when creating new course at runestone.academy

### ISSUE THREAD

**Issue by cigas** [RunestoneInteractive/RunestoneComponents#432]
While waiting for a new course to build at runestone.academy, the instructions still show a link back to interactivepython.org for accessing the course. See below:

The course build has started.

...

Please -- If the build takes longer than 10 minutes Do NOT just try to build a new course. Please contact me by email at RunestoneInteractive. You can also try to access your course, by using a URL of the form: **http://interactivepython.org/runestone/static/<yourcoursename>/index.html** If you get an error message contact me by email and I will investigate and get your course built correctly.

**Comment by bnmnetp** [comment]
Fixed, thanks
