### ISSUE TITLE
Exercise 2_4 is missing descriptive text

### ISSUE THREAD

**Issue by cigas** [RunestoneInteractive/RunestoneComponents#434]
Exercise 2_4 is missing part of a description. See below:

It is possible to name the days 0 through 6 where day 0 is Sunday and day 6 is Saturday. If you go on a wonderful holiday leaving on day number 3 (a Wednesday) and you return home after 10 nights ????something is missing here??????. Write a general version of the program which asks for the starting day number, and the length of your stay, and it will tell you the number of day of the week you will return on. 

I think a better/replacement description should be:

It is possible to number the days of the week 0 through 6, where day 0 is Sunday and day 6 is Saturday. If you go on a wonderful holiday leaving on day number 3 (a Wednesday) and you return home after 10 nights, then it will be day 6, a Saturday. Write a general version of the program which asks for the starting day number and the length of your stay, then the program will print the number of the day of the week you will return on.

**Comment by bnmnetp** [comment]
fixed
