### ISSUE TITLE
Getting logged out after selecting a book

### ISSUE THREAD

**Issue by cigas** [RunestoneInteractive/RunestoneComponents#436]
On runestone.academy, the first time I login from a browser I get logged in fine, but when I select a book, it briefly shows me the book, but then logs me out and returns me to the sign in page again.  The second time I log in and select the book, everything works fine. I can then continue to log in and out just fine. However, if I clear all my browsing history, I get bounced after the first login again.

**Comment by bnmnetp** [comment]
This is a small lingering problem with changing over the domain from dev.runestone.academy to runestone.academy.  Rebuilding your course should help, but make sure that when you rebuild you are rebuilding from the non-dev domain name in the instructor interface.

**Comment by cigas** [comment]
OK, but I can't get to a non-dev domain. When I click on the course link, I'm thrown right into the dev domain. I think this is true even for a course I created on Monday or Tuesday of this week, though I can't remember when I did what right now.

**Comment by bnmnetp** [comment]
When you get to the instructors page, just modify the URL by removing the dev

But never mind that, I think I fixed it for you the old fashioned way:

```
sed -i.bak s/dev.runestone.academy/runestone.academy/g **/*.html
```
