### ISSUE TITLE
New activecode uses unsupported methods

### ISSUE THREAD

**Issue by riknos314** [RunestoneInteractive/RunestoneComponents#45]
Line 1345 in activecode.js uses the .includes method of an array which is part of EMCAscript 2016 and is not supported in current-generation browsers.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes#Browser_compatibility

**Comment by bnmnetp** [comment]
I guess thats what I get for testing with Safari 9.0  It does support includes.
