### ISSUE TITLE
i can't see the question

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/RunestoneComponents#454]
Error reported in course KOM202IPB on page https://runestone.academy/runestone/assignments/doAssignment?assignment_id=199 by user G14160039 tenniareydita@yahoo.co.id
when I open the assignment, the question fails to open, so there are no questions and practice questions. i try it so many times but the question doesnt appear.

**Comment by bnmnetp** [comment]
I joined your course and I can see all of the questions just fine.
