### ISSUE TITLE
self check 3 in "3.9. Infix, Prefix and Postfix Expressions" use different operand to check.

### ISSUE THREAD

**Issue by Hobinx** [RunestoneInteractive/RunestoneComponents#464]
The check said: "Modify the `infixToPostfix` function so that it can convert the following expression: 5 * 3 ** (4 - 2)", however, the check use `^` to check, the correct answer this check said: `5 3 4 2 - ^ *`, rather than `5 3 4 2 - ** *`.

**Comment by hamc17** [comment]
Can confirm this is still a problem, left me scratching my head for a while until I checked the video!

**Comment by bnmnetp** [comment]
No, you were on this page: http://interactivepython.org/runestone/static/pythonds/BasicDS/InfixPrefixandPostfixExpressions.html#postfix-evaluation

I am no longer updating interactivepython.org

**Comment by hamc17** [comment]
My mistake. Thanks.
