### ISSUE TITLE
Issues with Assignment points and viewing grades.

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/RunestoneComponents#467]
Error reported in course Wiese on page https://runestone.academy/runestone/static/Wiese/index.html by user hwiese hwiese@lcps.org
1. Assignment 1 is worth 8 points, but it is grading out of 9.
2. Assignment 4 reading is worth 20 points, but it is grading out of 12.
3. I used to be able to see grades for my whole class. Now I can only see grades for the first few students in my gradebook.

**Comment by sspiegels** [comment]
I am having a similar issue. On Thursday, my String 1 assignment was graded for the entire class (@50 students).  On Friday, the grades for 20/50 of these students disappeared, and the next assignment was only 1/2 graded. The same students were missing grades in both assignments. Mostly missing grades are the second half of the alphabet.

My info: https://runestone.academy/runestone/static/MadAP2017/index.html by sspiege3@schools.nyc.gov

Pardon me, I don't know the protocol for posting..

**Comment by bnmnetp** [comment]
OK, I rewrote the code for populating the gradebook table this weekend.  this version is more robust when it comes to students having the same name.
