### ISSUE TITLE
Ch 7 Exercise 3 reporting error on line not typed by user

### ISSUE THREAD

**Issue by psmaker** [RunestoneInteractive/RunestoneComponents#470]
There seems to be some sort of error in the test code for ex_6_3.  It is reporting an error on a line that doesn't exist in the code.

![image](https://user-images.githubusercontent.com/28868409/30832681-d2e4731c-a200-11e7-81fe-845d80222fe9.png)

**Comment by EricGT** [comment]
As another user confirming it is real. Did a rebuild and error is still there. Checked [code](https://github.com/RunestoneInteractive/thinkcspy/blob/master/_sources/Selection/Exercises.rst) and RST is out of alignment.

**Comment by bnmnetp** [comment]
Yep. I would be happy to accept a PR from anyone willing to help clean these up.

**Comment by psmaker** [comment]
I'm going close this here.  I mistakenly put it in this area when I had already opened up this issue the other day in the thinkcspy repository.  Just totally forgot I had already opened one up...

**Comment by psmaker** [comment]
whoops hit the wrong button... and didn't close it.
