### ISSUE TITLE
Audio tours are not working again on Runestone.Academy

### ISSUE THREAD

**Issue by ericsonga** [RunestoneInteractive/RunestoneComponents#484]
The audio tours are not working on Runestone.academy

**Comment by bnmnetp** [comment]
Barb,

Can you please provide more detail?  Which one's are not working for you?  Do you get any errors in the JavaScript console?

**Comment by valmonaco** [comment]
I’ve encountered a similar issue.  

For example, when trying to load the audio tour for https://runestone.academy/runestone/static/StudentCSP/CSPNameNumbers/driving.html

I’m seeing console 404 errors for files. Here is an example URL which returns a 404:  http://media.interactivepython.org/StudentCSP/audio/trp-line7.mp3. 

Looks like this URL may be constructed starting at line 1217 in 
https://github.com/RunestoneInteractive/RunestoneComponents/blob/c5caca86bbbda41f858aab363cb9f59e2e204afd/runestone/activecode/js/activecode.js

**Comment by ericsonga** [comment]
It looks like it is a http versus https issue.  We are having the same trouble with the YouTube videos too.  The audio files are at http://media.interactivepython.org/  Can you setup a server that uses https?

**Comment by ericsonga** [comment]
You can test with the first audio tour at http://interactivepython.org/runestone/static/StudentCSP/CSPrinTeasers/computeNumbers.html  on the old server and at https://runestone.academy/runestone/static/StudentCSP/CSPrinTeasers/computeWords.html on the new server
