### ISSUE TITLE
Riley Coan duplicate account

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/RunestoneComponents#502]
Error reported in course LJHS_AP_CSA on page https://runestone.academy/runestone/static/LJHS_AP_CSA/index.html by user LJHS_mstuart mstuart1@sandi.net
Hi,

I have one more student who had trouble with his account and made a duplicate account that seems to be messing things up.  Would you please delete the account with the following information:

Username: LJHS_rcoan
Email: rcoan02@gmail.com

Thank you!

**Comment by EricGT** [comment]
For Brad,

Just a suggestion for latter as I know you are more than busy.

In a related case my class has a student who has three different ids and I would like to delete the unused ones. The delete student option (instructors account -> instructors page -> Admin tab -> Manage Students tab) could be used if the list of students showed more than just there name, e.g. the e-mail account which uniquely identifies the student. 

I also just rebuilt the course in case the page might have been updated, but it only listed the student names.

Thanks,
Eric
