### ISSUE TITLE
faulty acticode box

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/RunestoneComponents#503]
Error reported in course Python on page https://runestone.academy/runestone/static/Python/Functions/thinkcspyExercises.html by user sm42397 steven1968mull@gmail.com
Question 12 activecode: 7 (ex_5_7)
gives the following error 
Error

SyntaxError: bad input on line 9

Description

This message indicates that Python can't figure out the syntax of a particular statement. Some examples are assigning to a literal, or a function call
To Fix

Check your assignment statments and make sure that the left hand side of the assignment is a variable, not a literal or a function.

however if i copy and paste my code into one of the extra activecode boxes at the end of another chapter the code works fine. so i would guess its just a problem with this box.

**Comment by bnmnetp** [comment]
This was fixed some time ago.  Please rebuild your book.
