### ISSUE TITLE
Activecode download 

### ISSUE THREAD

**Issue by kooi** [RunestoneInteractive/RunestoneComponents#510]
I would like to I've students the ability to download the code from an activecode block. This gives students the ability to backup / export their work to other systems easily.

**Comment by bnmnetp** [comment]
Thats an interesting idea.  

Are you thinking that this would work for a single activecode?  There would be a button that would prompt them to enter a name and then they would get a name.py file in their download folder filled in with the code from that activecode window?

I always just have my students copy and paste.  What are the advantages of having a download link over the copy/paste approach?

**Comment by kooi** [comment]
I've actually managed to get this working; I extended the activecode definition with an :enabledownload: flag so you can turn this off and on. If this is a useful feature I'll do a pull request.

I considered the copy-paste method which I thought would be no problem, but I've been working with kids (age 11-12) with a very varied skillset; most don't really seem to have trouble grasping the basic programming concepts but basic computer skills are sorely lacking in many (the concept of copying and pasting is alien?!) and this seemed an easy solution to hand in files via moodle without needing LTI-integration (which personally I think I would prefer).

**Comment by bnmnetp** [comment]
Indeed LTI integration is on the roadmap for a couple of years.  I think it (LTI) may have gotten to the point where we can really make it a high priority this summer.

In the meantime, I would be happy to accept a PR for this.

Thanks!
