### ISSUE TITLE
Add ability to specify Jobe run_spec parameters to activecode directives

### ISSUE THREAD

**Issue by DaveParillo** [RunestoneInteractive/RunestoneComponents#511]
Enhancement request.

The flexibility of using Runestone is limited for Java (somewhat) and C/C++ (a lot).

The run_spec is hard_coded in activecode.js and livecode.js.
Being able to specify `compileargs: ['-std=c++11', '-Wall', '-Wpedantic'] ` would be very useful.
I'm sure pyhton and java would benefit from interpreterargs also.
See [Jobe readme](https://github.com/trampgeek/jobe#run_spec-parameters) for details.

It was easy to modify the javascript for this change, but not being a python programmer and never having written a Sphinx directive, adding new properties to the active code directive was a bit beyond me.

**Comment by bnmnetp** [comment]
Good point!

I'll take a look, but I should be able to add something to the directive to make that possible.  Luckily I have my grading done and a nice long break ahead of me.

**Comment by DaveParillo** [comment]
I started this, but could not get it to work as a directive.
It was trivial to get it to work using hardcoded values set directly in activecode & livecode.js: 
[activecode.txt](https://github.com/RunestoneInteractive/RunestoneComponents/files/1564974/activecode.txt)
[livecode.txt](https://github.com/RunestoneInteractive/RunestoneComponents/files/1564976/livecode.txt)

But when I tried to hook this to the activecode directlve, it stopped rendering the HTML for any directive that contained a 'compileargs' option.  No errors or warnings were displayed either during compile or runtime and I don't know how to run the runestone serve process in a debugger, so I stopped.
I can check this half-working version in on a branch if you think it would be helpful.

This *seemed* like it should be a simple enhancement ...

**Comment by bnmnetp** [comment]
I just pushed changes that allow you to specify options for compileargs, interpreterargs, runargs and linkargs in the directive.  I tested it with your example list and it worked great.

**Comment by DaveParillo** [comment]
Tested in both my textbook and in the runestone docs branch. works great
