### ISSUE TITLE
Scratch active code area is 'python only'

### ISSUE THREAD

**Issue by DaveParillo** [RunestoneInteractive/RunestoneComponents#512]
The scratch active code area is hardcoded to python only.
Even the currently [published Java Review textbook](https://runestone.academy/runestone/static/JavaReview/index.html) has a scratch code link that expects python.

Ideally, something along the lines of `.. highlight:: language` would allow a book author to set the language globally for scratch and for code-block and activecode directives.
Maybe in pavement.py?

**Comment by bnmnetp** [comment]
This too should be very doable.  Its great to see people pushing the edges of books beyond python.

**Comment by bnmnetp** [comment]
Just pushed a change for this.   In an existing project you will need to do 2 things to make this work.

1.  Update your layout.html file under _templates/....  So that it has the line:
```
  eBookConfig.acDefaultLange = '{{ default_ac_lang }}';
```
2. Update your pavement.py file adding a line in the template_args assignment to include:

```
                       'default_ac_lang': '%(default_ac_lang)s',
```

**Comment by DaveParillo** [comment]
How does default_ac_lang get set? Tried conf.py and setting 'highlight_language' in conf.py.

**Comment by bnmnetp** [comment]
Sorry, I copy/pasted the string for pavement.py from the default template.  You set default_ac_lang in pavement.py

```
'default_ac_lang': 'cpp',
```
I'm going to edit my coment above so its correct.

**Comment by DaveParillo** [comment]
Thanks, I thought I had tried that, but apparently not.

It appears the url posted assumes acess to a locally hosted runestone server / service endpoint.
When I invoke active code from the http server, the url for the post is:
master url + `/runestone/proxy/jobeRun`

In activecode.py, the this.resource var appears to have this hardcoded in a few places.
Not sure how to set 'resource' dynamically.

I have two instances of the book up, both built using RunestoneComponents/master:
http://209.129.16.61/~dparillo/book/intermediate-cpp/
and
https://daveparillo.github.io/intermediate-cpp/

**Comment by bnmnetp** [comment]
Its set up that way so that the runestone server can act as a proxy for the jobeServer.  Making that more configurable is a work in progress in PR #505

I see that @CABowers has checked in some more code, but it needs review and looks like it has conflicts.

**Comment by bnmnetp** [comment]
With #505 accepted I think the only thing left is for you update your master template, and then configure your book to use the canterbury jobe server directly.  The activecode unittests demonstrate how to configure your pavement.py file.    Now we just need to figure out an https proxy.  Runestone.academy does this, but I have not enabled cross origin requests as that would circumvent the API key security measures they have in place.  We could probably work something out where I could enable it for your daveparillo.github.io domain.

**Comment by DaveParillo** [comment]
Thanks for all the effort -I’m working on the pavement.py config now.
The active code unit tests use slightly different versions from what appears to be used in activecode.js.

activecode.js uses ‘jobehost’, ‘proxyuri_runs’, and ‘proxyuri_files'

the unit test pavement.py uses ‘jobe_host’, ‘proxy_uri_runs’, and ‘proxy_uri_files’

I tried both, but 'this.JOBE_SERVER + this.resource;’  on line 1678 of is activecode.py still evaluating to undefined after rebuilding the book with a modified pavement.py.

Line 1534 sets this.JOBE_SERVER = eBookConfig.jobehost;

the eBookConfig in the running debugger does not contain any of the new properties set in the templates section of pavement.py.

Currently poking around to determine where this object gets read in initially.

**Comment by DaveParillo** [comment]
Tested scratch area in my eBook - works fine. One limitation other should be aware of is that compileargs and interpreter args are going to be whatever the default jobe server supports, but I would close this and consider that a separate future enhancement.

**Comment by bnmnetp** [comment]
Great!  Glad it is working for you now.

I think this summer I will move toward running our own JOBE server.  It seems easy enough as they have a Dockerized version of the server that I was able to get running very quickly.  This will give us more flexibility in configuring and supporting different configurations from authors like yourself.
