### ISSUE TITLE
Inline code literals render incorrectly

### ISSUE THREAD

**Issue by DaveParillo** [RunestoneInteractive/RunestoneComponents#516]
Sometime after release 3.0.7, the rendering for inline literals (`enclosed in backticks`) renders incorrect HTML.

Any line containing code literals now renders at the start of the line with other text on the line after it.  Each inline literal creates a newline in the rendered output.

Noticed first in the book I'm working on, but verified it happens in thinkcspy/master also.

This does not happen in releases 3.0.7 or prior, but have not tried incremental checkouts to see when it was introduced.

**Comment by bnmnetp** [comment]
Unfortunately that is not something that I have control over.  Rendering things in backticks is base functionality of Sphinx.  What version of sphinx do you have installed?

**Comment by bnmnetp** [comment]
Or, perhaps it is a CSS bug that was introduced...

**Comment by bnmnetp** [comment]
Yep, it was a CSS bug 

@ericsonga @CABowers : 
There was a rule added to parsons.css that applied to ALL code tags everywhere, not just in a parsons problem.  I modified the selector to be `.parsons code` which seems fine to me.  But you might want to check it in the context of your adaptive problems just in case.

**Comment by DaveParillo** [comment]
If it helps, I built my book and thinkcspy with the runestone skulpt_upg branch and both parsons problems and code literals appear to be working.

The only noticeable new feature is that inline literals are now shown in bold font, where they did not used to be.

**Comment by bnmnetp** [comment]
Sorry, I meant for that update to be on master not that branch.

**Comment by DaveParillo** [comment]
tested this on /master for my book and it works fine.
Not sure what your process is for closing issues, but no need to hold it open on my account.
