### ISSUE TITLE
Unable to log in

### ISSUE THREAD

**Issue by steevo619** [RunestoneInteractive/RunestoneComponents#525]
Hi there,

I have registered to Runeacademy (username: steevo619; password:) and am trying to log in in order to use the course How To Think Like A Computer Scientist. When I click on "Login" as showed in the attached screen capture, I get taken to the Welcome To Interactive Python page (which seems like a completely different course). If I try logging in there, I see the message "Invalid login." Yes, I am using my username (steevo619) and not my email address. Frustrating!

Thank you,
Steven
<img width="187" alt="login" src="https://user-images.githubusercontent.com/35041501/34495885-0f76b238-efac-11e7-8977-9e5ed056b977.png">

**Comment by bnmnetp** [comment]
I cannot find a username like that in the database on runestone.academy, although I can see that we have quite a few new user registrations today.

Please make sure that when you register you use the course name `thinkcspy` to register for the how to think book.

**Comment by steevo619** [comment]
Thank you! That seemed to work.

It really isn’t clear at all in the registration instructions that there are code names for the courses you register for. I just entered “How To Think Like A Computer Scientist” assuming that would work. You may want to make that clearer.

Thanks again,
Steven

On Jan 2, 2018, at 11:09 AM, Bradley Miller <notifications@github.com<mailto:notifications@github.com>> wrote:


I cannot find a username like that in the database on runestone.academy, although I can see that we have quite a few new user registrations today.

Please make sure that when you register you use the course name thinkcspy to register for the how to think book.

**Comment by bnmnetp** [comment]
The text entry box for the course name does contain a hint:
<img width="344" alt="screen shot 2018-01-02 at 1 31 22 pm" src="https://user-images.githubusercontent.com/51115/34497075-8e5e0582-efc1-11e7-995f-4614d89ff6b4.png">

But I'll see if I can't figure out a way to make that more clear.

**Comment by steevo619** [comment]
Yes, I noticed that after I got your message, but before then I had no idea that I was supposed to enter “thinkcspy.”

Steven

On Jan 2, 2018, at 11:34 AM, Bradley Miller <notifications@github.com<mailto:notifications@github.com>> wrote:


The text entry box for the course name does contain a hint:
[screen shot 2018-01-02 at 1 31 22 pm]<https://user-images.githubusercontent.com/51115/34497075-8e5e0582-efc1-11e7-995f-4614d89ff6b4.png>

But I'll see if I can't figure out a way to make that more clear.
