### ISSUE TITLE
new exercise old answer

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/RunestoneComponents#527]
Error reported in course pythonds on page InfixPrefixandPostfixExpressions by user 2011txy 2011txy@gmail.com
In the exercise "Modify the infixToPostfix function so that it can convert the following expression: 5 * 3 ** (4 - 2)", "^" was replaced by "**", but the correct answer is still "5 3 4 2 - ^ *", which I thought should be "5 3 4 2 - ** *" now?

**Comment by bnmnetp** [comment]
fixed
