### ISSUE TITLE
basecourse duplicates existing course_id

### ISSUE THREAD

**Issue by DaveParillo** [RunestoneInteractive/RunestoneComponents#529]
when creating a new course, the pavement.py file contains two properties that appear redundant

1.  course_id
1. basecourse

The `runestone init` command sets them to the same vale, but an instructor editing them later may remember to change only one of them.

Most custom directives use ` eBookConfig.course`, but activecode uses `eBookConfig.basecourse`.

**Comment by bnmnetp** [comment]
Both of these are needed for the runestone.academy server.  The course is the name of a particular course created by an instructor based on the basecourse.  If you are starting your own book from scratch its a good idea for them to be the same.

The basecourse is also important for how questions are stored in the database so we do not duplicate storing questions for every course.

**Comment by DaveParillo** [comment]
OK. Sounds invalid.  If I understand correctly, these two values should be the same for most anyone **not** cloning a book directly on the runestone server.
