### ISSUE TITLE
Java4Python book needs to be restructured to make assignments work

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/RunestoneComponents#536]
Error reported in course Cheyney-CIS102 on page https://runestone.academy/runestone/static/Cheyney-CIS102/index.html by user DavidCooperCheyney dgcooper@cheyney.edu
When creating an assignment I can't see readings or problems that can be added.

Please let me know if I'm doing something wrong.

Thanks,

David

**Comment by bnmnetp** [comment]
python4java needs to be updated so that chapters/subchapters will work for the assignment builder.

**Comment by bnmnetp** [comment]
I have done this.
