### ISSUE TITLE
Student work not showing

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/RunestoneComponents#543]
Error reported in course SB_Intro_CS_Python on page https://runestone.academy/runestone/dashboard/ind by user MrsJakubielski
I have a student that has 2 accounts (he goofed and created a 2nd account) and for some reason, I am not seeing any of his work.  Initially he accidentally began work in thinkcspy and not my course.  But then he switched to my course.  When he opens his book, I can see the work, but it doesn't show when I open my instructor's page. I can see he accesses the pages but none of his work.
Thank you for any help!
Ann Marie

**Comment by bnmnetp** [comment]
fixed.
