### ISSUE TITLE
Manual grading does not always update assignment totals 

### ISSUE THREAD

**Issue by cigas** [RunestoneInteractive/RunestoneComponents#545]
Look at course CS152HOSP2018 and view the gradebook for CS 152 Readings and Assignment Day 2.

The summary page shows students with various percentages but not all of these match the actual recorded scores. For example, click on one of the 72.73% entries and the individual page showing the graded exercises shows the student has received full credit on everything.

I think this has to do with how I graded the coding exercises. I ran into a similar problem with CS 152 Assignment 1, where the summary was incorrect. I went back to the last student in the grading list, and clicked "Save and next" and then got the little pop-up that said things had been scored. After that, the summary page matched the individual scores.  

From my end, it looks like something doesn't get updated until all items in a list have been graded, and  the system keys off the last item in the grading list for this. My problem is that I like to grade students in different orders, and so the last student I grade may not be the last in the list. I can work around this, but only if the updating scheme is clearly spelled out.

**Comment by bnmnetp** [comment]
I changed the title because the gradebook is correctly representing what is in the database.  But I agree that there needs to be more consistency in updating the database when doing manual grading.  I can't seem to recreate this reliably so it may take some work to figure out what exactly is happening.

**Comment by cigas** [comment]
I have a 14Mbyte screencast video showing pretty consistent behavior from how I grade. It's got some student info so I can't post it here. How would you like it?

**Comment by bnmnetp** [comment]
Can you share a  link to it with me on  either dropbox or a google drive?  You can can send the to the runestoneinteractive gmail account.  I'm the only one with access to that.

**Comment by bnmnetp** [comment]
OK, I've found the offending code...  Around line 304 in admin.js

```javascript
        jQuery('form', rightDiv).submit(save);
        // Handle the save and next button
        jQuery('.next', rightDiv).click(function (event) {
            event.preventDefault();
            jQuery('form', rightDiv).submit();
            var col3 = document.getElementById("gradingcolumn3");
            try {
                var ind = col3.selectedIndex + 1;
                col3.selectedIndex = ind;
                col3.onchange();
            }

            catch (err) {
                //reached end of list
            }
```

You are correct that it keys off of reaching the end of the list, which I think was a conscious choice we made.  But its written in a way that is pretty dangerous.

```javascript
        jQuery('form', rightDiv).submit(save);  <-- set up save to be called on submit event
        // Handle the save and next button
        jQuery('.next', rightDiv).click(function (event) {
            event.preventDefault();
            jQuery('form', rightDiv).submit();  <-- trigger the save event -- causes save to be called ASYNCHRONOUSLY
            var col3 = document.getElementById("gradingcolumn3");
            try {
                var ind = col3.selectedIndex + 1;  <-- Now in the main thread change the selected student.  If we are at the end of the list then the selected student will be null when calculateTotals is called and the code will update the total score for everyone.  This is really a bad way to handle this and should be fixed regardless.  Even worse this race condition actually causes the total for the next student on the list to get calculated most of the time rather than the student who's grade we just updated.
                col3.selectedIndex = ind;
                col3.onchange();
            }

            catch (err) {
                //reached end of list
            }
```

If the bug mentioned above is handled, that is we update the total score for the proper students then I think this solves your problem @cigas ?

@presnick @aerenchyma have you run across this?  What are your thoughts?

**Comment by bnmnetp** [comment]
@cigas I've pushed a fix for this to runestone.academy.  You won't see the popup as I think that would be super annoying if it popped up for every student, but in my testing it is now correctly updating the total score for each student (the correct student) as you go along.

**Comment by cigas** [comment]
Thanks! This seems to be working from my end too. The popup would be very annoying - I'm glad it's gone.
