### ISSUE TITLE
Not able to create New Assignments under the "Assignments" page  

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/RunestoneComponents#546]
Error reported in course IHS-APCSA on page https://runestone.academy/runestone/assignments/chooseAssignment.html by user obryant bryanto@friscoisd.org
SInce the beginning of year 2018, the assignments created from the "Instructor's page" is not displaying on the "Assignment" page nder the Course view, therefore no assignment handel was created. This is the case for all the courses under Runestone Academy from my end.

**Comment by bnmnetp** [comment]
What DO you see?  I have not seen any kind of crash report. Is it a blank page or do you get an error?

**Comment by cigas** [comment]
When you create an assignment, now there's a checkbox to make that assignment visible on the Assignments page. I've forgotten to check it several times when creating an assignment, but it's nice later on to be able to hide past assignments and reduce clutter.

**Comment by bnmnetp** [comment]
I can confirm that the checkbox was not checked for these assignments.

Maybe some kind of more obvious visual indicator or better wording would make it more clear when this is unchecked -- Any ideas??

**Comment by cigas** [comment]
Maybe put it on the same line as the due date. It's easy to miss where it is.

Not sure if it should come first or second on the line though.

**Comment by bnmnetp** [comment]
I've added making the visible check box more prominent to my todo list.
