### ISSUE TITLE
Student Registration Issue

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/RunestoneComponents#549]
Error reported in course APJAVA2018 on page https://runestone.academy/runestone/admin/admin by user czajkas1 czajkas@rbhs208.net
I have been trying to have my students register for this class (actually I tried with two classes APJAVA2018 and APCSA2018) and when students put in either Course Name they get a message the course does not exist and to see the Instructor.  Can you please help me determine what I am doing wrong or what the issue is for my students?  Thank you!

**Comment by bnmnetp** [comment]
Students were directed to the wrong site.  Please do not send students to interactivepython.org any more.
