### ISSUE TITLE
Casting Error between double and int

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/RunestoneComponents#550]
Error reported in course PCHS-APCS on page VariablePractice by user ahan mspetersclasssmarty@gmail.com
In the last question with chicken wings, the code tries to set a "int num" with two double numbers divided by each other. This gives a compile time error.

**Comment by ericsonga** [comment]
I have fixed this, but it hasn't been updated on the server yet.  Brad can you update the Java Review ebook when you get a chance?

**Comment by irunestone** [comment]
Thats what the Jenkins server is for….  Do you monitor the status of your builds?  If you’ve committed then the build there must be failing for some reason.

**Comment by ericsonga** [comment]
Can you walk me through this again?  I haven't ever actually done it since you originally set it up and could use a review.  Perhaps after I turn in my dissertation on Feb 19th?
