### ISSUE TITLE
Assignments wont show up

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/RunestoneComponents#573]
Error reported in course javaAtTheRanch on page https://runestone.academy/runestone/assignments/chooseAssignment.html by user harshparmar harshparmarzw@gmail.com
in the assignment tab nothing shows up but in the progress menu, it shows that its there and I haven't done it.

**Comment by bnmnetp** [comment]
Resolved.   You must remember to check the box that makes the assignment visible to students.
