### ISSUE TITLE
Video will not play in "Java Review for The AP CS A Exam Book"

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/RunestoneComponents#575]
Error reported in course DHS_AP_CS_A on page https://runestone.academy/runestone/static/DHS_AP_CS_A/OOBasics/objectObasics.html by user MrFoster pfoster@pasadenaisd.org
Videos do not run in the “Java Review for The AP CS A Exam” book, but they do work for the “How to Think like a computer scientist” book. 
I have been using “How to Think Like a Computer Scientist: Interactive Edition” for several months and have not had any issues playing the videos.
I recently started to use the “Java Review for the AP CS A Exam”. When I tried to play the videos in the “11.1. Object-Oriented Programming Concepts” section they would not play. The play and pause button do toggle but the video never starts. I have tried it using Chrome, IE, Firefox, and MS Edge. I tried to play at least 4 different videos with the same result.
In Chrome, there was an option to download the videos but, when I tried it I received a “Failed – Network error”. I also tried to download the inheritance.mov, the introToAnts.mov, and the polymorphism.mov and each gave me the “Failed Network error”. I was able to download the activecodelens.mov from the “How to Think like a computer scientist: Interactive Edition”.
 I contacted our district network support and they also received the same error. The network support team tested it both inside and outside of our district network. 
Thanks For Your Help,

Mr. Philip Foster

**Comment by barbarer** [comment]
Is this still problem?  It seems to be working for me.
