### ISSUE TITLE
cannot login with facebook

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/RunestoneComponents#578]
Error reported in course thinkcspy on page index by user pzarv paulzarvpro@gmail.com
Since today 5/3/2018 I'm no more able to login with my FB account. I've signed up again at Runestone, but doing so I've lost my progress till now. Please help. Thank you

**Comment by bnmnetp** [comment]
I disabled registration on interactivepython.org in January 2018 with a message that people should register at https://runestone.academy  The license for social logins wtih Janrain expired and is too expensive to renew.  

Social logins raise additional privacy concerns, so I have no plans to reinstate that feature at this time.
