### ISSUE TITLE
More typos on Variable Mixed Up Code Review

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/RunestoneComponents#582]
Error reported in course JavaReview on page VariablePracticeParsons by user aMcc2018 andrewdmccarthy@yahoo.com
Alongside problem 6, problems 7, 9, and 10 state that the code includes an extra block when all blocks of code are used.

**Comment by ericsonga** [comment]
Now that the Parsons problems are adaptive the number of distractors can vary based on the user performance.  I changed it to say may include.
