### ISSUE TITLE
iPad Encoding Errors

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/RunestoneComponents#585]
Error reported in course cghsflCS on page compileTimeErrors by user rjohnpowers powers@cghsfl.org
My school has 1-to-1 iPads, and I would like for the students to be able to use the iPad to complete work in the book on this site. The problem that I have encountered though is when trying to do 2.4.1 Compile Time Error 1.

In the solution to fix the code, you need to enter a ", however when typing that on the iPad, it enters what I assume to be a smart quote and the compiler gives an unmappable character error.

Do you know how to fix this on the iPad's end? Or will they have to complete these sections on a computer?

**Comment by bnmnetp** [comment]
There is a setting on the iPad under keyboards to allow you to turn off smart quotes.  This will fix it.
