### ISSUE TITLE
video muted

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/RunestoneComponents#590]
Error reported in course FCHSIntro on page https://runestone.academy/runestone/static/FCHSIntro/SimplePythonData/Variables.html by user kmtsullivan k.sullivan@frassaticatholic.org
Chapter 2.4 Variables
Video is muted.  I click the "mute" symbol but it does not unmute.
I've seen this problem with other videos in this book (How to Think like a Computer Scientist), but others have played.

**Comment by bnmnetp** [comment]
fixed
