### ISSUE TITLE
CodeLens window truncated

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/RunestoneComponents#591]
Error reported in course FCHSIntro on page OperatorsandOperands by user kmtsullivan k.sullivan@frassaticatholic.org
On this page: https://runestone.academy/runestone/static/FCHSIntro/SimplePythonData/OperatorsandOperands.html

There is one CodeLens exercise.  The window is too short and the last line of code is not visible.

**Comment by bnmnetp** [comment]
I can't reproduce this one anywhere.
