### ISSUE TITLE
ClickableArea doesn't work in Timed

### ISSUE THREAD

**Issue by katieirenec** [RunestoneInteractive/RunestoneComponents#597]
I can't get clickablearea directives to work within a timed directive. I believe that the clickablearea isn't added to the RenderedQuestionArray because `if ($(tmpChild).is("[data-component=clickablearea]"))`  in `Timed.prototype.createRenderedQuestionArray` doesn't evaluate to True. 

Here is an example of what I'm trying to do:

    .. timed:: assess_P1C4_matchlabels
        :timelimit: 5
        :nofeedback:
        :fullwidth:
        .. clickablearea:: P1L2
           :question: Click on the code best decribed by "If the input is empty".
           :iscode:
    
           :click-incorrect:new_roster = enterCourseRoster():endclick:

           :click-correct:if length(new_roster) == 0::endclick:
               :click-incorrect:error(“Roster has no students!”):endclick:
           :click-incorrect:else:
               save(new_roster):endclick:

When I dig into the html, it seems that the clickablearea has a different format than other elements within a timed exam.

_clickablearea (not seen in timed):_

    <div data-component="clickablearea" class="runestone alert alert-warning" id="P1L2"   >
    <span data-question>Click on the code best decribed by "If the input is empty".</span><pre>
    <span data-incorrect>new_roster = enterCourseRoster()</span>
    <span data-correct>if length(new_roster) == 0:</span>
    <span data-incorrect>error(“Roster has no students!”)</span>
    <span data-incorrect>else:
    save(new_roster)</span></pre>
    </div>

_multiplechoice (seen in timed):_

    <div class="runestone alert alert-warning">
    <ul data-component="multiplechoice" data-multipleanswers="false"  id="posttest_P1_C4_FillIn_2__">
    Q-1: Which code should go in ____2____?
    <li data-component="answer"  id="posttest_P1_C4_FillIn_2___opt_a">roster > 0</li><li data-component="feedback" id="posttest_P1_C4_FillIn_2___opt_a"></li>
    <li data-component="answer" data-correct id="posttest_P1_C4_FillIn_2___opt_b">error("The roster must have students!")</li><li data-component="feedback" id="posttest_P1_C4_FillIn_2___opt_b"></li>
    <li data-component="answer"  id="posttest_P1_C4_FillIn_2___opt_c">error("The roster has too many students!")</li><li data-component="feedback" id="posttest_P1_C4_FillIn_2___opt_c"></li>
    <li data-component="answer"  id="posttest_P1_C4_FillIn_2___opt_d">enterCourseRoster()</li><li data-component="feedback" id="posttest_P1_C4_FillIn_2___opt_d"></li>
    <li data-component="answer"  id="posttest_P1_C4_FillIn_2___opt_e">length(bio_course) == 0</li>
    <li data-component="feedback" id="posttest_P1_C4_FillIn_2___opt_e"></li>

**Comment by bnmnetp** [comment]
My first thought is that you should try adding a blank line after :fullwidth: There needs to be a blank line separating the options of a directive and the body of a directive.

**Comment by katieirenec** [comment]
That's my bad -- for some reason I took out a newline when I pasted the example in. 

The problem still exists with the blank line after :fullwidth:.

**Comment by bnmnetp** [comment]
I just pushed a quick change to github that adds the proper outer runestone div around the clickablearea. That should do it, but let me know.

**Comment by katieirenec** [comment]
It works perfectly! Fantastic!! 🎉

**Comment by bnmnetp** [comment]
Great!  Its nice when its an easy fix!
