### ISSUE TITLE
No way to set scratch activecode options

### ISSUE THREAD

**Issue by DaveParillo** [RunestoneInteractive/RunestoneComponents#600]
The scratch active code is a great feature for ad hoc programming, but
it would be nice, if in my c++ book it could permit c++11 syntax.

Since the default jobe compiler settings are c++98, most c++11 specific syntax fails.

It should be possible to set compilerargs, interpresterargs or stdin.

**Comment by bnmnetp** [comment]
This should be doable in the same way we allow someone to configure the default language in pavement.py by adding ``default_ac_lang`` to template_args  we can add options for compilerargs and interpreterargs and store them in the eBookConfig object in layout.html as well.

**Comment by bnmnetp** [comment]
this is done.
