### ISSUE TITLE
just a typo

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/RunestoneComponents#611]
Error reported in course thinkcspy on page OrderofOperations by user PancakeDave13 dakawa.kawa@gmail.com
"Multiplication and both division operators have the same precedence"
(word "both" is out of place)

**Comment by DaveParillo** [comment]
Sounds like @PancakeDave13 does not know Python has 2 different division operators.

Since this is an introduction they are correct: perhaps the brevity is misplaced.
Consider
> The multiplication, division, and floor division operators all have the same precedence.
