### ISSUE TITLE
Finish Exam button not visible on some browsers

### ISSUE THREAD

**Issue by katieirenec** [RunestoneInteractive/RunestoneComponents#618]
Opacity of the "Finish Exam" button on timed exam directive varies on different browsers. While it's highly visible on Safari, it is difficult to see on Firefox and the background is completely invisible on Chrome.

Safari:
![safari](https://user-images.githubusercontent.com/3497707/42196079-da08fdb8-7e30-11e8-9018-d2b4d3b8e0fc.png)
Firefox:
![firefox](https://user-images.githubusercontent.com/3497707/42196080-da279cb4-7e30-11e8-804f-aec5c08f6f29.png)
Chrome:
![chrome](https://user-images.githubusercontent.com/3497707/42196081-da449418-7e30-11e8-9d99-dd9d0848dd82.png)

**Comment by bnmnetp** [comment]
Ugh, I have a feeling this must be because different browsers deal with the accessibility coloring differently.  But thats just a guess.  Otherwise why would the same CSS show up so differently on different browsers??

**Comment by bnmnetp** [comment]
Of course I could be wrong.  It seems that something is trying to set the background color of the button in chrome to something called ButtonFace, which my brief research says should be #f0f0f0
Not sure why chrome is coloring it white.
