### ISSUE TITLE
add audio tour to overview.rst

### ISSUE THREAD

**Issue by ericsonga** [RunestoneInteractive/RunestoneComponents#62]
If the activecode supports audio tours then add an example to the overview.rst to show that.

**Comment by bnmnetp** [comment]
Yes, audio tours work in the new implementation.

**Comment by bnmnetp** [comment]
@ericsonga as I was adding an audio tour to the overview in the project template, I ran into a problem in that the source paths for the audio as well as the image files are hardcoded to look in ``../_static/...``  This is ok in the books where each chapter is in a subdirectory and `_static` lives above that subdirectory, but it does not work well for overview or other smaller documents that are not organized into subdirectories.

**Comment by bnmnetp** [comment]
OK, I found a workaround where I can have a single backup location for the audio/image files.  But this doesn't really fix the true problem.  the overview in the project template contains a working audio tour example now.
