### ISSUE TITLE
The usageassignment directive does not function

### ISSUE THREAD

**Issue by DaveParillo** [RunestoneInteractive/RunestoneComponents#626]
Is this directive intended for use? But this may simply be operator error on my part.

I could not find a book on Runestone Academy currently using it.

This directive appears to be a work in progress:

- Throws error on build:
   > Error in "usageassignment" directive:
   > no content permitted.

   even when no content area exists.
- No docs or unit tests
- The only example says 'this is kind of a hack'. twice.
- The 'hacks' are for section ID's and assignment types: numbers which are not documented anywhere.

So even if the build error was fixed, it's not clear how anyone would use this directive or what it does.

The source code indicates that this doesn't render any HTML, it `just creates an assignment object, with deadlines, etc.`.

**Comment by bnmnetp** [comment]
@presnick do you still use this?  Should we remove this directive now?

**Comment by presnick** [comment]
Yes, it's OK with me to remove it now. I think @aerenchyma was the last person using it, but I think she has also switched over to using the assignments interface. She can correct me if I'm wrong.
