### ISSUE TITLE
Error 404

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/RunestoneComponents#640]
Error reported in course JavaLBHS on page runClass by user cdenton cdenton@lbusd.org
Every time I try to run the active code I receive this message: 

"A server error occurred: 404 Not Found"

I have tried running many different active code -- places in several different chapters.  I am not sure what to do?

THanks!
Carrie Denton

**Comment by bnmnetp** [comment]
rebuild fixed the error.
