### ISSUE TITLE
grading by section?

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/RunestoneComponents#655]
Error reported in course smhs on page https://runestone.academy/runestone/static/smhs/index.html by user dleesmusd dlee@smusd.us
When I go to "Instructor's Page -> Assignments", I'm trying to grade my class' assigned problems, but don't see the option of selecting a section. 

Instead, when I select a student and chapter, I don't see the problems that I've assigned listed anywhere. I'm wondering if this functionality been coded yet or if I'm doing something wrong?

I want to be able to select a section and see all of the assignments I've assigned for each student as it was on the interactivepython platform.

Best regards, 

- Daniel

**Comment by bnmnetp** [comment]
The interface on Runestone.academy is a very different design from the old interface on interactivepython.org.

Have you created the assignment using the assignments tab?

If so then you should select assignment in the first column, and the problem in the second column, then you can see all of your students in the third column.  

Brad

**Comment by dlee-smhs** [comment]
Thanks for the response Brad!

I can see how to access the assignments now. 

With the new interface, am I able to see assignments by section, or is it expected that instructors create separate courses for each class? 

If it's the latter, then a follow up question would be, is there a way to create a copy of a course?

**Comment by dlee-smhs** [comment]
I believe the usefulness is dependent on how the instructor's grading system is set up. 

For high school teachers, each class is grouped in a Gradebook application and students are alphabetized by last name. Using the system as is requires the teacher to look for each student from their Gradebook on runestone in what could be a long list. This is time wasted. 

Also, it would be ideal if teachers could select the section, the assignment name, and the student name. Then the system should list all the activecode boxes associated with that assignment. This would also save time.

As the system stands, it is more time efficient for the high school teacher to have the students open up their assignments and grade them by looking at their screens which takes up instructional time unnecessarily.
