### ISSUE TITLE
Invalid login

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/RunestoneComponents#657]
Error reported in course CS152-Cigas-Online on page index by user theriggs 1653424@park.edu or I prefer theriggs35@yahoo.com
I am logged in on my pc and I can change my pw and access all of the content on my pc no problem, but when i try to login on my laptop or cell phone I encounter the message invalid login. I am using my login name not my email and I have tried changing my pw and logging in, but it still does not work.

**Comment by bnmnetp** [comment]
I think you are confusing two websites.  My guess is that on your PC you are accessing interactivepython.org instead of runestone.academy
