### ISSUE TITLE
not authorized/Insufficient privileges

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/RunestoneComponents#659]
Error reported in course JavaReview on page https://runestone.academy/runestone/default/user/not_authorized by user detrickd detrickd@warrenhills.org
I have used Runestone with my APCS A classes for a couple of years, but now when I go to the instructor page it says unauthorized / insufficient privileges.   Please advise.  School starts 8/29 and I decided to not use a physical textbook this year.   Thanks  Daryl

**Comment by bnmnetp** [comment]
You re registered for the JavaReview course and you are not authorized to be an instructor of that course.  If you want to create a new course you should have selected that option when you registered, or if you had another class that you were an instructor for you could choose create course  from the instructors page, or if you click ont eh create course link at the top of the course selection page if you are registered for more than one course.

In any case the link below should allow you to create a course.

https://runestone.academy/runestone/designer/index
