### ISSUE TITLE
incorrect word

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/RunestoneComponents#662]
Error reported in course Python on page OrderofOperations by user Krooko jaeung@vt.edu
"So in the expression 6-3+2, the subtraction happens first, yielding 3. "

it should be 5?

**Comment by schweinsbergs** [comment]
If you continue reading: " So in the expression 6-3+2, the subtraction happens first, yielding 3. We then add 2 to get the result 5." It seems to be fine. I believe this issue can be closed.
