### ISSUE TITLE
Parsons problems not working if you have code segments and a distractor

### ISSUE THREAD

**Issue by ericsonga** [RunestoneInteractive/RunestoneComponents#67]
This example didn't work 
.. parsonsprob:: 2_swap

   The following has the correct code to 'swap' the values in x and y (so that x ends up with y's initial value and y ends up with x's initial value), but the code is mixed up and contains one or more extra statements.  Drag the needed blocks from the left into the correct order on the right. Check your solution by clicking on the <i>Check Me</i> button.  You will be told if any of the blocks are in the wrong order or if you need to remove one or more blocks.
   -----
   int x = 3;
   int y = 5;
   int temp = 0;
   =====
   temp = x;
   =====
   x = y;
   =====
   y = temp;
   =====
   y = x; #distractor

**Comment by bnmnetp** [comment]
Barb, are you sure you have the absolute latest components from the github repository?

I just build this example and it works great for me.
