### ISSUE TITLE
Problem logging in with different devices.

### ISSUE THREAD

**Issue by tajkau** [RunestoneInteractive/RunestoneComponents#671]
I’m using the same login details on three devices. I can access the book through my phone and iPad but not my MacBook. I’ve tried resetting the password but nothing would work. I even tried resetting the password and then accessing the email from my laptop; I was able to change the password and access it through the Mac but once I came back to it later on it wouldn’t work again. Each time it says ‘invalid login’ and if I try resetting the password it says ‘invalid username’. I’ve also tried after deleting the cache, and also logging in through a different browser. It’s just weird.

**Comment by bnmnetp** [comment]
please make sure you are:

1.  On runestone.academy and not interactivepython.org
2.  Using your username to login and not your email address... they are different.

**Comment by tajkau** [comment]
I did trust me. I did both things correctly. I’m accessing the following link: 

https://dev.runestone.academy/runestone/default/user/login?_next=/runestone/default/index
(most times I access it from the link on my professor’s webpage). 

And I’m definitely not using my email, otherwise I would not be able to access the book through my other devices.
