### ISSUE TITLE
non-existant video tasks

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/RunestoneComponents#676]
Error reported in course brekke on page assignments by user haugrud haugrudm@mnstate.edu
Brad, my colleague's course is built from my msumoorhead base course. The videos are listed as two tasks when making an assignment. (see the activity 2 assignment). The reading assignments are most affected by this problem since it is not apparent that there are duplicates when making the assignment. Please remove the (video) tasks that are not a part of the course. We had a similar problem about a year ago with duplicate tasks and you were able to fix it. This same issue also affects the haugrud and ficek courses (all built from the msumoorhead base course).

**Comment by bnmnetp** [comment]
side effect of moving to youtube for video hosting.  Should be good now.
