### ISSUE TITLE
Chp 3.6 import pythonds

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/RunestoneComponents#678]
Error reported in course CPAVTS_Programming_2 on page SimpleBalancedParentheses by user jlamertina JLamertina@usa.com
The default sample code in section 3.6 begins with:
"from pythonds.basic.stack import stack"
But this dos not work, even after using pip:
"pip3 install pythonds".
The error is:
"ImportError: No module named pythonds on line 1"
How can this be fixed?

**Comment by bnmnetp** [comment]
Fixed
