### ISSUE TITLE
luther.jpg failed to load in grading interface

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/RunestoneComponents#686]
Error reported in course cs_python on page https://runestone.academy/runestone/admin/grading by user normprokup norm@college-prep.org
I am trying to grade ex_7_15, 16, 17, and 18.  However, the image "luther.jpg" does not load, so I'm not able to grade these exercises.  Is there a workaround, or should I have my students download Pillow and redo the exercises outside of Runestone?

**Comment by bnmnetp** [comment]
The real solution should be to make a simple image directive that stores the URL in a way that the Image loader can get to.  Or to have the image loader retry.  

If "luther.jpg does not work then have image use eBookConfig information to construct the link to _static/image

This means we should be careful about having the id of the image embedded in the page match the file name.
