### ISSUE TITLE
Reading assignments - some more inaccurate activity counts

### ISSUE THREAD

**Issue by cigas** [RunestoneInteractive/RunestoneComponents#698]
It seems that some page activity counts are incorrect on reading assignments, which then affects the default number of required components to complete to receive credit. This is especially true for 
Simple Python Data: Order of Operations, which says there are 10 components, but I only count 7 on the page, so at least in my class last term, it was impossible for students to achieve a score of 8 and thus get credit for this item.
![activity](https://user-images.githubusercontent.com/11619455/47937512-fa4fa700-deae-11e8-891c-eec652109cfa.PNG)

And another one from Chapter 1
![anotherwrongvalue](https://user-images.githubusercontent.com/11619455/48236851-a8fd5700-e389-11e8-9c78-1bd4d0d550c4.PNG)

**Comment by bnmnetp** [comment]
Thanks, for the report.  I will look into it in more detail.  I think what happens is that we miss deleting an old item if we change the id (which we should not do).

In any case, you have control over the number required.  So if there is only seven **you** can set the # required to 7 or 6 or 5 in order for your students to get the credit.  You can even do that now and regrade.

Brad

**Comment by cigas** [comment]
Adjusting the # required and regrading is what we've done. Finding the # to adjust...that's the challenge.
