### ISSUE TITLE
timed exams - if complete should show previous answer automatically on all questions

### ISSUE THREAD

**Issue by ericsonga** [RunestoneInteractive/RunestoneComponents#70]
It currently only shows the feedback on the first question in the timed exam.  It should show the feedback for all questions.   I would also prefer it to do so automatically, rather than wait till you click on the Start button.

**Comment by bnmnetp** [comment]
Fixed.   I broke this last friday while doing something that I thought was pretty harmless. The timed exam stuff adds so many more permutations to test.  We really need some kind of automated testing to catch these regressions.
