### ISSUE TITLE
Multiple attempt

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/RunestoneComponents#707]
Error reported in course APCSP-B1-18-19 on page https://runestone.academy/runestone/default/reportabug by user skurnaz skurnaz@harmonytx.org
Students are able make multiple attempts and it makes my job harder as an instructor. Is it possible to make it just one attempt for each questions or multiple attempts but a warning after the first attempt which "says just you can see the explanation for other options but you will not be able to get full score for this item!"

And in the outo-grade section it does grade the first attempts.

Thank you for designing this website it looks like it will help me so much.

**Comment by bnmnetp** [comment]
You have control over how you want to have these graded.  If you select first answer when you are creating your assignment then the students first answer will be used and subsequent answers will be ignored.  This allows students to answer the question but still explore other answers without making your job harder.  If you select best answer then you are allowing students to keep guessing until they get it right.
