### ISSUE TITLE
Code NotSaving

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/RunestoneComponents#708]
Error reported in course whsap2018dt on page https://runestone.academy/runestone/static/whsap2018dt/VariableBasics/VariablePractice.html by user 100006751 100006751@student.guhsdaz.org
I have tried to submit my answers for this assignment over 3 times now, and it has not been saving. I've even placed all my answers on a text document because I've had to restart my work two times. Every time, I hit "save & run" for all activities. Lastly, I select "mark as completed" but when I return to the assignment shortly afterwards, none of my code has saved.

**Comment by yarikoptic** [comment]
could be related to https://github.com/RunestoneInteractive/RunestoneServer/issues/1179?

**Comment by bnmnetp** [comment]
No, this was a different issue that was due to some real overloading on the site that day.
