### ISSUE TITLE
timed exams - strange behavior

### ISSUE THREAD

**Issue by ericsonga** [RunestoneInteractive/RunestoneComponents#72]
I took a timed exam and it was counting down the time.  I hit the submit answers button and it didn't give me the results and it changed to displaying the time it took me to complete the exam.  It also is still letting me change the answers on all but the first question.

**Comment by bnmnetp** [comment]
I think this was probably related to #70.  Let me know if you still see this behavior after you grab my fix from the repository.

PS, in case you don't know you can clear your localStorage and reset all the questions and exams on a page using ``localStorage.clear()`` from the javascript console.

**Comment by bnmnetp** [comment]
I'm guessing this one was fixed along with the fix for #70.  If you see it again, we can reopen.
