### ISSUE TITLE
Error: Runestone build failed: *** has_emperor mode detected (fd: 7) *** 

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/RunestoneComponents#736]
Error reported in course CSC110 on page https://runestone.academy/runestone/admin/assignments#component-preview by user dellingston de@uw.edu
This bug appeared after my last rebuild a few days ago, before that everything was working fine. This error message "Error: Runestone build failed: *** has_emperor mode detected (fd: 7) *** unable to load configuration from runestone " pops up when I try to write my own activecode homework problems. I cannot generate & view HTML, cannot save problems.  Thank you!

**Comment by bjones1** [comment]
Wow. I wouldn't have expected that. I assume this is running nginx? Is there any easy way to set up a test server so I could play with a workaround? Based on [SO](https://stackoverflow.com/questions/18014122/how-to-get-python-interpreter-path-in-uwsgi-process#comment26371589_18021303), the [uwsgi.opt](https://uwsgi-docs.readthedocs.io/en/latest/PythonModule.html#uwsgi.opt) [home](https://uwsgi-docs.readthedocs.io/en/latest/Options.html#home) option has the correct value for `sys.executable`., I'm guessing something like this:

``` Python
    try:
        import uwsgi
        sys_executable = uwsgi.opt['home']
    except:
        sys_executable = sys.executable
```

**Comment by bnmnetp** [comment]
nginx acts as a reverse proxy and uwsgi is the wsgi container for the web2py application.

**Comment by bjones1** [comment]
Is the setup described at http://web2py.com/books/default/chapter/29/13/deployment-recipes#Nginx close enough to what you're running that I could reproduce this? Or is what you're doing totally different?

**Comment by bnmnetp** [comment]
Yes, that is very close to my setup.
