### ISSUE TITLE
input vrs raw_input

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/RunestoneComponents#766]
Error reported in course learning on page Input by user smteichmer smteichmer@lcmail.lcsc.edu
I'm using this course beside a computer science course to help reinforce what I am learning in Python. Our class is using Python 2.7.15 version. In this version input values are int or float, and raw_input values are str. This seems to be different than what is taught in this section.

**Comment by bnmnetp** [comment]
Python 2.7 will be done in 2020.  I would suggest you use Python3 in your course rather than 2.
