### ISSUE TITLE
Can not add students to classes

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/RunestoneComponents#767]
Error reported in course DHS_AP_CS_A on page Admin by user MrFoster pfoster@pasadenaisd.org
I cannot find the information to give to my students so that they can join my class.

**Comment by bnmnetp** [comment]
All you need to do is give your students the ID of the class you created -- DHS_AP_CS_A in your case.  Then when the students register they use that name and they are in your class.  

I would  suggest you take a look at some of the help videos I created for new instructors.  You will find them on the instructors page under the Help/Documentation tab.
