### ISSUE TITLE
Exercises created via the 'write' button won't display in an assignment

### ISSUE THREAD

**Issue by cigas** [RunestoneInteractive/RunestoneComponents#781]
When I create a new exercise by 
a) Editing an existing exercise
b) Copying the description and unit tests 
c) Opening a new exercise with the Write button
d) Pasting into the new exercise and changing the Activecode Identifier
The exercise gets created, but it won't appear when I try to add it to an assignment.

However, when I create a new exercise by just
a) Editing an existing exercise
b) Changing the Activecode Identifier

Everything seems to work as expected. See the following screencast for a demonstration.
https://drive.google.com/file/d/1JneTo-oS3rhkskW0vDN3yU_FnukJrSlX/view?usp=sharing

**Comment by bnmnetp** [comment]
Hmmm, I just did a workshop last Saturday where we created exercises from scratch using the Write button and they were available in the assignment.  What book and chapter are you trying to save them to?  That may be the issue.

**Comment by cigas** [comment]
ThinkCSPY, Chapter 6 on Functions

**Comment by bnmnetp** [comment]
You certainly have the knack for helping find the problems, and I'm grateful for your problem reports.  In this case the problem is that the file containing the Exercises for the functions chapter is named incorrectly!

**Comment by bnmnetp** [comment]
Its an easy fix, so I'll make it and push it out this afternoon sometime.

**Comment by bnmnetp** [comment]
Fix deployed.  You should rebuild your test class and things should work.

**Comment by cigas** [comment]
I rebuilt, and yes, all the exercises that I created with the Write option display in an assignment.
BUT...
All the exercises that I created just by editing an old assignment now do NOT display. Unfortunately, that's how I created the ones I just assigned to my class.
Were there two different files of exercises? Is there an easy way to combine the two?

**Comment by bnmnetp** [comment]
If you can provide me with a list of the unique ids for those that are not showing up I'll see if I can poke at them in the database and get them to show up again.

**Comment by cigas** [comment]
These were used in the class I rebuilt, CS152-Cigas-Spring-2019, Assignment Unit 3 - Practice
CS152_skipForward
CS152_skipTo
CS152_perimeter
CS152_circle_rad

But what's really, really strange is that ex_5_13 disappeared from an assignment in another class that I did not rebuild and anyway, it's not my exercise. That class is CS152HOSP2019 in Assignment Day 11 - In class exercises. However, my two exercises are still there!?!

**Comment by bnmnetp** [comment]
I moved the questions from above into the proper subchapter in the database.  So, check and make sure they are now visible in your test course.

If that works, and then you rebuild CS152HOSP2019 then everything should be consistent again there as well.

This is all database driven, based on the assumption that user entered exercises are stored in a subchapter called Exercises.  The subchapter name is derived from the filename in the original source for the book, not the title you see on the page.  In the functions chapter the filename was thinkcspyExercises, and I didn't catch that.

**Comment by cigas** [comment]
Thanks. Everything worked like you said. Now there's just two more of my questions to move please:
CS152_sumBetween_loop
CS152_sumBetween_sumTo

**Comment by bnmnetp** [comment]
done.

**Comment by cigas** [comment]
That worked, so I'm all set ... for this chapter.

Thanks for spending your afternoon on this.

**Comment by bnmnetp** [comment]
Thanks for your help.
