### ISSUE TITLE
difficulties to login in Runestone Academy

### ISSUE THREAD

**Issue by Antonio789RabeloAGAR** [RunestoneInteractive/RunestoneComponents#785]
Good morning.
I am trying to create an account, to log in, in the Runestone Academy, to register for the course, "Think like a computer Scientist: Interactive edition, Python 3" and when it asks to e-mail the site to get a userrname, I got an answer of INVALID E-MAIL. There's nothing wrong with my e-mail. Can you help me to login for this course?
Best regards
Antônio Guilherme de Assis Rabelo.

**Comment by bnmnetp** [comment]
The email my username link is for recovering your username if you forget it, but remember your email.  Please use the blue "Sign Up" button at the top of the page to register.  Or follow this link:  https://runestone.academy/runestone/default/user/register

**Comment by Antonio789RabeloAGAR** [comment]
Good morning, Bradley.
Thank you for the help. Unfortunatelly the blue "sign up" button didn't
work nor the link you sent to me. I type the name of the course but when I
try to sign up appears this message:

   - course_id: Unknown course name. Please see your instructor. (I don't
   have an instructor untill now).
   - It seems that I also need a username for that.
   - Can I ask you for the right way to conclude the register? I really
   would appreciate to take this course.
   - Thank you
   - Antônio Guilherme de Assis Rabelo.


Em qua, 13 de mar de 2019 às 16:52, Bradley Miller <notifications@github.com>
escreveu:

**Comment by bnmnetp** [comment]
what value are you using for course_id ?  If you are not enrolled in a class in a school, then the value you should use is thinkcspy as suggested by the hint in the box.
