### ISSUE TITLE
Trying to build the APCS A and get a not found 404 error

### ISSUE THREAD

**Issue by johnchapin-lcps** [RunestoneInteractive/RunestoneComponents#787]
Class Name:  APCS-2018
Teacher email:  john.chapin@lcps.org
Course Name:  AP CS A Java Review, by Barbara Ericson

I have tried rebuilding and still get a 404 not found error

**Comment by bnmnetp** [comment]
Hi John,

I emailed you, but for posterity.  There was an error introduced into the javareview book that caused the build to fail.  This is fixed now, and you should be able to either rebuild the course or make a new one that will succeed.
