### ISSUE TITLE
AP CS A Exam Not Working

### ISSUE THREAD

**Issue by MarianaS1** [RunestoneInteractive/RunestoneComponents#797]
[errors.txt](https://github.com/RunestoneInteractive/RunestoneServer/files/3085639/errors.txt)
The Practice Exam 1 for the AP CS A Exam gives me and other students the answers to all the questions in the test as soon as we click "Start". The test becomes very useless if we are seeing the answers as soon as we try to start it. The timer goes from "45:00" straight to "0:00". I have attached the console messages from my browser. We tried it on edge and got the same results. We are using Google Chrome  Version 73.0.3683.103 (Official Build) (64-bit) and it has the same problems. 
We tried clearing the cache already, as suggested on your website, but it did not help. Thank you for your help. I hope you can fix this problem soon so that we can take advantage of your practice exams before our AP test which is on May 17th, 2019.

**Comment by bnmnetp** [comment]
Those messages make more questions than answers.

We don't have anything called like.php in our system.  

Are these common computers with individual logins or are they open to anyone who sits down?

If so are they running something like deep freeze?  
Are they rebooted regularly?  
Is there some other system in place to clear the history and cache of the browser?
What kind of computers are they?  Windows? Mac?
What version of Chrome are they running?

Does your school have any special software installed to block certain sites or kinds of activity?

I went to your course from Chrome on my own compute, and, unsurprisingly,  the exam was ready for me to take by pressing the start button.

I'm not trying to pass the buck here, but there are 125 schools currently using this same book on Runestone and I think I would be hearing more complaining if this was a major problem in our software.  

The fact that is is happening to some but not all students is even more mystifying.  Unless your students are not being honest and have been trying to look ahead at the questions.  That would certainly be one explanation.  

I like to think most of them are honest and would like to get to the bottom of this and fix it.  But that is super hard when I cannot reproduce the problem myself.
