### ISSUE TITLE
Instructor name Mixed up with user name

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/RunestoneComponents#800]
Error reported in course JavaReview on page https://runestone.academy/runestone/static/JavaReview/index.html by user rlaksnarain ram@samvidusa.net
When I login as instructor with the above user name and try to go to instructor page to set assignment, the username changes to my email id and shows as not authorized.
Ram

**Comment by bnmnetp** [comment]
You are not allowed to be an instructor for the JavaReview course.  Only the admins for Runestone.academy can be instructors in courses that are open to anyone.

**Comment by bnmnetp** [comment]
fixed.
