### ISSUE TITLE
Student login shows up a tab to create a course

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/RunestoneComponents#801]
Error reported in course Merit_Java on page https://runestone.academy/runestone/static/Merit_Java/index.html by user merit_student rlaks1956@gmail.com
When I log in as a student, the drop down shows change to instructor page.  When clicked takes me to the page with two courses. when clicked on merit java course, it takes me to the course.  But I also see a tab with Create a Course for the student.  This is confusing.  Can the student create a course?

**Comment by bnmnetp** [comment]
Yes.  Just as you were a 'student' when you first registered... Anyone can create a course and become an instructor **for the course they create.**   I'm not sure how to automatically go about verifying that someone who claims to be an instructor really is an instructor.  But I'm certainly open to suggestions that don't involve human (read me) interaction.

That said, I can understand the argument that the link in the dropdown should not be there,  but its never been a high enough priority to spend time to fix.  I think I have an easy solution, so stay tuned.

**Comment by bnmnetp** [comment]
fixed
