### ISSUE TITLE
None displaying instead of course name

### ISSUE THREAD

**Issue by cigas** [RunestoneInteractive/RunestoneComponents#802]
I rebuilt the course CS152HOSP2019. When I visit a page, now it shows 'None' instead of the course name. Formerly it displayed the book name. 
![NoCourseName](https://user-images.githubusercontent.com/11619455/56672710-84b5de00-667c-11e9-8c2c-6d3431e87bc3.PNG)

**Comment by bnmnetp** [comment]
Grrrr.... sorry,  Testing a better fix now.

**Comment by bnmnetp** [comment]
Try your build again. It is working on my test courses.

**Comment by cigas** [comment]
That did it. Thanks.
