### ISSUE TITLE
Using alternative email because my email address exists but can't login.

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/RunestoneComponents#803]
Error reported in course fopp on page /runestone/mygroup/initiateGroup by user brindha_lekshmisaran brindhasaran@gmail.com
Hi,
I had registered using brindha.lekshmisaran@gmail.com
But when I tried to login, it gave error. So, I attempted to register again, but the email value already exists; but it would let me use that email in "forgot password" form. 

So, I have now registered using my older email (that I rarely use now); brindhasaran@gmail.com 
Using this alternative email, I'm able to login and use your site and content.

I would like to update my profile to my current email brindha.lekshmisaran@gmail.com
I am unable to because this email is already in your database (though I can't login with that). 

Can you please help me resolve this?

Kind regards,
Brindha

**Comment by bnmnetp** [comment]
There are two buttons for you to use to resolve this issue.

First, you need to remember that your username is not your email address.
So, if you cannot remember your username then you can use the "email my username" button.  If you do remember your username then you can reset your password with the Lost Password button.
