### ISSUE TITLE
How I can read the Spanish's course?

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/RunestoneComponents#804]
Error reported in course pythonds on page toctree by user AvionZapador simonjejeje@gmail.com
I can not choose the course in Spanish or I do not know how to access (for example to 
http://interactivepython.org/runestone/static/pythoned/Introduction/ParaComenzar.html) when I login.

**Comment by bnmnetp** [comment]
Hola,

The Spanish course is now available on https://runestone.academy  When you register you should use the course name of pythoned   If you don’t want to register you can still read the spanish edition at

https://runestone.academy/runestone/static/pythoned/index.html
