### ISSUE TITLE
merge sort

### ISSUE THREAD

**Issue by lifei023** [RunestoneInteractive/RunestoneComponents#808]
Hello,

I try to implement the sample code of the the merge sort algorithm myself and find that it doesn't work as expected in certain situation. For example, if I use it to sort the list [10,9,8,7,6,5,4,3,2,1] then the output would be [1,1,1,1,1,1,1,1,1,1]

**Comment by lifei023** [comment]
Solved. Just add .copy() when creating the lefthalf and righthalf. Hope this helps.

**Comment by lifei023** [comment]
> Hello,
> 
> I try to implement the sample code of the the merge sort algorithm myself and find that it doesn't work as expected in certain situation. For example, if I use it to sort the list [10,9,8,7,6,5,4,3,2,1] then the output would be [1,1,1,1,1,1,1,1,1,1]

My bad. I use this function on a numpy array and forget that the slice of a numpy array is just a view of the array rather than its copy. That's why the .copy() method works.

**Comment by bnmnetp** [comment]
Yeah, we definitely don't teach numpy in that book.
