### ISSUE TITLE
Pictures aren't showing up as answers to multiple choice questions in the timed exam

### ISSUE THREAD

**Issue by ericsonga** [RunestoneInteractive/RunestoneComponents#81]
.. mchoice:: e5a6_5
       :answer_a: <img src="../_static/checka.png" alt="Shorter line to south and then longer line to east" width="300">
       :answer_b: <img src="../_static/checkb.png" alt="Longer line to south and then shorter line to east" width="300">
       :answer_c: <img src="../_static/checkc.png" alt="Longer line to north and then shorter line to east" width="300">
       :answer_d: <img src="../_static/checkd.png" alt="Shorter line to north and then longer line to east" width="300">
       :correct: d
       :feedback_a: This would be true if it was right first and then left.
       :feedback_b: This would be true if it was right first and then left and if the first forward was 150 and the last was 75.
       :feedback_c: This would be true if it was the shorter line to the north and the longer to the east.
       :feedback_d: This will draw the shorter line to the north and then the longer one to the east.

       Which picture would the following code produce?
   
       ::
       
          from turtle import * 
          space = Screen() 
          sue = Turtle()
          sue.left(90)
          sue.forward(75)
          sue.right(90)
          sue.forward(150)

**Comment by bnmnetp** [comment]
The solution to this is to change ``.text`` to ``.html`` in two places in the mchoice.js file.  However, I want to make sure that this does not "break" other questions before I push that change.

**Comment by ericsonga** [comment]
Okay.

**Comment by bnmnetp** [comment]
I've checked most of the multiple choice in thinkcspy and all look good.  I pushed the change.
