### ISSUE TITLE
Make configuration updates to the layout.html and pavement.py file easier to distribute

### ISSUE THREAD

**Issue by bnmnetp** [RunestoneInteractive/RunestoneComponents#812]
After merging #805 

I think the toughest part of moving books to dynamic pages is going back to all the existing books and updating layout.html as well as pavement.py  Each book has its own history with that file and what is in the navbar etc... Its not an easy process to deal with when you add a new feature that requires something new to be added to eBookConfig and pavement.tmpl and the init process for a new book.

I wonder if there is a way to make it a little easier.... I'm thinking that we might be better off to do an 
```
{% include "ebookconfig.html" %}
```
Where the ebookconfig.html would come from a central location rather than having been forked to the book...

I'm also wondering if some of the pieces of the `template_args` part of pavement.py could be included from a central location...

What do you think @bjones1?

**Comment by bjones1** [comment]
Copying the template to every book created causes a lot of problems. IMHO, I'd like to remove this altogether! Include a Sphinx theme when installing RunestoneComponents then use that. Otherwise, any edits to the theme rarely get propagated to a built book.

Also, `pavement.py` has run amok with too many config options. It should be simplified! I'm in favor of eliminating vars / factoring them out.

**Comment by bnmnetp** [comment]
Lets think through a few big things before getting bogged down in details of config variables and templates...

1. It has always been a design goal that someone could use runestone to build a book that could be served as a static site with nothing but a vanilla web server serving up the pages.  I still think that is an important goal.

2. It seems worthwhile to preserve the option that a book could be built so that API calls from the Runestone components store data in SOME server.  Maybe as simple as a server that does nothing more than collect data into a useinfo table and spits out a CSV for an instructor.  It could be much more complicated than that also.  It doesn't seem to me there is anything wrong with keeping this ability intact. (authentication is the biggest stumbling block here...).

3. Now we have the dynamic pages model of which we are just at the beginning.  This has the advantage that as runestone.academy scales we don't need to keep buying more disks, it eliminates the slow and cumbersome build a book process, and it ensures that everyone is running the latest version of a book with all the bug fixes without needing to worry about it.  Good Stuff!  Thanks!
  * We could vastly simplify what happens when a page of a book loads because it is now entirely possible to eliminate the javascript code required to see if a user is logged in and all of the actions that follow.
  * We could simplify the process of restoring answers to questions
  * We can eliminate logging calls just to record page views
  * I'm sure there are more things we can do if we spend some time thinking it through.

4.  I would love to see further separation between serving books and the instructor interface.  I think they should  be two separate applications that happen to share a common database, and would have the nice property of keeping updates on separate paths and timelines.  The user base for #4 is also MUCH smaller.

I'm having a hard time letting go of number 2.  There is something elegant about that level of separation that I really like.  But I think it is mostly at odds with all of the good simplifications that we could make if we took number 3 to its logical ends.  It may take an adjustment period for me to let go.  There is one current proposal outstanding that relies on the functionality of 2, and if that falls through it will make it easier.  I'll know more about that in a couple weeks.

--------

OK, so here is the list of config variables in pavement.py that are used in the build process.

* login_required  - only needed if we keep 2
* loglevel - we only have two levels right now, so it is of dubious value
* default_ac_lang - Different books have different default languages and it makes sense to have a way to configure the default for the scratch activecodes
* basecourse - 
* course_title -- If we elminate 2 this can go
* python3 -- this can go no matter what, Python 2 is dead.
* dburl -- pretty sure this is not used anywhere
* jobe_server -- If we run our own JOBE server then we can probably eliminate these three
* proxy_uri_runs
* proxy_uri_files
* downloads_enabled - So, this is the first of the 'instructor preferences'
* enable_chatcodes- Not sure of the status of this project at U Mich, but it would be a great feature
* allow_pairs - This is an experimental feature that some instructors will want and others won't
* dynamic_pages - If we eliminate 2 then this is redundant with use_services
* use_services  - If we eliminate 2 this is redundant with dynamic_pages
* course_id -Needed no matter what
* appname 
* course_url  -- Not sure where or how this is used??

I don't agree that the variables have run amok.  Each was added for a good reason, and most still are serving a good purpose.  We are at a crossroads where a bunch of these could be eliminated.  Its a difference between a highly opinionated implementation and an implementation that allows for lots of choice.  I've always opted for more choice to try to make it work for more people in more situations.  I think thats a big difference between designing for Runestone.academy and designing for a single instructor/institution.

--------

I am much more ready to have a single layout.html that all books use as a default, so we would not copy a layout.html during `runestone init`  But I do think that some authors will want to customize either the theme or perhaps even the layout.  The layout is definitely ripe for some improvements!  This might be pretty easy to handle in the conf.py where we set the theme_path.

**Comment by bjones1** [comment]
Thanks for your thoughts! My comments:

1. I don't really understand what you mean:
    1. The ability to build and use an offline book that requires no web server whatsoever?
    2. The ability for the book to work with something like `runestone serve`?
    3. Something more complex than `runestone serve`, but simpler than the web2py app?
2. Again, I don't fully understand this point. Is there some spec I'm unaware of? This isn't https://github.com/RunestoneInteractive/RunestoneServer/wiki/RSE-0001, but something else, I'm assuming.
3. I'm in favor of pursing this path --involve both the server and the client in the creation of a richer, more interactive user experience.
    1. Dynamic problems (Paul mentioned this) -- write programs that can create a unique problem on every page load.
    2. Tutors / assistants -- use some AI to present the material a student is struggling with.
    3. All the improvements you mentioned.
4. Yes yes yes!!! This is a great idea!

In terms of config variables, I'd like to eliminate / simplify whatever is possible. Also, with dynamic book routing, a lot of config can be moved to the server -- I think it would be neat to make this a per-course option (perhaps in the `courses` table) instead of "baked in" at Sphinx build time.

**Comment by bnmnetp** [comment]
1. -- The ability for a book to work with something like `runestone serve`, or `github pages` or simply `python -m http.server` or drop the build folder into a subdirectory of any web server.  (of course runestone services are not supported when serving pages this way)

2. is essentially how it works today.

**Comment by bjones1** [comment]
1. To keep this ability, all we need is to create static pages, correct?
2. I'm still a bit fuzzy on this. If the spec for this is defined by how it's currently implemented, does that prevent us from implementing things in item 3? Perhaps we can talk more today in the hangout.
