### ISSUE TITLE
can't add course

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/RunestoneComponents#813]
Error reported in course Problem solving with Algorithms and Data Structures in Python on page https://runestone.academy/runestone/default/user/profile? by user beeman052 beeman052@gmail.com
I'm trying to add Problem solving with Algorithms and Data Structures in Python (this is the main reason I would like to use the site) and I don't seem capable of doing that, and I'm not sure if it's my fault (probably is) or something else, and I'd just like help getting it resolved. Thank you for taking the time to not only help me with this, but to provide this kind of content

**Comment by bnmnetp** [comment]
You are registered now, so it looks like you figured it out.
