### ISSUE TITLE
Pictures are still not showing up when part of answers for timed exams - getting <img tags>

### ISSUE THREAD

**Issue by ericsonga** [RunestoneInteractive/RunestoneComponents#82]
<img width="735" alt="screen shot 2015-07-31 at 10 04 36 pm" src="https://cloud.githubusercontent.com/assets/1844609/9020272/33133b58-37d0-11e5-803b-1fcad64bc3ab.png">

**Comment by bnmnetp** [comment]
Ugh, we should be able to be more clever about how to render the multiple choice question without having one version for timed questions and one for regular questions.  The code is 99% the same. :-(

Anyway its fixed for timed questions now too.
