### ISSUE TITLE
undefined message when accessing key that is not in the dictionary - Python

### ISSUE THREAD

**Issue by JuicySword** [RunestoneInteractive/RunestoneComponents#828]
When trying to access a key that is not in the dictionary, it returns "undefined" messages.
Here is a sample code you can try in somewhere [[Here](https://fopp.umsi.education/runestone/static/fopp/index.html)] that allow you to run Python code or use Scratch ActiveCode top right:
`dic = {"a":0,"b":1,"c":2}`
`print(dic['d'])`

**Comment by bnmnetp** [comment]
Thanks,

I've added some description and suggested solutions to the dev version of Runestone.
