### ISSUE TITLE
Wrong Answer to the Multiple Choice

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/RunestoneComponents#829]
Error reported in course pythonds on page TheBubbleSort by user navidpaya me@navidpaya.com
Hi
Not sure if I'm mistaken or not but worth checking. I believe the correct answer for the multiple choice at the end is C. There will be 3 passes:
1 - 19 moves all the way to the end
2 - 1 stays since it's less than 9
3 - 9 moves before 10

**Comment by bnmnetp** [comment]
Nope, the Feedback for C gives you a good hint on why you are incorrect.
