### ISSUE TITLE
undefined message when not supplying the required parameter of a function - Python

### ISSUE THREAD

**Issue by JuicySword** [RunestoneInteractive/RunestoneComponents#835]
When we call a function without supplying the required parameter, it displays a "undefined" message. 
Here is a sample code that you can try somewhere in the Runestone environment or use Scratch ActiveCode top right:
```python
def test(a,b=1):
    return a,b
test(b=2)
```

**Comment by bnmnetp** [comment]
I'm not seeing that.  Your example, on Runestone.academy, gives me

**Error**
TypeError: test() takes atleast 1 arguments (1 given) on line 3

**Description**
Type errors most often occur when an expression tries to combine two objects with types that should not be combined. Like raising a string to a power

**To Fix**
To fix a type error you will most likely need to trace through your code and make sure the variables have the types you expect them to have. It may be helpful to print out each variable along the way to be sure its value is what you think it should be.

**Comment by JuicySword** [comment]
The error occurs on https://fopp.umsi.education/runestone/static/fopp/index.html#
I guess, it is a older version.
