### ISSUE TITLE
questions

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/RunestoneComponents#836]
Error reported in course fopp on page SpecialWaystoExecutePythoninthisBook by user ani aninditachaudhary@gmail.com
Hi, why did you guys remove the questions? Most law schools in India have an open book test and that is more conducive and yields better results because a student is supposed to understand the problem and not memorise it.  When you gave me questions my learning improved and I understood the problem better by looking it up.  Please keep the questions because they are great help and interactive and I can self asses how much I understand the problem on hand.

**Comment by bnmnetp** [comment]
Addressed in email
