### ISSUE TITLE
Runtime Errors on examples in 8.8

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/RunestoneComponents#851]
Error reported in course How to think like a computer scientist interactive edition on page https://runestone.academy/runestone/books/published/thinkcspy/MoreAboutIteration/SentinelValuesAndValidation.html by user weisch03 chelseaweiss2021@u.northwestern.edu
Both of the examples listed (8.8.1 & 8.8.2) have runtime errors that prevent the full code from being executed, difficult to follow modification instructions as the page thinks it's in an infinite loop and exits early.

**Comment by NateJose123** [comment]
Is this still an issue?

-Nathan Jose, Berea College '20

**Comment by bnmnetp** [comment]
No.
