### ISSUE TITLE
404 not found

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/RunestoneComponents#857]
Error reported in course GCS_AP_Summer_Prep on page https://runestone.academy/runestone/books/published/apcsareview/index.html by user teamschmidt schmidt@glenelg.org
always get a 404 not found error trying to access my class page but can add student /assignments/ etc. but can not see page??    
thanks
Marc Schmidt

**Comment by bnmnetp** [comment]
Marc,

I think you caught me right in the middle of an update.
