### ISSUE TITLE
Cannot Login

### ISSUE THREAD

**Issue by ierdembayar** [RunestoneInteractive/RunestoneComponents#875]
Even I come from the coursera page, I can not login to the runestone.

**Comment by Shreesh01** [comment]
Facing the same problem. The very first day it was logged in then the next day I was logged out automatically and now I cannot sign in.

**Comment by bnmnetp** [comment]
Runestone is not affiliated with Coursera.

Runestone uses usernames not email addresses for login, so please make sure you are using the correct username to log in.
