### ISSUE TITLE
Grading

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/RunestoneComponents#877]
Error reported in course NelsonPHS on page https://www.youtube.com/watch?v=nqcv3U6uFQg&feature=youtu.be by user melissa.nelson melissa.nelson@wcs.edu
May not be a bug but none of your grading videos are working with my course.  Where can I get additional help?  Thanks

**Comment by bnmnetp** [comment]
These videos are hosted on youtube.  If youtube isn't working for you then it may be that your school district blocks youtube.  In that case you are going to have to access them from home or talk to your school about allowing valid videos on youtube.
