### ISSUE TITLE
instructor dashboard broken links

### ISSUE THREAD

**Issue by bhoffman0** [RunestoneInteractive/RunestoneComponents#878]
In the instructor dashboard, clicking on exercise links, exercise details links, or subchapter links gives errors.  This screenshot is from a teacher using csawesome.

<img width="499" alt="capture1" src="https://user-images.githubusercontent.com/4571962/63044360-0932a380-be9c-11e9-8e7e-106ffd52e7fe.png">

If you click on 1.1.Getting Started and other subchapter links here, you get a 404 error because the url is missing a ".html" on the end.
<img width="464" alt="capture2" src="https://user-images.githubusercontent.com/4571962/63044364-0c2d9400-be9c-11e9-8672-20cc308ff934.png">

**Comment by bnmnetp** [comment]
Beryl -- Notice that the links causing questions are in section GettingStarted .999 !!

If I look in the database for that question I see:

**Comment by bhoffman0** [comment]
Sorry must be my weird nested structuring again. ptest.rst is included in a :toctree directive in topic-1-1-getting-started.rst which is included in Unit1/toctree.rst.

**Comment by bnmnetp** [comment]
It may also just be an error in an old query that didn't make any difference until now...

I'm going to try a quick fix, and I'll let you know.

**Comment by bnmnetp** [comment]
Yay!  It was a simple query bug exercised by your unique configuration....

Fixed now.

**Comment by bhoffman0** [comment]
Wow, thank you!
