### ISSUE TITLE
Unable to access Instructor Page

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/RunestoneComponents#879]
Error reported in course csawesome on page toctree by user nisantiwilmot nwilmot@oakwoodway.org
I'm a teacher at Oakwood School. I'm trying to create a section so I can view student progress but when I click on the Instructor page, I get "Insufficient privileges" error message.

**Comment by bnmnetp** [comment]
You are not an instructor for the csawesome course.  In order to become an instructor you must make your own course.

Please have a look at the FAQ and the Instructor guide as linked under the help menu!
