### ISSUE TITLE
Deleting students

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/RunestoneComponents#880]
Error reported in course cs2k20192020 on page https://runestone.academy/runestone/admin/admin by user wjasik weldon.jasik@cfisd.net
I successfully deleted students on the Manage Students tab, but when I went to the Manage Sections tab and clicked on the default section they were still there.  (Also, I can't see any way to move students between sections.)

**Comment by bnmnetp** [comment]
Students are not deleted, they are removed from your course and put into the "base course" that you made your course from.  Unfortunately students were not removed from the second, so they appeared to still be there even though they are not in the course anymore.


As far as moving students to sections they need to do that themselves by editing their profile and changing the name of their section.

**Comment by bnmnetp** [comment]
fixed
