### ISSUE TITLE
1-8-8

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/RunestoneComponents#889]
Error reported in course SBHS_AP_CS-A on page topic-1-8-practice-coding by user sbarner sbarner@sbschools.net
Exercise 1-8-8 would result in a compilation error, as the result of the division of two doubles is being assigned to an int without an explicit cast.

**Comment by bnmnetp** [comment]
Tagging @bhoffman to look at this.

**Comment by bhoffman0** [comment]
You're right. I'll fix it in the next update. Thanks.
-Beryl
