### ISSUE TITLE
code bug in fopp chapter 1

### ISSUE THREAD

**Issue by jenniferskay** [RunestoneInteractive/RunestoneComponents#891]
Run this problem: Now if we compute that formula for each possible Cj then the one with the higest value is our winner.

Lets work out the example we have outlined to get the scores given our Oreo, Oreo, Oreo, Chips Ahoy! example. The probability that we get an Oreo given that it is Bowl1 is .75 And the probability that it is a Chips Ahoy! given that it is Bowl1 is .25 The probability that it is Bowl1 is .5

Results in an error: SyntaxError: EOF in multi-line statement on line 6

**Comment by bnmnetp** [comment]
Where is this?  this is definitely not in fopp chapter 1!

**Comment by bnmnetp** [comment]
Found it -- in the sentiment analysis chapter.  Just missing a )

Fixed -- will be updated on line in the next build (Saturday)
