### ISSUE TITLE
'Auto-grade' and 'Which to grade' won't update.

### ISSUE THREAD

**Issue by tluchko** [RunestoneInteractive/RunestoneComponents#892]
I have created several problems with unit tests that I would like to have auto-graded.  However, the `Auto-grade` and `Which to grade` fields stay at their default values of `Manual` and `Empty`:
<img width="950" alt="image" src="https://user-images.githubusercontent.com/31545346/63707997-20e92080-c7e8-11e9-9e92-396f15fd77f0.png">

If I try to modify the fields and save the assignment, the fields revert to the defaults when I open the assignment again.

In case I am using the directives/flags incorrectly, this is the header for one of the questions:
```
.. activecode:: TL_365_ex_2_11
   :language: python
   :autograde: unittest
```

I also tried replacing the source with the source from `ex_2_11`, which has defaults of `% correct` and `Best answer` and has the ActiveCode checkmark, but the result was the same.

**Comment by tluchko** [comment]
I think I fixed the issue.  

While the database add the '_1' suffix to ID when I created it, the source code it saved did not include the suffix.  I've added the suffix to the ID myself and it appears to grade correctly now.

Before I made this change, I would run auto grade and the student would get 0 regardless of what they had written.  I could run the code myself and see that all tests passed and run auto grade and the grade was still 0.

**Comment by tluchko** [comment]
Following up with a related problem, I have several short answer problems that I want marked ``Interaction``. (Actually, I'd be fine if they were worth 0 points.)  However, the settings don't save when I try to set 'Auto-grade' to ``Interaction`` and 'Which to grade' to ``Last``.

An example is ``TL_365_ReadingFeedback_4``.

**Comment by bnmnetp** [comment]
That was a choice... maybe a wrong one I guess.  But I never thought someone would assign a short answer and not want to read what the students wrote.

**Comment by tluchko** [comment]
I do read what the students wrote.  I'm using the questions at the end of reading assignments where they can tell me if anything was unclear or if they want something discussed in class.  There is nothing right or wrong to grade and it is fine if a student doesn't want to write anything.

**Comment by bnmnetp** [comment]
Fair.  Just my own lack of imagination about how people might use the questions.

Lets make a separate issue about auto grading short answers.   There is a group of students doing a class about open source software that has chosen to help out with Runestone development. This would be a great issue to hand off to them.

**Comment by bnmnetp** [comment]
I had to double check the code, to be sure, but the database does not append _1 to anything.  If you try to replace a question that you are not the owner of you get an error dialog and are asked to assign a new unique id to the question.

It seems more likely that you changed the id in the source and resaved it without updating the html.

**Comment by tluchko** [comment]
OK.  I'm not sure what happened.  The site won't let me write a new question or edit an existing one without generating the HTML first.  It also won't let me save a new question with an ID that already exists.

I am confident that the ID for the problem was different than what was displayed in the table but I can't reproduce this myself.

I think the original problem was addressed, so I'll close this issue myself.
