### ISSUE TITLE
shortanswer directive not working over multiple lines

### ISSUE THREAD

**Issue by raskutti** [RunestoneInteractive/RunestoneComponents#896]
When using the `shortanswer` directive, if the question goes over one line, the new line is appearing below the box. The `fillintheblank` and `mchoice` directives allow for multiple line questions.

For example, see the attached screenshot. The source is below.

```
.. shortanswer:: voting

   How do you think the researchers got information on how different groups
   voted?
```

![shortanswer_screenshot](https://user-images.githubusercontent.com/14115681/63814968-c68fb300-c900-11e9-9b65-7c443260281f.png)

**Comment by bnmnetp** [comment]
I've heard from several people over the last few days that this was a problem.  So I bumped it up and fixed it.

You can have multiple lines and any kind of restructuredText you want embedded in the question part of a short answer directive.
