### ISSUE TITLE
Missing class

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/RunestoneComponents#897]
Error reported in course CPS141-Fall2018 on page https://runestone.academy/runestone/books/published/pip2/index.html by user jtincher jtincher@wccnet.edu
I get a 404 error when trying to access my class. The progress page shows my class, https://runestone.academy/runestone/assignments/index, but I have no way to get into my class.  Everything I try related to it gives me the 404 error.

Regards,

John

**Comment by bnmnetp** [comment]
restored
