### ISSUE TITLE
Spreadsheet coltitles doesn't allow spaces

### ISSUE THREAD

**Issue by raskutti** [RunestoneInteractive/RunestoneComponents#900]
Within the `spreadsheet` directive, the `coltitles` values cannot have spaces. However within the fields themselves, spaces are allowed.

```
.. spreadsheet:: s
   :coltitles: 'column 1'
```

The above does not work, but the below does.

```
.. spreadsheet:: s
   :coltitles: 'column_1'
```

**Comment by bnmnetp** [comment]
fixed in master
