### ISSUE TITLE
View spreadsheet field as plain text

### ISSUE THREAD

**Issue by raskutti** [RunestoneInteractive/RunestoneComponents#902]
This is a tricky one (discussed offline).I want to view a spreadsheet field as plain text. For example:

- I want to write a formula but not have it evaluate. e.g. `=1+1`. When this renders in Runestone, it displays as 2, but suppose I want to literally display the string `"=1+1"`. In Google Sheets / Excel, I can use a leading apostrophe `'=1+1`.

- I want to display a comma in a string. For example, suppose I want to display the plain text `"CONCATENATE('abc', 'xyz')"`. The renderer interprets the comma as a separator, but I don't want it to in this case.

**Comment by bnmnetp** [comment]
Using the 'standard' escape scheme for csv files you can now do this: (runestone >= 4.1.1)

```
.. spreadsheet:: ss3
   :colwidths: 200,200

   "&#61;CONCATENATE(""abc"", ""xyz"")","=CONCATENATE(""abc"", ""xyz"")"
   '=1+1, 2
```

Note that the `&#61;` gives you an = that will be ignored by jExcel.  You could also do '= but the single quote will show up..
