### ISSUE TITLE
Repeated sentence

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/RunestoneComponents#903]
Error reported in course agnes_ac101f19a on page Exercises by user agnes312 cdepree+agnes312@agnesscott.edu
Small thing - On one of the questions (I think 7 or 8), the words "print a nice message" are repeated twice.

**Comment by jennahughes15** [comment]
Hello!  I'd like to fix this issue, but I am confused on the location of it.  Could you be more specific on where it is?  Thanks!

**Comment by cigas** [comment]
This seems to have been fixed already.

Unit 2 Exercises
[https://csawesome.runestone.academy/runestone/books/published/thinkcspy/SimplePythonData/Exercises.html](https://csawesome.runestone.academy/runestone/books/published/thinkcspy/SimplePythonData/Exercises.html)

Problems 8, 9 and 10 have the 'print a nice message' phrase, but it isn't being repeated.
