### ISSUE TITLE
Problems marked :practice:T break auto grading in assignments

### ISSUE THREAD

**Issue by tluchko** [RunestoneInteractive/RunestoneComponents#907]
If a problem has attribute ``:practice: T``, when it is auto-graded two grades are give, one of which is always 0.

For example ``question13_2_1`` gives this is when included in an assignment:
<img width="1171" alt="image" src="https://user-images.githubusercontent.com/31545346/64299081-af6a4a00-cf2c-11e9-88d6-35c827522cae.png">

However, if I remove ``:practice: T`` from the source, if works fine:
<img width="1173" alt="image" src="https://user-images.githubusercontent.com/31545346/64299095-b8f3b200-cf2c-11e9-9a4c-0251cb018dde.png">

**Comment by bnmnetp** [comment]
I'm not following what you mean when you say two grades are given....  Where are you looking to see how many grades are recorded?

I just tried this myself.  I added question13_2_1 to an assignment.  I answered the question correctly. and only 1 score is recorded and I receive full points.

practice and auto grade are two very very separate features and thousands of questions have `:practice: T` so I think something else is going on here or I would be hearing from hundreds of people about this.

**Comment by tluchko** [comment]
You're right.  When I create a new assignment and add question13_2_1 everything works fine.  There is only one Score and the total points is the same as total number of questions.

However, on the existing assignment, in addition to the double Score in the original screenshot, there are only 16 question but it is graded out of 17.  I'd rather not modify the existing assignment if possible since students are already working on in.

I copied the assignment to a test course and see the same issue.  In this case, I tried deleting question13_2_1 but the student view still contains the question. (I did answer the question before trying to delete it.)

**Comment by bnmnetp** [comment]
Which assignment is this?

**Comment by bnmnetp** [comment]
Just guessing, but I think this is the assignment and it does have 17 points:

```
+--------------------------+---------------+------------------------------------+----------+
| name                     | chapter       | subchapter                         | points   |
|--------------------------+---------------+------------------------------------+----------|
| db_q_ex3_1               | Debugging     | intro-HowtobeaSuccessfulProgrammer | 1        |
| question4_1_1            | Debugging     | intro-HowtobeaSuccessfulProgrammer | 1        |
| question4_4_1            | Debugging     | Syntaxerrors                       | 1        |
| question4_4_2            | Debugging     | Syntaxerrors                       | 1        |
| question4_6_2            | Debugging     | SemanticErrors                     | 1        |
| question4_5_1            | Debugging     | RuntimeErrors                      | 1        |
| question4_5_2            | Debugging     | RuntimeErrors                      | 1        |
| question4_6_1            | Debugging     | SemanticErrors                     | 1        |
| question4_7_1            | Debugging     | KnowyourerrorMessages              | 1        |
| question13_1_1           | PythonModules | intro-ModulesandGettingHelp        | 1        |
| question13_1_3           | PythonModules | intro-ModulesandGettingHelp        | 1        |
| question13_1_2           | PythonModules | intro-ModulesandGettingHelp        | 1        |
| vid_modules              | PythonModules | intro-ModulesandGettingHelp        | 1        |
| question13_2_1           | PythonModules | Therandommodule                    | 1        |
| question13_2_2           | PythonModules | Therandommodule                    | 1        |
| TL_365_ReadingFeedback_4 | PythonModules | Exercises                          | 1        |
| TL_365_question13_2_1    | PythonModules | Exercises                          | 1        |
+--------------------------+---------------+------------------------------------+----------+
```

**Comment by bnmnetp** [comment]
The reason you only see 16 items on the assignment page is that one of the "problems" you assign is a video which cannot be shown except on the page it was created.

**Comment by tluchko** [comment]
You are right.  That is the assignment and the video was the cause of the extra point.  I deleted the video and the total score is what I expected and the double score for question13_2_1 is gone.

Thank you!
