### ISSUE TITLE
Deleting bad exercises

### ISSUE THREAD

**Issue by bhoffman0** [RunestoneInteractive/RunestoneComponents#913]
Could you please delete the following exercises which are incorrect or incomplete or replaced in the csawesome course. Thanks!
- thirdClassCustom
- lccv1_1
- challenge1-6
- 1.1.a
- test1
- test2
- MadLibs
- PigLatin
- TroyTest1
- uniqueid

**Comment by bnmnetp** [comment]
Thanks for the list.  This just illustrates the complexity in deleting a question.   I looked at:
`lccv1_1` as an example and found that it is part of an assignment in the following courses right now!

```
	name	course_name	duedate
0	lccv1_1	PCA_AP_CS	2019-09-11 00:07:00
1	lccv1_1	MVTHSCSA	2019-09-11 10:29:00
2	lccv1_1	CSA-19-20	2019-09-06 03:23:00
3	lccv1_1	ofhs_java	2019-09-11 15:54:00
4	lccv1_1	CSSEDU6730Fall2019	2019-09-11 20:33:00
5	lccv1_1	CSA19_20	2019-09-09 08:00:00
6	lccv1_1	APCSA-2019B	2019-09-12 17:46:00
7	lccv1_1	CA-CSA	2019-09-10 21:00:00
8	lccv1_1	FitzAPCSA	2019-09-20 10:25:00
9	lccv1_1	PHS_CS_Awesome	2019-09-14 16:47:00
```
thirdClassCustom is included in over 30 assignments.

**Comment by bhoffman0** [comment]
That is a problem! I think it's people including it without realizing that it doesn't really exist in the published course anymore for those two. I'm not sure what to do about it though.

**Comment by bnmnetp** [comment]
So...

* We know all of the questions we have that were ever part of the book
* We know all of the questions that are part of the book as of the last build
* We know the additional questions that were added by instructors.

That leaves 89 questions in the database that are outdated.

Deleting them will cause some pain, leaving them in means that the students can ONLY access the questions from the assignments page, but the longer we leave them in the harder it is to fix.

One possibility is that I mark all 89 of those questions as private so they are no longer available to anyone other than me to add to a new assignment.

**Comment by bhoffman0** [comment]
I like making those 89 questions private if that will cause less problems than deleting them.
The ids below were submitted by other instructors but should be deleted as incomplete or test questions:
1.1.a
test1
test2
TroyTest1
uniqueid

**Comment by bnmnetp** [comment]
All of them are included in assignment as well...  OMG uniqueid is included in 72 assignments....

It might be good to talk about this as part of your webinar on Wednesday!

**Comment by bnmnetp** [comment]
OK I've marked all of those as private.

**Comment by bnmnetp** [comment]
I kind of want to put up a big confirmation dialog if someone clicks on Exercises!

**Really!??!**  Are you **absolutely sure** you want to assign X problems that you haven't even reviewed to your students for this assignment?

**Comment by bhoffman0** [comment]
Thanks! That's a good idea too :-)! 
I'll bring this problem up on Wed. They're newbies.
