### ISSUE TITLE
Not working video.

### ISSUE THREAD

**Issue by Rombeso** [RunestoneInteractive/RunestoneComponents#915]
Not working video on the page 2.11. Order of Operations
I use Google Chrome Version 76.0.3809.132 (Official Build) (64-bit)
You can see that on the screenshot http://prntscr.com/p3tla4

**Comment by bnmnetp** [comment]
What course are you in?  Whatever it is, I can tell that it is not a recently built course and is missing a lot of bug fixes and updates.

**Comment by Rombeso** [comment]
Course name is Python Basics

**Comment by bnmnetp** [comment]
There is no course called "Python Basics" . There is a course from 2017 called PythonBasics, but I don't think you are looking at that one as its not the right book.

giving us an actual URL of the page you are on would help a ton.

**Comment by Rombeso** [comment]
https://fopp.umsi.education/runestone/static/fopp/SimplePythonData/OrderofOperations.html

https://www.coursera.org/learn/python-basics/supplement/gBi7H/order-of-operations

**Comment by bnmnetp** [comment]
Please contact your instructor at the University of Michigan or Coursera.  We have no control over the content of the videos from the Coursera and Michigan  courses.

**Comment by presnick** [comment]
Almost all the videos within the Coursera textbook are currently not working. We will be deploying a fix in October.

You'll generally be better off with the Coursera videos, in any case.
