### ISSUE TITLE
Question saved with source code from a different question

### ISSUE THREAD

**Issue by tluchko** [RunestoneInteractive/RunestoneComponents#916]
After I edited a question that I added, TL_365_ch_6_1, the question comes up with the source of a completely different question, TL_365_matrix_multiply.  Students are also shown the wrong content for TL_365_ch_6_1.  The edit I made was quite minor, I deleted one character, and I generate the HTML before I saved it.

You can see what the source code should be by looking at TL_365_ch_6_1_fix. Note, I intensionally added this as a new question with a different ID.

As it may be a contributing factor, I'll note that I had two tabs open to two different pages, the Assignments and Grading pages, at the time when this occurred.

It seems this might be related to issue #892, specifically starting at https://github.com/RunestoneInteractive/RunestoneComponents/issues/892#issuecomment-525082474_

I think this will be difficult to reproduce but you should be able to at least see the problem.

**Comment by bnmnetp** [comment]
What I can see in the database is question TL_365_ch_6_1_fix looks fine. The name, the rst source and the html in the database are all consistent.

But for TL_365_ch_6_1  - the rst source for that question includes the instructions to print letter 'C' from this list and to print letters 'C', 'D', 'E' as a list. whereas the the stored html (what we use for showing the assignments page) has the text for the TL_365_matrix_multiply question.

So I want to make sure I have a really clear picture of the sequence of edits you did, because I think there is a sequence of events that can lead to your situation.  😭 

Did you create, preview, or edit the matrix_multiply question in the modal dialog?

When you saved _ch_6_1 in the editor were you prompted to preview the html?

**Comment by bnmnetp** [comment]
So, there is definitely a hole that would allow you to be working on adding questions and using the editing interface, click save and not be prompted to regenerate the html where the html would correspond to the last question you had previewed in the modal editing dialog...

I've plugged said hole and will push it live after a bit more testing.

**Comment by tluchko** [comment]
At this moment, when I click on 'Edit Source' for TL_365_ch_6_1 I get the source for TL_365_matrix_multiply. This may be because when I click on TL_365_ch_6_1 from Browse, I get the TL_365_matrix_multiply HTML.

I'm quite sure (but can't guarantee or confirm) that I clicked on 'Generate/View HTML' after I edited TL_365_ch_6_1 because it has become automatic for me at this point.  Whenever I have purposefully tried to skip this, the website won't let me save.

I also know I brought up TL_365_matrix_multiply in the editor a few minutes earlier and deleted a line from the source.

Hopefully your fix will prevent this from happening in the future.  I write and edit my questions offline as much as possible; so, I can wait a couple of days

**Comment by bnmnetp** [comment]
Good news -- I think I finally have got to the bottom of what's going on in the code...  A series of unfortunate decisions that leads to what you see.

Part I - in place will do more to prevent unwanted accidental saves.

Part - II - to fix the behavior that explains what you are seeing in the interface and what I am seeing in the database and makes things right.

After this, you should be able to bring up questions that are "out of sync" and get them back in order with a quick regenerate of the html and save.

**Comment by bnmnetp** [comment]
I think I have it!  Please check out TL_365_ch_6_1 - when you edit it now you should get the correct source, and be able to rebuild the html to get the preview correct as well...

**Comment by tluchko** [comment]
Yes, when I clicked on edit I got the correct source and was able to rebuild HTML.  It looks like its working now.

Thanks!

**Comment by bnmnetp** [comment]
Wonderful!

In the process I figured out what how to catch an editing event in the textarea and invalidate the html.  Now if you make any kind of change you will be forced to rebuild. No more honor system. 😄 

Hopefully this is the end of this bit of problems.

Thanks for your patience and help in tracking this down.
