### ISSUE TITLE
No Run Button

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/RunestoneComponents#922]
Error reported in course C120-thinkcspy on page IndexOperatorWorkingwiththeCharactersofaString by user jya184 justin_yan_3@sfu.ca
This happens with other pages and sections as well. Sometimes the interactive segments do not display a button to run the code in order to gain progress towards completion for the tasks.

**Comment by NateJose123** [comment]
Is this still an issue?

-Nathan Jose, Berea College '20

**Comment by bnmnetp** [comment]
No, this was a stale cache issue, and has been fixed..
