### ISSUE TITLE
Erroneous Audio Tour Links

### ISSUE THREAD

**Issue by soney** [RunestoneInteractive/RunestoneComponents#927]
It appears that including an `:available_files: ...` directive gets consumed as an `audio` directive, meaning that any activecode with `:available_files` also includes an "Audio Tour" button. The problem appears to be in the way that runestone/activecode/active.py parses its template. `self.options['ctext']` is set to the value of `:available_files` and then gets passed on to `data-audio` in the rendered page (see below)

I'll submit this as an issue rather than a PR to avoid making a "fix" that breaks something else.

from runestone/activecode/active.py:

```
        newcomplete = complete.replace("\"", "*doubleq*")
        self.options['ctext'] = newcomplete
```

...

```
TEMPLATE_END = """
<textarea data-component="activecode" id=%(divid)s data-lang="%(language)s" %(autorun)s
    %(hidecode)s %(include)s %(timelimit)s %(coach)s %(codelens)s %(enabledownload)s %(chatcodes)s
    data-audio='%(ctext)s' %(sourcefile)s %(datafile)s %(stdin)s %(tie)s %(dburl)s %(nopair)s
    %(cargs)s %(largs)s %(rargs)s %(iargs)s %(gradebutton)s %(caption)s %(hidehistory)s>
%(initialcode)s
</textarea>
</div>
"""
```

...

```
    res = TEMPLATE_END % node.ac_components
```

**Comment by bnmnetp** [comment]
fixed
