### ISSUE TITLE
Does local development require a database?

### ISSUE THREAD

**Issue by alexmojaki** [RunestoneInteractive/RunestoneComponents#931]
I'm trying to contribute to this project for the first time. I followed the instructions in the README and things went smoothly. However when I run any `runestone` command the first thing I see is:

```
Cannot configure a Database URL!
Skipping all DB operations because environment variables not set up
```

Digging around in the source code I figured out I could set `WEB2PY_CONFIG` and `DEV_DBURL`. I tried sqlite and that failed with an obscure error, so I tried postgres and that sort of worked, after installing psycopg2 and making a database. Except it didn't actually work because none of the tables exist.

Do I need a database for testing and development? If not, I think there should be some documentation or an error message indicating this. If so, how is it set up?

**Comment by bnmnetp** [comment]
If you are just trying to build books or contribute to RunestoneComponents then the error message is harmless.  If you are trying to set up a complete environment then you should follow the instructions for RunestoneServer, which would tell you to run `rsmanage initdb` to get a database set up.

Or you can follow the instructions for setting up a server in Docker.
