### ISSUE TITLE
Lost communication with server.

### ISSUE THREAD

**Issue by tgblake** [RunestoneInteractive/RunestoneComponents#934]
I had a glitch with my router.  It's fine now, but I still get an "Error communicating with server" when I try to run an exercise.

**Comment by bnmnetp** [comment]
Are you still having trouble?  Did you reload the page?  The only way you get that error is if it can't make a connection to Runestone and the server is alive and well.  So maybe you still have some kind of router issue.

**Comment by tgblake** [comment]
I did reload the page and the problem never went away, but it was only on that exercise.  Later exercises were OK, so I skipped that one.

Thanks,
    Terry
_________

**Comment by bnmnetp** [comment]
I have no idea what exercise you were having trouble with, but if it continues to be a problem I'd like to investigate and make sure it isn't a server problem on my side.

**Comment by tgblake** [comment]
Bradley,
	I looked back and couldn’t remember which exercise it was in the section on dictionaries, especially since a lot of my code was deleted when I use the forward and back arrows (a bug in itself, IMO).

Thanks,
    Terry
_________

**Comment by bnmnetp** [comment]
If you create an account, then Runestone saves all your code and lets you go through your code history for all activecode exercises and examples.

**Comment by tgblake** [comment]
I’m sorry, I forgot about the history slider, and didn’t notice it was still there.

Thanks,
    Terry
_________
