### ISSUE TITLE
Can't login on my runstone

### ISSUE THREAD

**Issue by hilary500** [RunestoneInteractive/RunestoneComponents#938]
I have reset my password change browser still unable to login so to submit my assessment

**Comment by bnmnetp** [comment]
We can't help you if you don't tell us the course you are in or the username that you are trying to reset.

Note:  If you are coming for coursera please contact your TA for help.  We can't help with that here.

**Comment by hilary500** [comment]
actually the course i'm trying to work on is python 3  i don't if i want to do the assessment i will be showing not login i can't do any assignment and coursera directed me to you guys
![ddddd](https://user-images.githubusercontent.com/56406920/66690266-34dbcb00-ec4c-11e9-9da0-eb1a995c7248.png)

**Comment by bnmnetp** [comment]
@presnick Coursera should not be directing people to report problems here.

**Comment by hilary500** [comment]
what do i need to do Mr. Bnmnetp i need your help all the instruction have been done still nothing change

**Comment by bnmnetp** [comment]
I’m sorry, but I cannot help you.  I don’t have any access to the server you are trying to connect to. 

Where did you find that URL?  I would double check the course materials to make sure you are trying to connect to the right server.  I don’t think you should be able to access that page for a coursera course without logging in first.

Again, this is not anything that we as developers have control over.  You should be getting support from the TAs for your coursera course.

**Comment by presnick** [comment]
The way to log in to the Coursera Python3 runestone server is by following a link from the course in Coursera. 

For example, from https://www.coursera.org/learn/python-basics/home/week/2 near the top of the page you'll see a link that says, "Single Sign On: Interactive Textbook and Practice Opportunities". Once you click on that, for the next couple of days any of the other links to specific pages will take you to the textbook and have you already logged in. Accessing any of the assignments will also automatically log you in.

Can you tell us who at Coursera directed you to post here? We'd like to communicate with them to make sure they are giving better direction to Coursera learners. Thanks.

**Comment by presnick** [comment]
...by "accessing any of the assignments" I mean accessing the assessment by following the link from Coursera. For example, from https://www.coursera.org/learn/python-basics/gradedLti/5g9kr/assessment-lists-and-strings
