### ISSUE TITLE
Extension runestone.lp shadows variable 'docname'

### ISSUE THREAD

**Issue by DaveParillo** [RunestoneInteractive/RunestoneComponents#944]
When building a book with Runestone version 4.1.11,  the following warning is displayed:

    WARNING: while setting up extension runestone.lp: role 'docname' is already registered, 
    it will be overridden

**Comment by bjones1** [comment]
Ignore -- this isn't a problem. CodeChat defines `docname`, then Runestone re-defines a customized version of it.

**Comment by DaveParillo** [comment]
OK, but it seems odd that the literate programming module is the only component warning about this.
