### ISSUE TITLE
Missing code in example AP FRQs

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/RunestoneComponents#945]
Error reported in course 2019_20_APCSA_Becker on page ArrayTesterB by user ALT200709661 200709661@student.lbschools.net
When attempting the 15.11 ArrayTester Part B FRQ, the code for ArrayTester.containsDuplicates(), ArrayTester.hasAllValues(), and ArrayTester.getColumn() are not provided. This problem requires the use of these methods, which cannot be used, throwing a "cannot find symbol" error instead.

**Comment by bhoffman0** [comment]
I added the required code and it will be live on Saturday morning.

**Comment by bnmnetp** [comment]
Great!
