### ISSUE TITLE
The radio buttons have changed to squares

### ISSUE THREAD

**Issue by ericsonga** [RunestoneInteractive/RunestoneComponents#95]
The radio buttons for single answer multiple choice questions have changed to squares.  I prefer circles to help differentiate them from multiple answer multiple choice questions.

**Comment by bnmnetp** [comment]
Are you sure?  They are still radio buttons on single answer questions for me.  I just looked at a brand new build of a quiz.

There was a bug where the multiple answer questions were showing up as radio buttons until last week. When the deprecated mchoicema directive was used.

**Comment by ericsonga** [comment]
This seemed to have cleared up.  I don't know what caused it.
