### ISSUE TITLE
Addition of C++ syntax highlighting

### ISSUE THREAD

**Issue by cbondurant** [RunestoneInteractive/RunestoneComponents#953]
I am one of the members of the team who are working on adding color syntax support through codemirror for C++. 
We have currently gotten so far as to have basic highlighting, as in comments, number literals, and string literals. Still, we believe that the updating of the codemirror files within runestone components will resolve this. 
There are additional complications in the fact that codemirror is passed its language mode through the same variable used to decide what kind of activecode runner will be used. `cpp` is used in the RST file for the language variable. However, codemirror expects c syntax highlighting to be referred to by `clike`. We are currently unsure where precisely this value is passed to the actual rendered webpage, and expect that it will need to be resolved before this can be completed.

**Comment by bnmnetp** [comment]
Look at the `createEditor` function in `activecode.js` you will see how I handled for setting up java and sql.

**Comment by cbondurant** [comment]
closing issue as this was merged over half a year ago.
