### ISSUE TITLE
Not being able to log into Runestone

### ISSUE THREAD

**Issue by canyanwucharles** [RunestoneInteractive/RunestoneComponents#962]
I have been doing my assignments on Runestone relating to Python 3 programming through cousera but after a day of inactivity, I could not see my checked completed assignments. There is also no means of clicking the save button and continue. A prompt was telling me user not signed in on Runestone but at same time I was signed in through coursera. Please I need help so I can proceed with my assignments.

**Comment by bnmnetp** [comment]
Sorry, but we cannot help you with issues related to coursera and how they are linking to our textbooks.  We have no control over their servers.  In the past this has been the answer from Professor Resnick.

> There is a “single sign-on” link near the top of each week in Coursera. Once you follow that you’ll be logged in for a while, and it keeps renewing every time you visit a page. So unless you’re away for a while you won’t have to keep using it.
