### ISSUE TITLE
Update the required 'requests' package version to 2.22.0

### ISSUE THREAD

**Issue by chensivan** [RunestoneInteractive/RunestoneComponents#966]
The current required version of 'requests' package is 2.18.4 which is incompatiable with the required version of urllib3 (1.24.2). See the error message i got in my terminal

![image](https://user-images.githubusercontent.com/2650733/68692197-0ef36000-0543-11ea-9bef-8ce6ff012d7e.png)

**To Reproduce**

execute the `runestone build` in your terminal once finishing the first step `pip install -r requirements.txt`

I fixed it by manually updating 'requests' package to 2.22.0 which is the latest one, and everything works fine. 

**Desktop (please complete the following information):**
 - OS: Mac 10.14.6

**Comment by bnmnetp** [comment]
I'm going to see how it goes when I remove urllib3 from the requirements.txt file.  The only reason it was there was to get around an earlier issue with requests.
