### ISSUE TITLE
MathJax rendering not applied on feedback in `mchoice` directive

### ISSUE THREAD

**Issue by donnerc** [RunestoneInteractive/RunestoneComponents#968]
Currently, the MathJax rendering is done on page load but not when the DOM is modified. Hence, the feedbacks of `mchoice` including math are not rendered properly. To improve the situation : call

```
MathJax.Hub.Queue(["Typeset",MathJax.Hub]);
```

after the feedback has been added to the DOM.

**Comment by bnmnetp** [comment]
Fixed
