### ISSUE TITLE
Runestone not logging in

### ISSUE THREAD

**Issue by seanred111** [RunestoneInteractive/RunestoneComponents#973]
When I use runestone it says 'user not logged in' in bottom left corner. It therefore doesnt update my 'compares' nor my score. Any help please?

**Comment by bnmnetp** [comment]
What does the 👤 menu show?  What course did you register for?  Why don't you just log in??

**Comment by seanred111** [comment]
Solved, thank you. My own fault :)
    On Tuesday, December 10, 2019, 09:08:34 PM GMT+2, Bradley Miller <notifications@github.com> wrote:  
 
 
What does the 👤 menu show? What course did you register for? Why don't you just log in??
