### ISSUE TITLE
 Please log in via your Learning Management System

### ISSUE THREAD

**Issue by chaitanyataware10** [RunestoneInteractive/RunestoneComponents#975]
I am unable to log in to runestone interactive. It shows the issue like "
Please log in via your Learning Management System".
When i am trying to get my username via email it said no registered email.
please help.

**Comment by bnmnetp** [comment]
Are you coming from Coursera?  We don't have any control over that.

Here's what you should know:

At the top of the activities for each week, you should see an activity titled, "Ungraded External Tool: Single Sign On: Interactive Textbook and Practice Opportunities". That will log you into the textbook. Once you've done that, you will be able to follow any of the other links to particular pages. If you've been away from the textbook for a couple days, you may need to access the Single Sign On activity again to login to the textbook again.
