### ISSUE TITLE
wrong language

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/RunestoneComponents#977]
Error reported in course pythoned on page index by user 0987jjb jessebyrtus@yahoo.com
I just created a logon, and selected a course however now the language changed to Spanish. I didn't request Spanish, nor do I want to learn Spanish to take the course.

**Comment by bnmnetp** [comment]
You are registered for pythoned, which is the Spanish version of pythonds.  Use the Change course feature to register for pythonds and you will have your English.
