### ISSUE TITLE
Insufficient privileges message

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/RunestoneComponents#980]
Error reported in course thinkcspy on page https://runestone.academy/runestone/default/courses by user thoffert tim.hoffert@jeffco.k12.co.us
I am registered as an instructor. But today when I tried to access the Instructors Page, I received an "Insufficient privileges error. I have not encountered this error before. I have been presenting the curriculum (including assignments and grading) since January 8. Hopefully you can restore my rights as an instructor, or diagnose the issue without too much fuss. I would submit through github, but the school district's filter prevents my access to github.

BTW: I love this curriculum and the tools it provides to me and my students.

**Comment by bnmnetp** [comment]
resolved via email
