### ISSUE TITLE
System Deletes Code

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/RunestoneComponents#983]
Error reported in course MSUD_Nam_CS1050_Spring_2020 on page topic-2-4-methods-with-params by user Marie34Ann apearso4@msudenver.edu
While either writing code or finished with coding, the page will refresh and delete everything. Then I will have to start all over again making difficult to get through all the lessons for the week. This is with both code exercises and  code challenges section

**Comment by bhoffman0** [comment]
If you're logged in, everything is saved. If you refresh the page, click on
Load Code above the Active Code windows and move the play bar to the right
to see your last answer.
