### ISSUE TITLE
Beta asgn as timed assessment assumes Python in Java course

### ISSUE THREAD

**Issue by bhoffman0** [RunestoneInteractive/RunestoneComponents#987]
Just set an assignment as a timed assessment in CSAwesome and when you hit run on any activecodes, it runs them through the python compiler instead of Java.

![image](https://user-images.githubusercontent.com/4571962/75684066-25decf00-5c66-11ea-9e91-55344fc3d133.png)

**Comment by bnmnetp** [comment]
Beryl, This should work now.
