### ISSUE TITLE
Unable to remove students

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/RunestoneComponents#989]
Error reported in course IMSA_CSI_Python on page Nonehttps://runestone.academy/runestone/admin/admin by user tmeyer tmeyer@imsa.edu
We are preparing for a new semester, and would like to remove all previous students. When I try, I always get an error:
"502 Bad Gateway
nginx/1.10.3 (Ubuntu)"

How can we remove old students?

Thanks,
Tom Meyer

**Comment by bnmnetp** [comment]
Removing students en-masse is time consuming, I think that the request is timing out.

Please just make a new course and copy your old assignments.  Its nicer to the students to leave them in place so they can go back and see their old work. 😄
