### ISSUE TITLE
Dark mode update?

### ISSUE THREAD

**Issue by GregDowl** [RunestoneInteractive/RunestoneComponents#991]
Personally I don't really like the look of the current dark mode, I've tried finding where it is in the code but am not having any luck getting it to work locally.

If anyone can make a more viewable dark mode that would be amazing

**Comment by bnmnetp** [comment]
What is it that you don't like?  Web site appearances are pretty subjective, so just vaguely stating that you don't like something isn't all that useful.

For some context, this feature was added by a group of students taking part in a course on contributing to open source software projects.  See PR #972 to see the files they changed.
