### ISSUE TITLE
In dark mode, CodeLens has white text with a white background

### ISSUE THREAD

**Issue by GeekLad** [RunestoneInteractive/RunestoneComponents#995]
When using Runestone in dark mode, the code cannot be seen in the CodeLens stepper because it has white text with a white background.

![image](https://user-images.githubusercontent.com/143769/76857448-d1be1800-682b-11ea-852f-dd1c9298f648.png)

Also, the variable frame has a rather light background with white text, which is difficult to read.

To reproduce:

- Enable dark mode
- Go to any page with a code section that has variable assignments and click **Show in CodeLens**

The stepper will show line numbers with blank lines (white text on white background).  Also the Global frame will appear with a very light background and white text, which is very difficult to read.

**Comment by GeekLad** [comment]
Closing out, I just tried dark mode again and it's displaying properly.  This was on the University of Michigan's fopp, which is running Runestone 4.1.17.  It's possible they were running an older version when I encountered the issue.

**Comment by bnmnetp** [comment]
I fixed it this morning on runestone.academy and pushed a change to the master of Runestone Components. I'll do a new release this weekend to make the fix generally available.
